import PeleadoresHero from '@/app/peleadores/components/PeleadoresHero'
import makhachev from '@/assets/peleadores__images/0-100/10-20/islam-makhachev/makhachev.png'
import khabib from '@/assets/peleadores__images/0-100/10-20/islam-makhachev/makhachev_khabib.jpg'
import styles from '@/app/peleadores/components/peleador.module.css'
import Image from 'next/image'
import Link from 'next/link'
import AsideFighter from '@/app/components/asides/AsideFighter'
import type { Metadata } from 'next'
import EndArticle from '@/app/components/EndArticle'

export const metadata: Metadata = {
    title: 'Islam Makhachev',
    description: 'Islam Makhachev es un peleador de Daguestán que compite en la división de peso ligero de la UFC, donde compite desde mayo de 2015, cuando hizo su debut ante el estadounidense Leo Kuntz.',
    openGraph: {
        title: 'Islam Makhachev',
        description: 'Islam Makhachev es un peleador de Daguestán que compite en la división de peso ligero de la UFC, donde compite desde mayo de 2015, cuando hizo su debut ante el estadounidense Leo Kuntz.',
        url: 'https://fullmma.org/peleadores/islam-makhachev'
    }
}

export default function Makhachev () {
    return(
        <main>
            <PeleadoresHero peleadoresImage={makhachev} w={26} l={1} d={0} nombre='Islam Makhachev' apodo={null} categoria='Peso Ligero' />
            <section className={styles.peleador__articles__container}>
                <article className={styles.peleador__article}>
                    <h2 className={styles.peleador__article__title}>UFC Makhachev</h2>
                    <p className={styles.peleador__article__text}>Islam Makhachev es un peleador de la República de Daguestán que compite en la división de peso ligero de la <Link href='/articulos/ufc'>UFC</Link> desde mayo de 2015, cuando hizo su debut ante el estadounidense <b>Leo Kuntz</b> en el <b>UFC 187</b>. </p>
                    <p className={styles.peleador__article__text}>Su estilo de pelea es típico de los luchadores de la zona rusa de Daguestán, donde son expertos en la lucha y en Sambo, teniendoo una alta efectividad en los derribos, y consiguiendo que la mayor parte de sus victorias vengan por la vía de la sumisión. En este sentido, aún con sus diferencias y sus matices, es un peleador parecido a su amigo y miembro de su esquina <Link href='/leyendas/khabib-nurmagomedov'>Khabib Nurmagomedov</Link>, quien con su estilo de lucha supo marcar la difencia por sobre los demás peleadores, convirtiéndose en un histórico campeón de la división de 155lbs. </p>
                    <p className={styles.peleador__article__text}>Destacaría especialmente en la compañía el día 22 de octubre de 2022, cuando en el <b>UFC 280</b> se enfrentaría al brasileño <Link href='/peleadores/charles-oliveira'>Charles Oliveira</Link> por el campeonato de peso ligero de la UFC, logrando una victoria por sumisión en el segundo asalto que lo convertiría en el nuevo campeón de peso ligero en la compañía. </p>
                    <h2 className={styles.peleador__article__title}>Makhachev Record</h2>
                    <p className={styles.peleador__article__text}>Islam Makhacev posee un récord profesional de 26-1. Siendo 5 de sus victorias por la vía del nocaut, siendo 12 por sumisión y siendos 9 de sus victorias por decisión. Mientras que la hasta ahora única derrota de su carrera fue por la vía del KO.</p>
                    <h2 className={styles.peleador__article__title}>Islam Makhachev & Khabib Nurmagomédov</h2>
                    <p className={styles.peleador__article__text}>Nacido el 27 de octubre de 1991, Majachkala, Duguestán (Rusia). A los 11 años de edad, en la escuela, conoce a Abubakar, sobrino de Abdulmanap Nurmagomedov, exmilitar y exjudoca ruso. Abubakar entrenaba con Khabib, hijo de Abdulmanap, de esta forma comienza la amistad entre Khabib e Islam (menor por dos años)</p>
                    <Image className={styles.peleador__article__image} src={khabib} alt='Islam Makhachev junto a Khabib Numagomédov y el padre de Khabib'/>
                    <p className={styles.peleador__article__text}>De esta manera, Makhachev, se volvió parte de la familia Nurmagomedov. En reiteradas ocasiones, ambos han declarado que se sienten como hermanos. Abdumanap se encargó de entrenar a ambos peleadores. Y aunque actualmente Khabib no está en el equipo de Makhachev, su relación sigue siendo igual.</p>
                    <h2 className={styles.peleador__article__title}>Islam Makhachev Historia</h2>
                    <p className={styles.peleador__article__text}>Siendo de etnia Lak, Islam Ramazanovich Makhachev nació en la ciudad de Majachkalá, en Daguestán, Rusia. Su padre se dedicaba a cultivar tomates y a trabajar como conductor, mientras que su madre era una ama de casa que dirigía una pequeña cafetería. Comenzó a entrenar desde los 7 años, con la idea de ser capaz de defenderse y de mantenerse fuerte, siendo el Taekwondo el primer arte marcial en el que se adentraría. Durante un tiempo también jugó fútbol luego de que se familia se mudara a otra ciudad. </p>
                    <p className={styles.peleador__article__text}>En febrero de 2014 se convertiría en Campeón Nacional Ruso de Sambo de Combate en su división, logrando clasificar para el campeonato mundial en Japón. Campeonanto en el que lamentablemente no pudo competir por una afección cardíaca.</p>
                    <p className={styles.peleador__article__text}>Haría su debut profesional en las MMA el 1 de agosto de 2010, enfrentando al oriundo de Azerbayán <b>Mogamed Bekbolatov</b>, a quien luego de 2 asaltos vencería por decisión unánime. Pelearía en diversas promotoras, especialmente en Rusia , hasta que le llegaría la oportunidad de firmar con la UFC, a la que llegaría con un récord de 11-0, ganando 2 de sus combates por nocaut, 5 por sumisión y 4 de estos por decisión. </p>
                    <p className={styles.peleador__article__text}>Su debut en la compañía de artes marciales mixtas más grande del mundo lo haría día 25 de mayo de 2015, cuando enfrentaría para ello al estadunidense <b>Leo Kuntz</b>, a quien sería capaz de someter en el segundo asalto de la pelea. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/yLLTQ4wE58Y?si=PR7UBylP9cjCDYWH" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Su segunda pelea en la UFC, que tendría lugar el 3 de octubre de 2015 en el UFC 192, sería su primer y hasta el momento única derrota, cuando enfrentaría al brasileño <b>Adriano Martins</b>, quien en el primer asalto dejaría KO a nuestro protagonista, dejando su récord profesional en 12-1.</p>
                    <p className={styles.peleador__article__text}>Sin embargo, luego de aquella dolorosa derrota, comenzaría una racha de victorias aún más larga que la que había conseguido hasta ese momento. Siendo la primera de estas victorias la que tuvo lugar el 17 de septiembre de 2016, cuando enfrentando a <b>Chris Wade</b>, al cabo de 3 asaltos sería capaz de vencer por decisión unánime. </p>
                    <p className={styles.peleador__article__text}>Pelearía solo una vez en el año 2017, para enfrentar el 11 de febrero al americano <b>Nik Lentz</b> en el UFC 208, contra quien conseguiría una victoria por decisión unánime. El año siguiente sería más activo, al pelear en 2 ocasiones, primero en enero ante el brasileño <b>Gleison Tibau</b>, a quien conseguiría conectarle un KO en el primer asalto, y luego julio ante el canadiense <b>Kajan Johnson</b>, a sería capaz de finalizar sometiéndolo en el primer asalto. </p>
                    <p className={styles.peleador__article__text}>Una de las peleas que más se le complicaría, sería la que tendría el 20 de abril de 2019 en un evento organizado en Rusia, cuando enfrentando al luchador armenio debutante <Link href='/peleadores/arman-tsarukyan'>Arman Tsarukyan</Link>, con quien tendría un combate que se extendería hasta los 3 asaltos, donde nuestro protagonista conseguiría alzarse victorioso por decisión unánime. Esta pelea le valdría para ganar el primer bono de su carrera a la Pelea de la Noche. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/dmTKu3R7mXU?si=hs5a34cRcKbe4hn8" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>En septiembre de ese mismo año volvería a pelear para enfrentar al brasileño <b>Davi Ramos</b>, a quien lograría vencer por decisión unánime luego de 3 asaltos. En su siguiente combate con fecha para el 6 de marzo de 2021 en el UFC 259, luego de tomarse un año de inactividad durante el 2020, se enfrentaría al estadounidense <b>Drew Dober</b>, a quien conseguiría derrotar por sumisión en el tercer asalto de la pelea, ganando por esto el bono a la Actuación de la Noche. </p>
                    <p className={styles.peleador__article__text}>Para el 17 de julio de 2021 encabezaría su primer evento al enfrentar al brasileño <b>Thiago Moises</b>, en una pelea que llegaría al cuarto asalto, y en la que Islam Makhachev sería capaz de someter a su rival, llevándose la victoria. En su siguiente pelea con fecha del 30 de octubre del mismo año, se enfrentaría al peleador de Nueva Zelanda <b>Dan Hooker</b> en el UFC 267, consiguiendo una meritoria victoria por sumisión en el primer asalto, al ser capaz de conectar un Kimura para finalizar a su rival. </p>
                    <p className={styles.peleador__article__text}>Luego de aquella importante victoria, volvería a encabezar un evento el 26 de febrero de 2022, para enfrentar al luchador estadounidense <b>Bobby Green</b>, a quien en tan solo 1 asaltos sería capaz de derrotar por nocaut, en lo que ya era su décima victoria consecutiva en la UFC.</p>
                    <p className={styles.peleador__article__text}>De esta manera, ya con un récord de 22-1 y 10 victorias consecutivas en la división, a Islam se le daría la oportunidad de pelear por el campeonato de Peso Ligero de la UFC, enfrentando al brasileño que había sabido ser campeón luego de que el cinturón quedara vacante ante la retirada de <Link href='/leyendas/khabib-nurmagomedov'>Khabib Nurmagomedov</Link>, <Link href='/peleadores/charles-oliveira'>Charles Oliveira</Link>, que venía de someter en el primer asalto a <Link href='/peleadores/justin-gaethje'>Justin Gaethje</Link>. Se enfrentarían el 22 de octubre de 2022 en el UFC 280, con un Makhachev que lograría hacerse con el cinturón, al someter en el segundo asalto a su contrincante, ganando además el bono a la Actuación de la Noche. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/34Tk9Z3AOvo?si=d51gK4EdsNMzb1Tn" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>En su primera defensa del título, se lo programaría para enfrentar al histórico campeón de peso pluma de la compañía, <Link href='/peleadores/alexander-volkanovski'>Alexander Volkanovski</Link>, quien venía de una racha de 22 victorias consecutivas, habiendo barrido completamente con su división, estaba en busca de nuevos retos, por lo que subió de categoría para enfrentar a nuestro protagonista. Ambos se enfrentarían en el UFC 284, organizado en Australia, de donde es Volkanovski, para el día 12 de febrero de 2023. Aquella noche, en lo que fue una auténtica guerra, y donde vimos por primera vez en mucho tiempo al luchador Daguestaní sufrir un poco durante el combate, Makhachev sería capaz de hacerse con la victoria por decisión unánime, en la que sería elegida la Pelea de la Noche, y posteriormente La Pelea del Año 2023. </p>
                    <p className={styles.peleador__article__text}>Para su segunda pelea se tenía programada una revancha ante el brasileño <Link href='/peleadores/charles-oliveira'>Charles Oliveira</Link> el 21 de octubre de 2023 en el <b>UFC 294</b>, organizado en Abu Dhabi. Sin embargo, el brasileño se daría de baja de la pelea luego de sufrir un corte en el campanento que le impediría estar en condiciones para competir, por lo que en su lugar entraría nuevamente <b>Alexander Volkanovski</b>. Durante aquel combate, Makhachev se encargaría de que esta vez no hayan dudas respecto al resultado de la pelea, conectando una patada en la cabeza del rival que lo dejaría KO en el primer asalto del combate, ganando por este desempeño el bono a la Actuación de la Noche.</p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/SbGbEw0My4U?si=W2M9ToxPxmuQ0Kbq" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>El 1 de junio de 2024 volvería a defender su título en el <Link href='/covertura-ufc/ufc302'>UFC 302</Link>, siendo el retador un <Link href='/peleadores/dustin-poirier'>Dustin Poirier</Link>, que venía de una victoria por nocaut en el <Link href='/covertura-ufc/ufc299'>UFC 299</Link> ante el francés <b>Benoit Saint-Denis</b>, y que al estar en sus 35 años, veía este combate como su última oportunidad para ser campeón. En una pelea donde el retador dió todo, nuestro protagonista supo demostrar de lo que está hecho, sometiendo en el quinto asalto a Poirier, concretando de esta manera su tercera defensa del cinturón, empatando con quien ahora forma parte de su esquina, <Link href='/leyendas/khabib-nurmagomedov'>Khabib Nurmagomedov</Link>, quien también se retiró con 3 defensas exitosas. Además, esa noche ganaría los bonos a la Actuación de la Noche y a la Pelea de la Noche.</p>
                    </article>
                    <EndArticle />
                <AsideFighter />
            </section>
        </main>
    )
}