import PeleadoresHero from '@/app/peleadores/components/PeleadoresHero'
import edwards from '@/assets/peleadores__images/0-100/10-20/leon-edwards/edwards.png'
import styles from '@/app/peleadores/components/peleador.module.css'
import Link from 'next/link'
import type { Metadata } from 'next'
import dynamic from 'next/dynamic'

const AsideChamps = dynamic(() => import('@/app/components/asides/AsideChamps'))
const EndArticle = dynamic(() => import('@/app/components/EndArticle'))

export const metadata: Metadata = {
    title: 'Leon Edwards',
    description: 'Leon Edwards es un peleador británico de MMA que actualmente compite en la división de peso wélter de la UFC, donde compite desde noviembre de 2014, cuando en el UFC Fight Night: Shogun vs. Saint Preux se enfrentaría al brasileño Cláudio Silva.',
    openGraph: {
        title: 'Leon Edwards',
        description: 'Leon Edwards es un peleador británico de MMA que actualmente compite en la división de peso wélter de la UFC, donde compite desde noviembre de 2014, cuando en el UFC Fight Night: Shogun vs. Saint Preux se enfrentaría al brasileño Cláudio Silva.',
        url: 'https://fullmma.org/peleadores/leon-edwards'
    }
}

export default function LeonEdwards () {
    return(
        <main>
            <PeleadoresHero peleadoresImage={edwards} w={22} l={5} d={0} nombre='Leon Edwards' apodo='ROCKY' categoria='Peso Welter' time='2025-10-29' />
            <section className={styles.peleador__articles__container}>
                <article className={styles.peleador__article}>
                    <h2 className={styles.peleador__article__title}>Edwards UFC</h2>
                    <p className={styles.peleador__article__text}>Leon Edwards es un peleador británico de MMA que actualmente compite en la división de peso wélter de la <Link href='/articulos/ufc'>UFC</Link>, donde compite desde noviembre de 2014, cuando en el <b>UFC Fight Night: Shogun vs. Saint Preux</b> se enfrentaría al brasileño <b>Cláudio Silva</b>. </p>
                    <p className={styles.peleador__article__text}>Leon Edwards es uno de los representantes británicos que tiene la compañía, y es uno de los más importantes que hay actualmente. Marcado por un pasado problemático, supo sobreponerse a las circunstancias para crecer y convertirse en uno de los mejores peleadores de la división de peso wélter de la UFC.</p>
                    <p className={styles.peleador__article__text}>Supo destacar en la compañía el día 20 de agosto de 2022, cuando enfrentando al entonces histórico campeón de la división de 170lbs, <Link href='/peleadores/kamaru-usman'>Kamaru Usman</Link>, fue capaz de dar vuelta lo que estaba siendo una pelea desfavorable para él, conectando una patada a la cabeza de su rival que lo dejaría KO en el último asalto de la pelea, convirtiéndose de esta manera en el nuevo campeón de la división. </p>
                    <h2 className={styles.peleador__article__title}>Leon Edwards Récord</h2>
                    <p className={styles.peleador__article__text}>Leon Edwards posee un récord profesional en MMA de 22-5 (1). Siendo 7 de estas victorias por la vía del nocaut, 3 por la vía de la sumisión, y 12 por decisión. Mientras que de sus 4 derrotas, 3 fueron la vía de la decisión, 1 por descalificación y 1 por sumisión. Además posee una pelea que quedó sin resultado ante <Link href='/peleadores/belal-muhammad'>Belal Muhammad</Link> luego de conectar un piquete de ojo accidental a su rival que le impidió continuar peleando. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/tY7HTlJEyzo?si=akeQEp82kBR7Z1C1" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <h2 className={styles.peleador__article__title}>Leon Edwards Historia</h2>
                    <p className={styles.peleador__article__text}>Leon Edwards nació el día 25 de agosto de 1991 en la capital de Jamaica, Kingston, donde vivió los primeros años de su vida junto a su hermano y sus padres. </p>
                    <p className={styles.peleador__article__text}>A temprana edad se mudó a Birmingham, Inglaterra. En los años de formación que tuvo en su nuevo hogar, lo apodaron “Rocky” a causa de la violencia en las calles de su barrio, Edwards no sería menos que otros muchachos de su edad. En palabras de Leon Edwards: “Por eso mi apodo es Rocky. Lo conseguí peleando en la calle.”</p>
                    <p className={styles.peleador__article__text}>A los 14 años, su padre muere en un club nocturno tras meterse en “actividades cuestionables” como Edwards describe. Esto generó que el muchacho terminara implicado en actividades criminales como tráfico de drogas y peleas callejeras. A los 17 años (2008) fue capaz de salir de eso gracias a su madre, decidió llevarlo a un club de MMA. </p>
                    <p className={styles.peleador__article__text}>De esta manera haría su debut el día 5 de junio de 2011, a los 19 años, enfrentando al polaco <b>Damian Zlotnicki</b>, a quien lograría derrotar por TKO en el primer asalto de la pelea. En noviembre de ese mismo año volvería a pelear contra el polaco <b>Pawel Zwiefka</b>, a quien derrotaría por decisión unánime, dando inicio de esta forma a su carrera profesional. </p>
                    <p className={styles.peleador__article__text}>Leon seguiría en una senda exitosa en su carrera, ganando muchos combates en promotoras inglesas, hasta llegar a acumular un récord de 6-1, que le abriría la oportunidad para pelear por el título de peso wélter de <b>BAMMA</b>, el día 5 de mayo de 2014, enfrentando a <b>Wayne Murrie</b>, a quien lograría derrotar por sumisión en el tercer asalto de la pelea, ganando de esta manera el campeonato de la compañía inglesa. Tiempo después defendería este cinturón en septiembre de ese mismo año, enfrentando al escoces <b>Shaun Taylor</b>, a quien sería capaz de derrotar por KO en el tercer asalto. </p>
                    <h3>Leon Edwards En La UFC</h3>
                    <p className={styles.peleador__article__text}>De esta manera, con un récord acumulado de 8-1, a Edwards se le abriría la oportunidad de competir en la compañía de artes marciales mixtas más grande del mundo, haciendo su debut oficial en la UFC el día 8 de noviembre de 2014 ante el brasileño <b>Cláudio Silva</b>, en el <b>UFC Fight Night: Shogun vs. Saint Preux</b>, donde lamentablemente caería derrotado por decisión dividida, sufriendo la segunda derrota de su carrera. Sin embargo, sería capaz de reponerse rápido de esta derrota, cuando el 11 de abril de 2015 en el <b>UFC Fight Night: Gonzaga vs. Cro Cop 2</b> en Croacia, enfrentando al estadounidense <b>Seth Baczynski</b>, consiguiendo una impresionante victoria por KO a los 8 segundos de la pelea, ganando por este hito el primer bono de su carrera a la Actuación de la Noche. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="478" height="849" src="https://www.youtube.com/embed/e9Nx-05Teow" title="Leon Edwards&#39; 8-Second KO" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Ese mismo 2015 tendría 2 combates más, siendo el siguiente uno ante el polaco <b>Pawel Pawlak</b>, a quien enfrentaría el 18 de junio, consiguiendo una nueva victoria por decisión unánime. Y el último combate del año lo tendría el 19 de diciembre de 2015, enfrentando para ello al nigeriano <Link href='/peleadores/kamaru-usman'>Kamaru Usman</Link>, con quien lamentablemente sufriría una derrota por decisión unánime. </p>
                    <p className={styles.peleador__article__text}>Sin embargo, Leon volvería de esta derrota aún más fuerte, acumulando una impresionante racha de victorias, que se extendería durante casi 9 años, comenzando en 2016, al derrotar primero en mayo al estadounidense <b>Dominic Waters</b> por decisión, y luego en octubre al ruso <b>Albert Trumenov</b> por sumisión en el tercer asalto. </p>
                    <p className={styles.peleador__article__text}>Durante el 2017 tendría otros 2 combates que acabaría ganando, siendo el primero ante el brasileño <b>Vicente Luque</b>, a quien derrotaría por decisión, y siendo el segundo ante el estadounidense <b>Bryan Barberena</b>, a quien de igual forma derrotaría por decisión unánime. </p>
                    <p className={styles.peleador__article__text}>El 17 de junio de 2018 se enfrentaría al polaco <b>Peter Sobotta</b> en una cartelera organizada en Londres, donde sería capaz de derrotar a su rival por TKO en el tercer asalto de la pelea. El 23 de junio de ese mismo año, protagonizaría su primera cartelera enfrentando a <b>Donal &quot;Cowboy&quot; Cerrone</b>, en el <b>UFC Fight Night: Cowboy vs. Edwards</b> organizado en Singapur, donde luego de 5 asaltos sería capaz de llevarse la victoria por decisión unánime. </p>
                    <p className={styles.peleador__article__text}>Durante el 2019 tendría otros 2 combates, siendo el primero ante el luchador de Islandia <b>Gunnar Nelson</b>, a quien enfrentaría el 16 de marzo consiguiendo una victoria por decisión dividida. Mientras que el segundo combate sería encabezando nuevamente una cartelera, esta vez en Texas, enfretando para ello el día 20 de julio al histórico peleador brasileño <b>Rafael dos Anjos</b>, a quien luego de 5 asaltos sería capaz de derrotar por decisión unánime. </p>
                    <p className={styles.peleador__article__text}>A esta altura, Edwards ya llevaba acumuladas 8 victorias consecutivas desde su ya lejana derrota ante Kamaru Usman. Se tomaría el año 2020 sin tomar ninguna pelea y finalmente volvería el 13 de marzo de 2021 para enfrentar a otro peleador que venía de una similar racha de victorias, como lo era <Link href='/peleadores/belal-muhammad'>Belal Muhammad</Link>, encabezando una nueva cartelera. Sin embargo, el enfrentamiento entre los 2 acabaría sin resultado, luego de que de manera accidental, Leon le realizara un piquete en el ojo a su rival en el segundo asalto, que le impidió continuar con el combate. </p>
                    <iframe className={styles.peleador__articel__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/O6iuPu3j1ww?si=DwS67rp2j5NX4nSv" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Sin embargo ese mismo año volvería a subirse al octágono para enfrentar a <Link href='/articulos/nate-diaz-historia'>Nate Diaz</Link> el 12 de junio en el UFC 263, consiguiendo esta vez sí, una victoria por la vía de la decisión. Victoria que además, le abriría las puertas a pelear por el cinturón de la división en una revancha ante el entonces campeón nigeriano, Kamaru Usman.</p>
                    <h2 className={styles.peleador__article__title}>Leon Edwards vs Kamaru Usman</h2>
                    <p className={styles.peleador__article__text}>Usman venía de cinco victorias del cinturón, 16 victorias seguidas y 9 años invicto sin que nadie que le ganase o le quitase el título del mejor en peso welter. Mientras que, por otro lado, Edwards venía de conseguir exitosos resultados en sus últimas peleas, sin perder ninguna, quedando descalificado en una ocasión.</p>
                    <p className={styles.peleador__article__text}>El día tan esperado había llegado (20 de agosto de 2022), donde Leon daría su revancha y Kamaru defendería su título por sexta ocasión. Sin embargo, los resultados no fueron los que uno esperaría para el invicto campeón de aquel entonces. En el quinto round, a tan solo 1 minuto de terminar, Edwards consigue conectar una patada a la cabeza de su adversario, noqueando a Usman de un golpe que le dio la victoria.</p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/HYi47Hx07OM?si=fr4lLgLZwKufpiSQ" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>En palabras del campeón: “Sabía que lo más probable es que tendremos una revancha en el futuro. Ya sea a continuación o más adelante, vamos a tener una revancha. Ha sido un campeón durante mucho tiempo, han estado diciendo que es el mejor libra por libra durante toda la semana, él lo creía. Como dije en el octágono, el cinturón no pertenece a nadie.” </p>
                    <p className={styles.peleador__article__text}>Tiempo más tarde, Edwards defendió su título contra Usman nuevamente. El 18 de marzo de 2023, por decisión mayoritaria (48-46, 48-46, 47-47), Leon Edwards mantuvo su título como el mejor de peso welter.</p>
                    <h3>Leon Edwards vs Colby Covington</h3>
                    <p className={styles.peleador__article__text}>Se programaría la segunda defensa de nuestro protagonista para el día 16 de diciembre de 2023, debiendo enfrentar para ello al excampeón interino de la compañía <Link href='/peleadores/colby-covington'>Colby Covington</Link>, que venía de una victoria ante <Link href='/peleadores/jorge-masvidal'>Jorge Masvidal</Link> el año anterior. </p>
                    <p className={styles.peleador__article__text}>La previa del combate estuvo caldeada, como era de esperar por el estilo acido que tiene el estadounidense de vender las peleas y de generar interés en la gente, metiéndose de lleno en temas personal y en la niñez de Edwards, de la cual hablamos en el inicio de su historia. Esto llevo a que veamos a un Leon Edwards más serio que de costumbre, que sería capaz de canalizar lo que pudo haber sentido en el combate, siendo capaz de derrotar a su rival por decisión unánime, en lo que fue una actuación absolutamente dominante por parte del británico. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/nBREqXtCUVE?si=HDcUZPp27eA_WvaS" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <h3>Leon Edwards pierde el cinturón con Belal</h3>
                    <p className={styles.peleador__article__text}>La tercer defensa del campeón jamaiquino, sería una revancha ante el lucchador de origen palestino <Link href='/peleadores/belal-muhammad'>Belal Muhamamd</Link>, quien al igual que Edwards, llevaba una amplia racha de peleas sin ver la derrota.</p>
                    <p className={styles.peleador__article__text}>Dicho enfrentamiento se programaría para el 27 de julio de 2024 en el <Link href='/covertura-ufc/ufc304'>UFC 304</Link>, organizada en la ciudad de Manchester, donde tanto Leon como Belal protagonizarían la pelea cabeza del evento. Lamentablemente para nuestro protagonista, pese a hacer &quot;de local&quot; en Inglaterra, terminaría por caer derrotado por decisión unánime, viéndose superado por su rival que lo dominó durante la totalidad del combate. </p>
                    <EndArticle />
                </article>
                <AsideChamps />
            </section>
        </main>
    )
}