import PeleadoresHero from '@/app/peleadores/components/PeleadoresHero'
import styles from '@/app/peleadores/components/peleador.module.css'
import Link from 'next/link'
import Image from 'next/image'
import duPlessis from '@/assets/peleadores__images/0-10/dricus-du-plessis/du-plessis.png'
import AsideFighter from '@/app/components/asides/AsideFighter'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Dricus Du Plessis',
    description: 'Dricus Du Plessis es un luchador de MMA sudafricano que actualmente compite en la división de Peso Medio de la UFC, donde pelea desde octubre de 2020. Destacaría en esta al en enero de 2024, convertirse en campeón, al derrotar por decisión dividida a Sean Strickland.',
    openGraph: {
        title: 'Dricus Du Plessis',
        description: 'Dricus Du Plessis es un luchador de MMA sudafricano que actualmente compite en la división de Peso Medio de la UFC, donde pelea desde octubre de 2020. Destacaría en esta al en enero de 2024, convertirse en campeón, al derrotar por decisión dividida a Sean Strickland.',
        url: 'https://fullmma.org/peleadores/du-plessis'
    }
}

export default function DuPlessis () {
    return(
        <main>
            <PeleadoresHero peleadoresImage={duPlessis} w={22} l={2} d={0} nombre='Dricus Du Plessis' apodo='STILLKNOCKS' categoria='Peso Medio' />
            <section className={styles.peleador__articles__container}>
                <article className={styles.peleador__article}>
                    <h2 className={styles.peleador__article__title}>Du Plessis</h2>
                    <p className={styles.peleador__article__text}>Dricus Du Plessis es un luchador de MMA sudafricano que actualmente compite en la división de Peso Medio de la <Link href='/articulos/ufc'>UFC</Link>, donde pelea desde octubre de 2020, cuando haría su debut enfrentando al brasileño <b>Markus Pérez</b>, a quien dejaría KO en el primer asalto de la pelea.</p>
                    <p className={styles.peleador__article__text}>Es quizás de los peleadores menos ortodoxos en pelear en la UFC, con un estilo pelea que suele ser caótico, pero que hasta el momento le ha traído buenos resultados, ganando la mayoría de sus combates por finalización. </p>
                    <p className={styles.peleador__article__text}>Destacaría en esta al en enero de 2024, al convertirse en campeón de la división, luego de derrotar por decisión dividida al entonces campeón <Link href='/peleadores/sean-strickland'>Sean Strickland</Link> el 20 de enero de 2024 en el <Link href='/covertura-ufc/ufc297'>UFC 297</Link>. </p>
                    <h2 className={styles.peleador__article__title}>Du Plessis Récord</h2>
                    <p className={styles.peleador__article__text}>Dricus Du Plessis, luego de participar en un total de 24 peleas, posee un récord de 22-2, siendo 9 de sus 22 victorias por la vía del nocaut, 11 por sumisión y 2 por decisión. Mientras que de sus 2 derrotas, 1 fue por la vía del nocaut y 1 por la vía de la sumisión.</p>
                    <h2 className={styles.peleador__article__title}>Du Plessis Historia</h2>
                    <p className={styles.peleador__article__text}>Dricus Du Plessis nació el 14 de enero de 1994 en la ciudad de Pretoria, ubicada en Sudáfrica. Tan sólo a la edad de 5 años comenzó a entrenar judo, a los 12 comenzaría a entrenar lucha libre, y posteriormente kickboxing con 14 años. Una vez en sus años escolares empezaría a jugar Rugby a la par que entreneba artes marciales, volviendose partidario del equipo nacional de rugby de Sudáfrica, los Spingboks.</p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/jcRN2K5cp7o?si=lI62oYSQbM-mhRhv" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Du plessis con 17 años se convertiría en el primer medallista de Sudáfrica en el Campeonato Mundial WAKO al ganar el oro en kickboxing estilo K-1 en el año 2012. Pero al ver que no se podía ganar tanto dinero en el Kickboxing decidiría migrar a las artes marciales mixtas en busca de mejores oportunidades económicas.</p>
                    <p className={styles.peleador__article__text}>Comenzaría a estudiar en la Universidad de Pretoria la carrera de economía agrícola, aunque abandonaría la carrera en su último año para dedicarse de lleno a las MMA. Carrera en la que tendría 3 combates amateur que ganaría, antes de su oportunidad como profesional. Haría su debut profesional el 25 de julio de 2013 contra el también sudádricano <b>Tshikangu Makuebo</b>, a quien derrotaría por nocaut en el primer asalto por <b>EFC Africa 21</b>.</p>
                    <p className={styles.peleador__article__text}> Ganaría todos sus primeros 4 combates por finalización, siendo 2 de estas victorias por TKO y 2 por sumisión, hasta que llegaría su primera derrota contra <b>Garreth McLellan</b>, quien en una pelea por el título de peso mediano de EFC, luego de 3 asaltos, terminaría por someterlo con una guillotine choke.</p>
                    <p className={styles.peleador__article__text}>Hasta aquel momento, Du Plessis venía peleando en peso mediano, pero luego de una pelea más en la que derrotaría a <b>Darren Daniel</b> por sumisión, decidió bajar de división a peso Wélter. División en la que debutaría el 6 de junio de 2015, para enfrentar a <b>Dino Bagattin</b>, a quien derrotaría por sumisión en el segundo asalto. Luego de una victoria más por sumisión ante <b>Bruno Mukulu</b>, terminaría ganando el título vacante de peso welter, al vencer a <b>Martin van Staden</b> por sumisión con una guillotine choke en el tercer asalto de la pelea.</p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/tDaY9riylrU?si=EGstPKgG2qehFzJq" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Una vez conseguido este hito, volvería a pelear en peso medio, en busca de escalar posiciones para volver a pelear por el cinturón. Para esto, se enfrentaría primero a al polaco <b>Rafal Haratyk</b> en diciembre de 2016, a quien lograría vencer por sumisión en el segundo asalto de la pelea. En su siguiente combate con fecha a mayo del 2017, se enfrentaría al brasileño <b>José Maurício da Rocha Jr.</b>, a quien vencería por TKO en el primer asalto del combate.</p>
                    <p className={styles.peleador__article__text}>Con estas 2 victorias, se ganaría la oportunidad de disputar el cinturón nuevamente el día 19 de agosto de ese mismo año, cuando enfrentaría al peleador inglés <b>Yanninck Bahati</b>, a quien conseguiría someter en el primer asalto de la pelea. Convirtiéndose de esta manera, en doble campeón de la compañía, al haber sostenido tanto el cinturón de peso wélter, como el de peso medio. </p>
                    <p className={styles.peleador__article__text}>Luego de campeonar en aquella compañía africana, Dricus firmaría un contrato para tener 3 peleas en la promotora polaca <b>KSW</b>, que es una de las más importantes del continente europeo. Haría su debut en esta promotora ya peleando por el título de peso wélter contra el campeón croata <b>Roberto Soldic</b>, el día 14 de abril de 2018, cuando conseguiría derrotar a este por TKO en el segundo asalto de la pelea, ganando de esta manera no sólo el cinturón de campeón, sino que también el primer bono de su carrera a la Actuación de la Noche. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/SLFbHWy_IdY?si=0jpP90XnQGQr-JbN" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>El 6 de octubre de ese mismo año, se volvería a enfrentar en una revancha al croata, poniendo en juego su título. Aquel evento organizado en Londres, acabaría con lo que sería la segunda derrota profesional de nuestro protagonista, que caería por KO en el tercer asalto de este combate. Perdiendo su cinturón, pero ganando de igual manera el segundo bono de su carrera a La Pelea de la Noche.</p>
                    <p className={styles.peleador__article__text}>Su última pelea en la promotora polaca sería en septiembre de 2019, regresando a la división de Peso Medio para enfrentar al brasileño <b>Joilton Santos</b>, a quien conseguiría derrotar por TKO en el KSW 50. Por último, volvería a pelear por última en la compañía <b>EFC Africa</b>, para defender su cinturón ante <b>Brendan Lesar</b>, a quien conseguiría derrotar con relativa facilidad al someterlo en el primer asalto de la pelea con una guillotina. </p>
                    <p className={styles.peleador__article__text}>Ya con un récord profesional de 14-2, habiendo sido campeón en 2 compañías distintos en 2 categorías de peso diferentes, Du Plessis se ganaría la oportunidad de pelear en la compañía de artes marciales mixtas más grande del mundo, la UFC. Donde haría su debut el 11 de octubre de 2020, para enfrentar al brasileño <b>Markus Pérez</b>, a quien en el primer asalto conseguiría dejar KO. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/IXmA-mq5WN4?si=q-tNXfR1NQKutmNH" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>En su segundo combate en la compañía, con fecha para el 10 de julio de 2021, se enfrentaría al estadounidense <b>Trevin Giles</b> en el UFC 264, a quien lograría derrotar por KO en el segundo asalto de la pelea, ganando el bono a la Actuación de la Noche. </p>
                    <p className={styles.peleador__article__text}>En el 2022 tendría 2 combates más, siendo el primero de estos también su primer pelea ante un luchador ranqueado de la UFC, cuando enfrentaría al americano <b>Brad Tavares</b> el 2 de julio en el UFC 276, consiguiendo una victoria por decisión unánime que lo pondría en los rankings de la división de peso medio. El 10 de diciembre en el UFC 282, se enfrentaría al inglés <b>Darren Till</b>, a quien en el tercer asalto lograría someter, ganando por este combate el bono a La Pelea de la Noche.</p>
                    <p className={styles.peleador__article__text}>Durante el año 2023 tendría otros 2 combates. Siendo el primero de estos el 4 de marzo en el UFC 285 ante el estadounidense <b>Derek Brunson</b>, a quien conseguiría derrotar por TKO terminando el segundo asalto, luego de una parada de la esquina rival. </p>
                    <p className={styles.peleador__article__text}>El 8 de julio de 2023 en el UFC 290, se enfrentaría al histórico excampeón de la división, el australiano <Link href='/peleadores/robert-whittaker'>Robert Whittaker</Link>, en lo que sería una eliminatoria titular. Aquella noche, el luchadro sudafricano aprovecharía su oportunidad consiguiendo noquear al australiano en el segundo asalto, ganando el derecho a pelear por el cinturón, y ganando el bono a la Actuación de la Noche, por lo hecho en aquel evento. </p>
                    <p className={styles.peleador__article__text}>De esta forma, se programaría su pelea por el título ante el campeón estadounidense <Link href='/peleadores/sean-strickland'>Sean Strickland</Link> en el <Link href='/covertura-ufc/ufc297'>UFC 297</Link> organizado el 20 de enero de 2024. Aquella noche, en lo que fue una pelea muy cerrada y que se definiría por decisión dividida, nuestro protagonista conseguiría convertirse en el nuevo campeón de las 185lbs, ganando además el bono a La Pelea de la Noche. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/RCw6lEJVsss?si=H1UKut80E3VDqLSz" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Ya como campeón, se organizaría su primer defensa del cinturón para el 18 de agosto de ese mismo año, enfrentando para ello al histórico campeón <Link href='/peleadores/israel-adesanya'>Israel Adesanya</Link>, con quien encabezaría el <Link href='/covertura-ufc/ufc305'>UFC 305</Link> organizado en Australia. Aquella noche, Du Plessi sería capaz de defender exitosamente su cinturón, cuando en el cuarto asalto de la pelea sometería al nigeriano, concretando de forma exitosa su primera defensa.</p>
                </article>
                <AsideFighter />
            </section>
        </main>
    )
}