import styles from '@/app/leyendas/components/leyenda.module.css'
import Link from 'next/link'
import AsideChamps from '@/app/components/asides/AsideChamps'
import EmelianenkoHero from './EmelianenkoHero'
import type { Metadata } from 'next'
import EndArticle from '@/app/components/EndArticle'

export const metadata: Metadata = {
    title: 'Fedor Emelianenko',
    description: "Fiódor Emelianenko es uno de los mejores peleadores de MMA de la historia, considerado por figuras como GSP, José Aldo o Mike Tyson como el mejor peleador de artes marciales mixtas de la historia. Siendo campeón de PRIDE, de RINGS y de World Alliance of Mixed Martial Arts, supo meterse en los libros de historia de las MMA. Además tuvo una destacada carrera política en Rusia, donde llegó a ser elegido diputado cuando todavía era un peleador activo en 2010 y donde formaría parte del poder ejecutivo al ser nombrado miembro del personal del Consejo de Aptitud Física y Deportes de Rusia en 2012.",
    openGraph: {
        title: 'Fedor Emelianenko',
        description: "Fiódor Emelianenko es uno de los mejores peleadores de MMA de la historia, considerado por figuras como GSP, José Aldo o Mike Tyson como el mejor peleador de artes marciales mixtas de la historia. Siendo campeón de PRIDE, de RINGS y de World Alliance of Mixed Martial Arts, supo meterse en los libros de historia de las MMA. Además tuvo una destacada carrera política en Rusia, donde llegó a ser elegido diputado cuando todavía era un peleador activo en 2010 y donde formaría parte del poder ejecutivo al ser nombrado miembro del personal del Consejo de Aptitud Física y Deportes de Rusia en 2012.",
        url: 'https://fullmma.org/leyendas/fedor-emelianenko'
    }
}


export default function FedorEmelianenko () {
    return(
        <main>
            <EmelianenkoHero />
            <section className={styles.leyenda__articles__container}>
                <article className={styles.leyenda__article}>
                    <h2 className={styles.leyenda__article__title}>Fiódor Emelianenko</h2>
                    <p className={styles.leyenda__article__text}>Fiódor Emelianenko es uno de los mejores peleadores de MMA de la historia, considerado por figuras como <Link href='/leyendas/george-st-pierre'>GSP</Link>, <Link href='/leyendas/jose-aldo'>José Aldo</Link> o <b>Mike Tyson</b> como el mejor peleador de artes marciales mixtas de la historia. Siendo campeón de <b>PRIDE</b>, de <b>RINGS</b> y de <b>World Alliance of Mixed Martial Arts</b>, supo meterse en los libros de historia de las MMA. Además tuvo una destacada carrera política en Rusia, donde llegó a ser elegido diputado cuando todavía era un peleador activo en 2010 y donde formaría parte del poder ejecutivo al ser nombrado miembro del personal del Consejo de Aptitud Física y Deportes de Rusia en 2012.</p>
                    <h2 className={styles.leyenda__article__title}>Fedor Emelianenko Récord</h2>
                    <p className={styles.leyenda__article__text}>Fedor Emelianenko se retiro con un récord de 40-7 (1). Siendo 16 de sus 40 victorias por la vía del noucat, 15 por sumisión y 9 por decisión. Mientras que de sus 7 derrotas, 6 fueron por nocaut y sólo 1 por sumisión. Además tiene una pelea que terminó sin resultado contra el brasileño <b>Antônio Rodrigo Nogueira</b>, producto de un cabezazo que le ocasionó un corte que el impidió continuar el combate.</p>
                    <h2 className={styles.leyenda__article__title}>Fedor Emelianenko Biografía</h2>
                    <p className={styles.leyenda__article__text}>Fiódor Vladímirovich Yemeliánenko nació el 28 de septiembre de 1976 en la antigua Unión Soviética, en el territorio hoy ocupado por Ucrania, sin embargo, cuando esta fue disuelta, Fiódor se encontraba viviendo en Rusia y adoptó esa ciudadanía. A los 10 años comenzó a entrenar Sambo y Judo, llevando consigo a su hermano menor Aleksandr, quien gracias a su influencia también se terminaría convirtiendo en un peleador de MMA, llegando a estar ranqueado entre los 10 mejores pesos pesados del mundo. </p>
                    <p className={styles.leyenda__article__text}>Entre los años 1995 y 1997, Fedor sirvió en el ejército ruso, participando primero de la brigada contra incendios y posteriormente en una división de tanques. Allí continuaría entrenando, pero producto de las limitaciones de tener que participar del servicio militar, no podría seguir entrenando al mismo nivel ni la misma cantidad de tiempo.</p>
                    <p className={styles.leyenda__article__text}>Emeliananeko haría su debut profesional como luchador el 21 de mayo de 2024 contra el bulgaro <b>Martin Lazarov</b> en la promotora <b>RINGS</b>, a quien sometería con una guillotina en el primer asalto. Ese año tendría un total de 5 combates en la misma promotora, ganando los primeros 4 y perdiendo el último contra el japonés <b>Tsuyoshi Koshaka</b>, contra quien recibió un corte que no le permitió continuar peleando, ante esto, pese a que se pidió que la pelea quede sin resultado el arbitro decidió darle la victoria al japonés, siendo esta la primera derrota en la carrera del ruso, por parada médica.</p>
                    <p className={styles.leyenda__article__text}>Luego de aquella polémica derrota, Fedor acumularía una racha de 5 victorias seguidas a lo largo del año 2001, siendo 3 de esas victorias por sumisión y las otras 2 por decisión, abriéndole paso a nuestro protagonista para poder enfrentarse al australiano <b>Chris Haseman</b> por el título de peso pesado. Enfrentamiento que tendría lugar el 15 de febrero de 2002 y que terminaría con una victoria para Emelianenko por TKO a los pocos minutos de empezado el primer asalto. </p>
                    <iframe className={styles.leyenda_article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/m5UnGuIYrZc?si=P7ZhYZsn--acL-I9" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.leyenda__article__text}>Luego de aquel combate, firmaría con la que entonces era la promotora de artes marciales mixtas más grande del mundo, <b>PRIDE</b>, donde debutaría derrotando por decisión unánime al neerlandés <b>Semmy Schilt</b> el 23 de junio de 2002. Luego de una victoria más por TKO contra el estadounidense <b>Heath Herring</b>, Fedor se enfrentó al brasileño <b>Antônio Rodrigo Nogueira</b> el 16 de marzo de 2003, por el campeonato de peso pesado de PRIDE, campeonato que terminaría ganándo por decisión unánime. </p>
                    <p className={styles.leyenda__article__text}>Contra este peleador se enfrentaría en 3 ocasiones, dado que luego de aquella victoria, tendría 7 combates más (todas victorias), hasta volver a enfrentarse a Nogueira por la unificación del cinturón de campeón el 15 de agosto de 2004. Sin embargo aquella pelea terminaría quedando sin resultado, producto de un cabezazo accidental que provocó un corte en Emelianenko que no le pemitió seguir peleando. Por lo que la pelea se reporgramó para el 31 de diciembre de 2004, y terminaría en una victoria por decisión unánime para nuestro protagonista.</p>
                    <p className={styles.leyenda__article__text}>Una de las peles más destacadas de su carrera, que se daría luego de que fuera capaz de unificar el título de PRIDE, sería contra el croata <b>Mirko Filipovic</b>, quien venía de una racha de 7 victorias consecutivas, entre ellas una por KO en el primer asalto a su hermano <b>Aleksander Emelianenko</b>. Por ser una pelea entre quienes en aquel momento se consideraban los 2 mejores pesos pesados del mundo, es que la pelea adquiría mucha relevancia. Luego de una tremenda pelea, Fedor se terminaría llevando la pelea por decisión unánime, completando de esta manera su primera defensa del título.</p>
                    <p className={styles.leyenda__article__text}>Emilianenko continuaría teniendo peleas en PRIDE, entre las que destacarían la segunda que tuvo con el excampeón de UFC <b>Mark Coleman</b>, a quien ya le había ganado en el pasado con una sumisión en el primer asalto. En su revancha que tendría lugar un par de años después, Emelenianenko volvería a someter a su rival con un kimura, esta vez en el segundo asalto. Su siguiente combate después de aquel, sería contra el neozelandés Mark Hunt, a quien vencería con una sumisión producto de un kimura a los 8 minutos del combate, esta pelea sería particularmente importante porque sería la última que tendría nuestro protagonista en PRIDE, dado que esta comapañía sería comprada por UFC.</p>
                    <iframe className={styles.leyenda_article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/AwToIVs9O9o?si=vWooRfWsuoO_yi8c" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.leyenda__article__text}>Dana White intentaría contratar a Fedor Emelinaneko para UFC para convencerlo de que peleara contra <Link href='/leyendas/randy-couture'>Randy Couture</Link>, sin embargo esto nunca lograría concretarse. Años después, el magnate de las MMA volvería a intentar traer a su compañía a nuestro protagonista para pelear con <Link href='/leyendas/brock-lesnar'>Brock Lesnar</Link>, pero nunca llegarían a un acuerdo. Una lástima, puesto que nunca pudimos ver a Emelianenko enfrentarse a leyendas de los pesos pesados de las MMA como las mencionadas anteriormente. </p>
                    <p className={styles.leyenda__article__text}>Sin embargo, Fedor seguiría compitiendo en diferentes compañías, manteniendo su extensa racha de victorias, hasta que en 2009 firmaría con <b>Strickeforce</b>, donde debutaría el 7 de noviembre, enfrentando al estadounidense <b>Brett Rogers</b>, a quien vencería por KO en el segundo asalto. En esta compañía enfrentaría al brasileño <b>Fabrício Werdum</b>, contra quien caería derrotado por sumisión en el primer asalto, con poco más de un minuto de empezado el combate. Esta sería la primera derrota &quot;real&quot; de su carrera, para un Emelianenko que hasta entonces había acumulado un récord de 31-1 (1). </p>
                    <p className={styles.leyenda__article__text}>Esto no sería todo, ya que para colmo perdería sus 2 siguientes combates, contra el brasileño <b>Antonio Silva</b>, con quien caería derrotado por TKO en el segundo asalto, y luego perdería por TKO en el primer asalto contra el estadounidense <b>Dan Henderson</b>, finalizando en este combate su contrato con Strickeforce. </p>
                    <p className={styles.leyenda__article__text}>Pero una carrera como la de Fedor no podía terminar de esta manera, así que procedió a ganar sus 3 siguientes combates, por decisión el primero, y por nocaut los últimos 2, siendo la pelea contra el brasileño <b>Pedro Rizzo</b>, la que lo llevaría a anunciar su retiro, el 21 de junio de 2012, dejando detrás un récord de 34-4. </p>
                    <iframe className={styles.article__video} width="560" height="315" src="https://www.youtube.com/embed/pl3yk4dP8g8?si=78g3Jm2bEZiiJBDC" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.leyenda__article__text}>Durante esta época fue cuando le dió más relevancia a su carrera política, en la que había sido nombrado miembro del personal del Consejo de Aptitud Física y Deportes de Rusia.</p>
                    <p className={styles.leyenda__article__text}>Aunque si de haber terminado su carrera allí mismo, ya sería considerado una absoluta leyenda, Fedor volvería del retiro 3 años después, a enfrentar al oriundo de la India <b>Singh Jaideep</b>, a quien derrotaría por TKO en el primer asalto. </p>
                    <p className={styles.leyenda__article__text}>Luego de un par de peleas más, Fedor firmaría con <b>Bellator</b>, en donde debutaría el 28 de abril de 2018 para enfrentar al estadunidense <b>Frank Mir</b>, a quien vencería por TKO en el primer asalto. Su siguiente combate sería ese mismo año contra el ex peleador de UFC <b>Chael Sonnen</b>, a quien derrotaría por TKO en el primer asalto, y en una victoria que le permitiría competir por el título en su siguiente combate.</p>
                    <iframe className={styles.leyenda_article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/ioEUsK1EYbI?si=NgTkyN1FNzRCy5Q1" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.leyenda__article__text}>Lamentablemente, Fedor no sería capaz de derrotar a <b>Ryan Bader</b>, y caería por KO en menos de un minuto, perdiend la oportunidad de coronarse campeón de otra compañía más.</p>
                    <p className={styles.leyenda__article__text}>Pero Fedor volvería inmediatamente a la victoria, al enfrentarse al estadounidense <b>Quinton Jackson</b>, a quien sería capaz de dejar KO en el primer asalto. Y volvería a ganar cuando enfrentó a <b>Timothy Johnson</b>, a quien también dejaría KO en el primer asalto en un evento celebrado en Moscú el 23 de octubre de 2023. Obteniendo esta última victoria además, con la edad de 45 años, siendo una absoluta bestia a pesar de edad. </p>
                    <p className={styles.leyenda__article__text}>Aparentamente por un error en la traducción de sus palabras, mucha gente creyó que luego de aquel combate Emelianenko se había retirado, pero lejos de ser así, volvería a pelear una vez más en una revancha contra <b>Ryan Bader</b>, por el título mundial de peso pesado de Bellator. Lamentablemente volvería a perder por TKO en el primer asalto, y esta vez sí de forma definitiva, se retiraría de las artes marciales mixtas, rodeado de otras leyendas que estuvieron presentes para despedir su sobresaliente carrera en el deporte. </p>
                    <iframe className={styles.leyenda_article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/JA3eAY9GtUA?si=fGrvcI5y-LBYqZ88" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <EndArticle />
                </article>
                <AsideChamps />
            </section>
        </main>
    )
}