import styles from '@/app/leyendas/components/leyenda.module.css'
import Link from 'next/link'
import Image from 'next/image'
import AsideChamps from '@/app/components/asides/AsideChamps'
import GspHero from './GspHero'


export default function GSP () {
    return(
        <main>
            <GspHero />
            <section className={styles.leyenda__articles__container}>
                <article className={styles.leyenda__article}>
                <h2 className={styles.leyenda__article__title}>George St-Pierre UFC</h2>
                    <p className={styles.leyenda__article__text}>George St-Pierre es un expeleador de MMA canadiense que destacó en su carrera por la actuación sobresaliente que tuvo cuando compitió en la <Link href='/promotoras/ufc'>UFC</Link>, en donde es considerado uno de los mejores peleadores de la historia, y seguramente sea el mejor Peso Wélter que tuvo la UFC. Supo ser campeón de la divisón de Peso Wélter en su momento, y campeón de Peso Medio de la UFC posteriormente, siendo uno de los pocos doble campeón que hay. Tanto en 2008, como en 2009 y 2010 fue nombrado el Atleta canadiense del Año por Rogers Sportsnet. En 2020 fue inducido al Salón de la Fama de UFC.</p>
                    <h2 className={styles.leyenda__article__title}>George St-Pierre Récord</h2>
                    <p className={styles.leyenda__article__text}>George St-Pierre cuenta con un récord de 26-2. Siendo 8 de sus 26 victorias por nocaut, 6 por sumisión, y 14 por decisión. Mientras que de sus 2 derrotas 1 fue por sumisión contra el histórico <b>Matt Hughes</b> y 1 por nocaut contra el estadounidense <b>Matt Serra</b>.</p>
                    <h2 className={styles.leyenda__article__title}>George St-Pierre Historia</h2>
                    <p className={styles.leyenda__article__text}>George St-Pierre, también conocido como <b>GSP</b>, nació el 19 de mayo de 1981 en la ciudad canadiense de Saint-Isidore, ubicada en la provincia de Ontario. Es hijo de Roland y Pauline St-Pierre.</p>
                    <p className={styles.leyenda__article__text}>George tuvo una infancia complicada, dado que en la escuela a la que asistía era una victima de bullyng, siendo el blanco de otros niños que le robaban su ropa y dinero. Producto de esta situación, es que su padre Roland, lo alentó a aprender Karate, siendo este su primer maestro, antes de que comenzara a entrenarse en el estilo <b>Karate Kyokushin</b> de la mano de un maestro de su ciudad. Este entrenamiento en el arte marcial japonés lo ayudó a ganar confianza y a poder afrontar su vida escolar de mejor manera, mostrando ya desde joven condiciones para el deporte, logrando convertirse en cinturón negro 2° Dan con tan solo 12 años. Continuó entrenando hasta los 16 años, cuando lamentablemente fallecería su maestro, fue por esta razón que comenzó a entrenarse en otras artes marciales como Lucha, Muay Thai, Boxeo y Jiu-Jitsu Brasileño antes de adentrarse de lleno en las MMA.</p>
                    <p className={styles.leyenda__article__text}>En esta época, se interesó en las Artes Marciales Mixtas, cuando llegó a él un video del primer evento de UFC, donde vió como el luchador <b>Royce Gracie</b> era capaz de derrotar y de someter a peleadores más grandes que él, lo que cambió su perspectiva sobre el mundo del combate, considerandolo uno de sus ídolos, respecto a esto dijo: &quot;Ser el GOAT tiene un significado diferente para mí. Para mí es Royce Gracie, porque cambió el deporte. El cambió la creencia respecto a lo que es una pelea real. Así que creo que es Royce Gracie&quot;. </p>
                    <p className={styles.leyenda__article__text}>En aquel momento las MMA estaban prohibidas en Canadá, es por esto que averiguando, GSP se enteró de que en el único lugar del país donde se podían organizar estas peleas era en las Reservas Indias, donde asistió a presenciar algunas peleas. Allí conocería a quien sería entrenador durante gran parte de su carrera.</p>
                    <p className={styles.leyenda__article__text}>A pesar de la prohibición, la promotora <b>UCC</b> se aprovechó de algunos vacíos legales para organizar sus combates, convirtiendose en la primera promotora del país. Es aquí donde George St-Pierre hizó su debut como profesional en <b>UCC 7: Bad Boyz</b> contra el salvadoreño <b>Iván Menjivar</b> a quien derrotó por nocaut en el primer asalto. Fue en esta promotora también donde logró convertirse en campeón de Peso Wélter en su segundo combate al derrotar con una sumisión en el primer asalto al canadiense <b>Justin Bruckmann</b>.</p>
                    <p className={styles.leyenda__article__text}>GSP tendría 5 combates antes de debutar en la UFC, ganando 3 por nocaut y 2 por sumisión. Aquel debut lo haría contra el armenio <b>Karo Perisyan</b>, quien era un peleador con muchísima más experiencia que George, a quien luego de dominar a lo largo de los 3 asaltos, vencería por decisión unánime.</p>
                    <p className={styles.leyenda__article__text}>GSP tendría una pelea más antes de ir por el título, contra el estadounidense <b>Jay Hieron</b> a quien vencería por nocaut en el primer asalto. Finalmente, el 24 de octubre de 2004, GSP se enfrentaría al campeón <b>Matt Hughes</b> en UFC 50 por el Campeonato de Peso Wélter de UFC, en aquel combate el canadiense terminaría por perder en el primer asalto luego de ser sometido en el primer asalto. Esta se convertiría en la primer derrota como profesional de GSP.</p>
                    <p className={styles.leyenda__article__text}>Pese a esta derrota, fue capaz de reponerse rápido, dado que 3 meses después pelearía contra <b>Dave Straesser</b> a quien vencería con una sumisión en menos de 2 minutos de pelea. George acumularía una racha de 4 victorias consecutivas, siendo la última contra <b>B.J Penn</b> con quien peleó en una eliminatoria por el título, esta pelea sería bastante cerrada, aunque se la terminaría llevando GSP por decisión dividida, tiempo después, reconocería que B.J Penn es el rival más conplicado al que se ha enfrentado. Luego de esta racha, George obtendría la revancha contra Matt Serra, logrando esta vez revertir la historia, ganando por nocaut en el segundo asalto, convirtiéndose así en campeón de peso wélter de UFC, ganando además el premio al KO de la noche.</p>
                    <p className={styles.leyenda__article__text}>Luego de proclamarse campeón, su primera defensa sería contra <b>Matt Serra</b>, quien venía de ganar el TUF, siendo un peleador bastante más veterano que GSP, se esperaba que este fuera capaz de defender su título de forma relativamente sencilla. Sin embargo sorprendió a todo el mundo que Matt fuera capaz de noquear en el primer asalto y arrebatarle el cinturón.</p>
                    <p className={styles.leyenda__article__text}>George St-Pierre luego de esto tuvo que pelear contra <b>Josh Koscheck</b> a quien venció por decisión unánime. Luego pelearía una tercera vez contra <b>Matt Hughes</b> por el campeonato interino de la división, en esta ocasión se cerraría la trilogía con una victoria para GSP por sumisión en el segundo asalto. Luego de estos 2 combates es que GSP tendría la oportunidad de pelear otra vez contra Matt Serra por el campeonato, donde esta vez lograría ganar por nocaut en el segundo asalto, unificando de esta manera el cinturón y volviéndose a consagrar campeón de la división. </p>
                    <p className={styles.leyenda__article__text}>Desde entonces, defendió el título un total de 9 veces de forma éxitosa, lo que es un récord en su división, y es el segundo número mayor de defensas en la historia de la UFC. Siendo la última contra el estadounidense <b>Johny Hendricks</b> en diciembre de 2013 por UFC 167, a quien luego de 5 asaltos vencería por decisión dividida, luego del combate anunciaría que se tomaría un descanso, dejando la puerta abierta a volver a pelear en el futuro, de esta forma dejó el título vacante y se dedicó a seguir sus otras pasiones, como lo era el cine, donde participó como actor en películas como <b>	Captain America: The Winter Soldier</b>, y <b>Kickboxer: Vengeance</b>, que sería protagonizada por una persona muy admirada por GSP como lo es Jean-Claude Van Damme, además de que aquí participó quien también fue peleadora de UFC, <b>Gina Carano</b>.</p>
                    <h2 className={styles.leyenda__article__title}>George St-Pierre Última Pelea</h2>
                    <p className={styles.leyenda__article__text}>Finalmente luego de 4 años de inactividad, que encima se habían agravado por una lesión en la rodilla que lo había obligado a permanecer 1 año sin entrenar, George St-Pierre volvería a pelear, esta vez en UFC 217 contra el histórico inglés <b>Michael Bisping</b>, por el Campeonato de Peso Medio de UFC.</p>
                    <p className={styles.leyenda__article__text}>Michael Bisping venía de consagrarse consagrarse luego de que una victoria contra <Link href='/leyendas/anderson-silva'>Anderson Silva</Link> le hiciera ganarse la pelea por el título de Peso medio contra <b>Luke Rockhold</b>, que ganaría por KO en el primer asalto y que luego defendería de manera exitosa contra <b>Dan Henderson</b> por decisión unánime luego de los 5 asaltos.</p>
                    <p className={styles.leyenda__article__text}>Este combate se lo terminaría llevando el canadiense por sumisión en el tercer asalto, convirtiendose de esta manera en doble campeón de la UFC en su glorioso regreso. Lamentablemente por una enfermedad, producto de la dieta que hizo para subir de peso, nunca pudo defender el título, dejándolo de esta manera vacante.</p>
                    <iframe className={styles.leyenda__article__video} width="560" height="315" src="https://www.youtube.com/embed/drN7gYW84w8?si=KxDaeZifPDVKlzHG" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen></iframe>
                </article>
                <AsideChamps />
            </section>
        </main>
    )
}