import PeleadoresHero from '@/app/peleadores/components/PeleadoresHero'
import gaethje from '@/assets/peleadores__images/0-100/10-20/justin-gaethje/gaethje.png'
import styles from '@/app/peleadores/components/peleador.module.css'
import Link from 'next/link'
import dynamic from 'next/dynamic'
import type { Metadata } from 'next'

const AsideChamps = dynamic(() => import('@/app/components/asides/AsideChamps'))
const EndArticle = dynamic(() => import('@/app/components/EndArticle'))

export const metadata: Metadata = {
    title: 'Justin Gaethje',
    description: 'Justin Gaethje actualmente se encuentra ranqueado número #2 en la división de Peso Ligero de UFC donde pelea desde 2017, habiendo hecho su debut en The Ultimate Fighter contra Michael Johnson el 7 de julio en Las Vegas, ganando por TKO en el segundo asalto, y habiendo hecho su debut en un evento de UFC el 2 de diciembre en UFC 218 contra Eddie Alvarez, quien lo venció por TKO en el tercer asalto.',
    openGraph: {
        title: 'Justin Gaethje',
        description: 'Justin Gaethje actualmente se encuentra ranqueado número #2 en la división de Peso Ligero de UFC donde pelea desde 2017, habiendo hecho su debut en The Ultimate Fighter contra Michael Johnson el 7 de julio en Las Vegas, ganando por TKO en el segundo asalto, y habiendo hecho su debut en un evento de UFC el 2 de diciembre en UFC 218 contra Eddie Alvarez, quien lo venció por TKO en el tercer asalto.',
        url: 'https://fullmma.org/peleadores/justin-gaethje'
    }
}

export default function Gaethje () {
    return(
        <main>
            <PeleadoresHero peleadoresImage={gaethje} w={26} l={5} d={0} nombre='Justin Gaethje' apodo='THE HIGHLIGHT' categoria='Peso Ligero' time='2025-10-29' />
            <section className={styles.peleador__articles__container}>
                <article className={styles.peleador__article}>
                    <h2 className={styles.peleador__article__title}>Gaethje UFC</h2>
                    <p className={styles.peleador__article__text}>Justin Gaethje es un peleador estadounidense de MMA que compite en la división de Peso Ligero de <Link href='/articulos/ufc'>UFC</Link>, donde pelea desde 2017, habiendo hecho su debut en <b>The Ultimate Fighter: Redemption Finale</b> contra Michael Johnson el 7 de julio en Las Vegas, ganando por TKO en el segundo asalto.</p>
                    <p className={styles.peleador__article__text}>Es sin dudas uno de los peleadores favoritos de los fans, un auténtico BMF, quien, pese a no tener una personalidad estridente como otros de sus colegas, con lo que demuestra dentro del octágono le bastó para ganarse el respeto y el cariño de la gente, dado que gane o pierda, siempre da espectáculo al momento de pelear, no por nada es uno de los luchadores con la mayor cantidad de bonos a La Pelea de la Noche ganados en la compañía, con 7. </p>
                    <p className={styles.peleador__article__text}>Destacaría en la compañía al haber sostenido el cinturón interino de la división de peso ligero de la UFC, luego de vencer por TKO al &quot;Cucuy&quot; <Link href='/peleadores/tony-ferguson'>Tony Ferguson</Link> el 9 de mayo de 2020 en el evento estelar del UFC 249, en lo que además le haría ganador de los bonos a La Pelea de la Noche y a la Actuación de la Noche. Además de haber disputado el cinturón indiscutido de la división en 2 ocasiones, aunque no fuera capaz de ganarlo en ninguna de estas oportunidades. </p>
                    <h2 className={styles.peleador__article__title}>Justin Gaethje Récord</h2>
                    <p className={styles.peleador__article__text}>Justin Gaethje tiene un record de 26-5. Siendo 20 de estas 26 victorias por nocaut, 5 por decisión y 1 por sumisión. Mientras que 3 de sus derrotas fueron por nocaut y 2 por sumisión.</p>
                    <h2 className={styles.peleador__article__title}>Justin Gaethje Biografía</h2>
                    <p className={styles.peleador__article__text}>Justin Ray Gaethje nació el 14 de noviembre de 1988 en Estados Unidos, en la ciudad de Safford, Arizona. Su madre es de ascendencia mexicana y su padre de ascendencia alemana (de donde sacó su apellido Gaethje que es de origen aleman). Su abuelo boxeaba mientras servía en el ejército de los Estados Unidos. Justin por su parte, se egresó con una licenciatura en Servicios Humanos en la Universidad del Norte de Colorado.</p>
                    <p className={styles.peleador__article__text}>Su inicio y su ingreos al mundo de las artes marciales mixtas se dió casi de forma accidental, puesto que pese a que Gaethje entrenó Wrestling desde pequeño, afirma nunca haber soñado con dedicarse a pelear, y que no había sido algo que le llamara la atención particularmente, tampoco se había envuelto en su vida en una pelea callejera, simplemente aceptó pelear de manera amateur en la universidad, consiguiendo 7 victorias consecutivas, llevándole a ser profesional una vez terminó sus estudios. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/shGPpy0AcYM?si=vTd1xmSejCz3tlVB" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Haría su debut profesional el 20 de agosto de 2011, enfrentando a su compatriota <b>Kevin Croom</b> en una pelea en peso pactado (160lbs), consiguiendo dejarlo KO en apenas un minuto de combate. De esta manera iniciaría su carrera, peleando 2 veces más ese año, primero ante <b>Joe Kelso</b>, a quien vencería por nocaut en el primer asalto, y luego ante <b>Donnie Bell</b> a quien derrotaría por TKO en el segundo asalto. </p>
                    <p className={styles.peleador__article__text}>Tendría 4 combates en el año 2012, siendo el primero de estos una victoria ante el estadounidense <b>Marcus Edwards</b>, a quien derrotaría por decisión unánime; la segunda victoria sería el australiano <b>Sam Young</b>, a quien sometería en el segundo asalto; la tercera de sus peleas sería ante <b>Drew Foclett</b>, a quien dejaría KO a los 12 segundos de empezar el combate; y finalmente en su última pelea del año enfrentaría a <b>Adrián Valdez</b>, a quien derrotaría por TKO en el inicio del segundo asalto. </p>
                    <p className={styles.peleador__article__text}>Para el año 2013 firmaría con la promotora <b>WSOF</b>, donde tendría varias de sus actuaciones más destacadas, peleando ese año en 3 oportunidades. La primera de estas peleas sería ante el brasileño <b>Gesias Cavalcante</b>, a quien derrotaría por TKO en el primer asalto; la segunda sería ante <b>Brian Cobb</b> a quien vencería por TKO en el tercer asalto del combate; y la última pelea sería ante su compatriota <b>Dan Lauzon</b> a quien noquearía en el segundo asalto.</p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/6_hDlEfeTFw?si=T9oWO2sq9ROglRHA" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Ya con un récord de 10-0 tendría la oportunidad de pelear por el Campeonato Inaugural de Peso Ligero de WSOF, que disputaría el 18 de enero de 2014 enfrentando a <b>Richard Patishnock</b>, a quien vencería por TKO en el primer asalto de la pelea, en sólo un minuto y 9 segundos.</p>
                    <p className={styles.peleador__article__text}>Defendería rápidamente el título ante el luchador manco <Link href='/articulos/luchador-manco-de-mma'>Nick Newell</Link> el 5 de junio de 2014, consiguiendo defender exitosamente su cinturón al derrotar por TKO en el segundo asalto a su rival. </p>
                    <p className={styles.peleador__article__text}>Volvería a pelear otra vez el 15 de noviembre de ese mismo año ante <b>Melvin Guillard</b>, aunque esta pelea no sería titular, debido a que Melvin no dió el peso necesario para competir por el título. De igual forma, Justin Gaethje consiguiría hacerse con la victoria nuevamente por decisión dividida. </p>
                    <p className={styles.peleador__article__text}>En marzo de 2015 se enfrentaría al peruano <b>Luis Palomino</b>, a quien sería capaz de derrotar por TKO en el tercer asalto de la pelea, defendiendo nuevamente el cinturón de forma exitosa. Para el 18 de septiembre se programaría una revancha ante Palomino, que terminaría de la misma forma, con un Gaethje siendo capaz de noquear a su adversario en el segundo asalto del encuentro. </p>
                    <p className={styles.peleador__article__text}>Justin defendería en 2 ocasiones más su cinturón, siendo la primera de estas defensas ante el estadounidense <b>Brian Foster</b>, contra quien solo necesitaría un asalto para noquear. Y por último, defendería ante el brasileño <b>Luiz Firmino</b>, a quien derrotaría por TKO una vez finalizado el tercer asalto, debido a que su rival no estaba en condiciones de seguir peleando a los ojos de los médicos. Concretando de esta forma su paso por WSOF, donde ganaría todos sus 11 combates, siendo campeón de la compañía, y defendiendo de forma exitosa el cinturón en 5 ocasiones. </p>
                    <p className={styles.peleador__article__text}>Gaethje abandonaría la compañía para firmar y unirse a la UFC en el año 2017, donde debutaría el día 7 de julio, para enfrentar al veterano <b>Michael Johnson</b>, a quien sería capaz de derrotar por TKO en el segundo asalto de la pelea, ganando ya en su debut 2 bonos, siendo uno a la Actuación de la Noche, y otro a la Pelea de la Noche. Además este combate sería elegido como la Pelea del Año 2017. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/solphxML3FQ?si=OJ4BGBab7Q1VBAyp" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Ya en su segunda pelea en la compañía le pusieron uno de los rivales más difíciles posibles, teniendo que enfrentar al excampeón de la división <b>Eddie Alavarez</b>, quien hacía tan sólo 1 año había perdido su cinturón con <Link href='/peleadores/conor-mcgregor'>Conor McGregor</Link>. El combate llegaría al tercer asalto y en lo que estaba siendo un espectáculo para todos los espectadores, Eddie fue capaz de conectar un rodillazo y golpes a nuestro protagonista que le terminaron por otorgar la victoria por TKO, siendo esta la primer derrota profesional de Gaethje. De igual forma, esta pelea le sirvió para ganar nuevamente el bono a la Pelea de la Noche. </p>
                    <p className={styles.peleador__article__text}>Lamentablemente para Justin, su siguiente combate no sería más fácil, puesto que el 14 de abril de 2018 se lo pondría a pelear como evento estelar de UFC ante el estadounidense <Link href='/peleadores/dustin-poirier'>Dustin Poirier</Link>, en una pelea que llegaría al cuarto asalto, pero que terminaría de igual forma que la anterior, con Poirier siendo capaz de conectar los golpes que le darían la victoria por TKO. Sin embargo, nuevamente esta sería elegida la Pelea de la Noche, lo que siginificaba un nuevo bono para nuestro protagonista, y no sólo eso, puesto que esta también sería elegida la pelea del año 2018. </p>
                    <p className={styles.peleador__article__text}>Pero estas 2 derrotas consecutivas, las primeras de su carrera, no detendrían a nuestro protagonista de escalar hasta alcanzar su objetivo de luchar por el título. De hecho, unos pocos meses después de la pelea contra Poirier, Gaethje aceptaría pelear en un evento encabezado por él contra <b>James Vick</b>, a quien luego de un minuto de pelea, dejaría KO con un golpe, en desempeño que le haría ganar el bono a la Actuación de la Noche. </p>
                    <p className={styles.peleador__article__text}>En su siguiente combate, con fecha al 30 de marzo de 2019, no defraudaría y volvería a dar una actuación de espectáculo, al enfrentar al histórico luchador brasileño de la UFC, <b>Edson Barboza</b>, a quien en 2 minutos y medio dejaría KO con un golpe en la cabeza, ganando de nuevo, por cuarta vez en sus 5 peleas en la UFC, el bono a la Pelea de la Noche. </p>
                    <p className={styles.peleador__article__text}>En otro Fight Night en el que encabezaría la pelea estelar, se enfrentaría a <b>Cowboy Cerrone</b> el 14 de septiembre de 2019, consiguiendo en otra protagónica actuación, derrotar a su rival por TKO en el primer asalto de la pelea. Otra vez ganaría el bono a la Actuación de la Noche por lo hecho en el octágono. </p>
                    <p className={styles.peleador__article__text}>El 9 de mayo de 2020 en el UFC 249 volvería a la jaula para enfrentar a quien quizás era el rival más peligroso hasta ese momento, <Link href='/peleadores/tony-ferguson'>Tony Ferguson</Link>, que llevaba una racha de 12 victorias consecutivas para cuando se organizó la pelea con nuestro protagonista. Debido a problemas que tenía para defender el cinturón el entonces campeón de la división, <Link href='/leyendas/khabib-nurmagomedov'>Khabib Nurmagomedov</Link>, es que se puso en juego un cinturón interino entre estos 2 luchadores, para que el ganador pudiera enfrentar al campeón en el futuro. Aquella noche, en un combate que llegaría hasta el quinto asalto, Gaethje sería capaz de noquear a su rival en el último asalto, convrtiéndose en el campeón interino de la división de peso ligero, ganando otra vez el bono a la Pelea de la Noche, y el bono a la Actuación de la Noche. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/dGWDT3iyrdw?si=OVYEMdQbDkkWfrQZ" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>De esta forma, el 24 de octubre de 2020 en el UFC 254, nuestro protagonista pelearía para unificar el cinturón y para convertirse en el campeón indiscutido ante <Link href='/leyendas/khabib-nurmagomedov'>Khabib Nurmagomedov</Link>. Pero lamentablemente par él, aquella noche no sería capaz de quitarle el invicto a su rival, cayendo derrotado por una sumisión en el segundo asalto de la pelea. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/XMJW1L9a-J4?si=vWWxxVsQ_rM6x525" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Gaehtje volvería para pelear sólo una vez en el año 2021, haciéndolo para enfrentar a <Link href='/peleadores/michael-chandler'>Michael Chandler</Link> el 6 de noviembre en el UFC 268, consiguiendo otra vez más dar espectáculo, al vencerlo por decisión unánime luego de 3 asaltos, siendo esta elegida la Pelea de la Noche, y tiempo después la Pelea del Año 2021, siendo esta la tercera vez que uno de sus combates recibe esta distinción. </p>
                    <p className={styles.peleador__article__text}>En el año 2022 tendría la oportunidad de volver a pelear por el cinturón de las 155lbs, esta vez para enfrentar al nuevo campeón brasileño <Link href='/peleadores/charles-oliveira'>Charles Oliveira</Link>. Aunque lamentablemente volvería a caer derrotado en esta pelea por el título, siendo sometido a los 3 minutos del primer asalto. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/5sX_HzPNPoM?si=60fUYPe8dm2EEsMa" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>El estadounidense no volvería a pelear hasta el 2023, haciendo su regreso ante el luchador de Azerbaiyán <b>Rafael Fiziev</b> el 18 de marzo en el UFC 286. Como nos tiene acostumbrados, se iría a la guerra con su rival, en un combate que se extendería hasta los 3 asaltos y que terminaría ganando por decisión mayoritaria, en la que sería elegida la Pelea de la Noche. </p>
                    <h3>Justin Gaethje y el Cinturón BMF</h3>
                    <p className={styles.peleador__article__text}>El 29 de julio de 2023, Justin Gaethje se enfrentaría a <Link href='/peleadores/dustin-poirier'>Dustin Poirier</Link> por el título BMF (Badest Mother Fucker), que según a dicho la UFC <b>Premia a los que tienen las agallas de para producir un momento estelar tras otro</b> cada vez que pelean. Poniendo nuevamente en juego el cinturón que ya se habían disputado en su momento <Link href='/articulos/jorge-masvidal-historia'>Jorge Masvidal</Link> y <Link href='/articulos/nate-diaz-historia'>Nate Diaz</Link>, entre estos 2 luchadores que eran los favoritos de la división de peso ligero.</p>
                    <p className={styles.peleador__article__text}>El título terminó siendo para Justin Gaethje que luego de darle una patada en la cabeza a <Link href='/peleadores/dustin-poirier'>Dustin Poirier</Link> que lo dejaría KO, ganaría la pelea y su quinto premio a la actuación de la noche en UFC.</p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/2UhTcnCRueY?si=ogBfnX4wk4IvsaRE" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Además, Justin Gaethje sería el primer peleador en defender este cinturón, ya que Masvidal no lo había hecho. Poniéndolo en juego en el <Link href='/covertura-ufc/ufc300-main-event'>UFC 300</Link> contra luchador de una división inferior y excampeón de la misma <Link href='/peleadores/max-holloway'>Max Holloway</Link>. Para aquel evento especial, Dana White había prometido elevar el bono a La Pelea de la Noche hasta lo $300k para quienes den la mejor pelea, y como no podía ser de otra forma, el combate que fue elegido es el que tenía a Gaethje como uno de los protagonistas. Aunque lastimosamente para él, sería en una pelea que tendría su derrota, al ser noqueado en el último segundo de la pelea, luego de haber intercambiado golpes como loco con Holloway durante los últimos 10 segundos, en un momento que los fans jamás olvidaremos en nuestra vida. </p>
                    <EndArticle />
                </article>
                <AsideChamps />
            </section>
        </main>
    )
}