import styles from '@/app/leyendas/components/leyenda.module.css'
import Link from 'next/link'
import AsideChamps from '@/app/components/asides/AsideChamps'
import KhabibHero from './KhabibHero'


export default function Khabib () {
    return(
        <main>
            <KhabibHero />
            <section className={styles.leyenda__articles__container}>
                <article className={styles.leyenda__article}>
                    <h2 className={styles.leyenda__article__title}>Khabib Nurmagomedov UFC</h2>
                    <p className={styles.leyenda__article__text}>Khabib es un ex luchador ruso de MMA, es considerado uno de los mejores peleadores de este deporte, que se destacó principalmente en su carrera en la <Link href='/promotoras/ufc'>UFC</Link> donde supo ser campeón en la división de Peso Ligero, concretando una correra de excelencia en la que ganó 29 combates y no perdió ninguno. </p>
                    <p className={styles.leyenda__article__text}>Así mismo, supo ser campeón del mundo de <b>Sambo</b> en 2 ocasiones en los años 2009 y 2010, deporte del cual es maestro internacional. También es maestro internacional en Judo, donde es poseedor del cinturón negro, del deporte en combate cuerpo a cuerpo y del deporte en Pancracio.</p>
                    <h2 className={styles.leyenda__article__title}>Khabib Nurmagomedov Biografía</h2>
                    <p className={styles.leyenda__article__text}>Khabib Abdulmanápovich Nurmagomédov nació el 22 de septiembre de 1988 en el pueblo de Sildi en el distrito Tsumadinsky de RASS de Daguestán, una república autónoma dentro de la ya disuelta Unión Soviética. Es proveniente de una familia Avar, siendo el segundo de 3 hijos, siendo su hermano mayor Magomed, y su hermana menor Amina, con ellos es que se mudo de niño a la capital de Daguestán, Majachkalá, donde se crió junto a sus hermanos y primos.</p>
                    <p className={styles.leyenda__article__text}>Como acostumbran a hacer los niños de su edad en Daguestán, comenzó a luchar desde temprano, bajo la tutela de su propio padre, quien era dueño de un edificio de 2 pisos, en el que decidió transformar la planta baja en un gimnasio, donde Khabib, al ver como estudiantes entrenaban en aquel gimnasio, comenzó a interesarse por las artes marciales.</p>
                    <p className={styles.leyenda__article__text}>Su padre, llamado Abdulmanap Nurmagomedov, de la misma manera había comenzado a entrenar desde pequeño artes marciales, concretamente Judo y Sambo, que aprendió en el ejército donde fue condecorado, así mismo fue el entrenador sénior del equipo nacional de sambo de combate en la República de Daguestán. De esta forma es que le enseñó Lucha a su hijo desde los 12 años, Judo desde los 15 y reanudó el entrenamiento de Sambo a los 17.</p>
                    <p className={styles.leyenda__article__text}>Sobre la época en que Abdulmanap entrenaba a Khabib cuando este era muy pequeño, existe un video en el que se vé como el campeón de UFC pelea contra un oso teniendo este 9 años de edad. Dicho video proviene de una entrevista del peleador ruso en la que también estaba el campeón de boxeo <b>Mike Tyson</b>. También se puede destacar como Khabib habla de la gran importancia que tuvo su padre para él, y como fue este el que lo motivaba a ser el mejor.</p>
                    <iframe className={styles.leyenda__article__video} width="560" height="315" src="https://www.youtube.com/embed/3pKQ2yDIBxY?si=epw_8VtKQfnhhHEW" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen></iframe>
                    <p className={styles.leyenda__article__text}>Su carrera en las MMA comenzaría de manera profesional el 13 de septiembre de 2008, cuando se enfrentaría a <b>Vusal Bayramov</b> en un evento de combates organizado en Ucrania, dicho debut lo acabaría ganando gracias a una sumisión que conseguiría en el segundo asalto. Luego de aquel primer combate, participaría del evento Pankration Atrium Cup el 11 de octubre de 2008, en el cual debería enfrentar a 3 rivales el mismo día. Khabib lograría ganar las 3 peleas por decisión unánime, logrando así acumular un récord de 4-0 en su primer mes como profesional. </p>
                    <p className={styles.leyenda__article__text}>Luego de aquel primer mes, intercalando peleas entre Peso Ligero y Peso Wélter, tendría 12 combates profesionales en promotoras de Rusia y Ucrania, de los cuales lograría finalizar a su oponente en 11 de ellos. Habiendo acumulado un récord de 16-0 terminaría por llamar la atención de <Link href='/promotoras/ufc'>UFC</Link> quienes lo llamarían para firmar un contrato de 6 peleas.</p>
                    <p className={styles.leyenda__article__text}>Khabib Nurmagomedov haría su debut en la UFC el 20 de enero de 2012 en el <b>UFC on FX: Guillard vs. Miller</b>, donde pelearía contra el iraní <b>Kamal Shalorus</b> en la división de Peso Ligero, donde se mantendría en toda su carrera en la compañía. Terminaría por vencer con una sumisión en el tercer asalto.</p>
                    <p className={styles.leyenda__article__text}>Luego de 7 victorias consecutivas, siendo la última contra <b>Darrel Horcher</b> a quien venció por nocaut en el segundo asalto, se esperaba que Khabib peleara por el título contra el entonces campeón <b>Eddie Alvarez</b>, tal y como lo había anunciado el mismo Dana White por Twitter, sin embargo se terminaría anunciando que quien pelearía con Alvarez sería <Link href='/peleadores/conor-mcgregor'>Conor Mcgregor</Link>, quien buscaba ser doble campeón. Desde aquí comenzó a iniciarse la rivalidad que el ruso luego tendría con Mcgregor. Finalmente Khabib terminaría peleando con <b>Michael Johnson</b> a quien derrotaría con una sumisión en le tercer asalto.</p>
                    <p className={styles.leyenda__article__text}>Luego de esto se buscaría hacer una pelea por el título contra <Link href='/peleadores/tony-ferguson'>Tony Ferguson</Link>, siendo esta la tercera vez que se progamaba una pelea contra Tony, finalmente terminaría por no darse debudo a que Khabib se enfermó en el corte de peso. En su lugar se terminaría enfrentando a Edson Barboza el 30 de diciembre, ganando la pelea por decisión unánime.</p>
                    <p className={styles.leyenda__article__text}>McGregor dejó el título vacante de la división, por lo que se programó por cuarta vez una pelea entre Khabib Nurmagomedov y Tony Ferguson. En esta ocasión la pelea no se dió dado que Tony sufrió una lesión en la rodilla que lo dejó fuera. En su lugar, luego de buscar a varios peleadores para reemplazarlo, la pelea terminó siendo contra el estadounidense <b>Al Iaquinta</b>, a quien luego de 5 asaltos venció por decisión unánime, convirtiendose finalmente en el campeón de Peso Ligero de UFC.</p>
                    <p className={styles.leyenda__article__text}>Khabib defendería el título en 3 ocasiones, ganando los 3 combates por sumisión. Siendo su primera defensa contra Conor Mcgregor, a quien derrotó luego de 4 asaltos; la segunda contra Dustin Poirier, contra quien le basataron 3 asaltos para someterlo; y la tercera y última defensa sería contra Justin Gaethje en Abu Dhabi, a quien vencería luego de 2 asaltos, concretando así su retiro de las MMA como campeón de UFC invicto, ranqueado #1 en el libra por libra de la compañía, y con un récord de 29-0.</p>
                    <h2 className={styles.leyenda__article__title}>Khabib Última Pelea</h2>
                    <p className={styles.leyenda__article__text}>El último combate en el que seríamos capaces de ver pelear a Khabib sería en el UFC 254 el 24 de octubre de 2020, en aquella ocasión contra el estadounidense <Link href='/peleadores/justin-gaethje'>Justin Gaethje</Link>, quien venía de una racha de 4 victorias consecutivas, siendo la última contra <Link href='/peleadores/tony-ferguson'>Tony Ferguson</Link> por el Campeonato Interino de Peso Ligero de UFC, a quien terminando el 5to y último asalto de la pelea logró noquear a golpes. Por su parte Khabib venía de defender el título hacía más de un año contra <Link href='/peleadores/dustin-poirier'>Dustin Poirier</Link>, a quien derrotó con una sumisión en el tercer asalto.</p>
                    <p className={styles.leyenda__article__text}>La pelea finalmente se la terminaría llevando el campeón ruso, quien con una sumisión en el segundo asalto terminaría por vencer a Gaethje. Terminando así, de retirarse de las Artes Marciales Mixtas con un récord de 29-0.</p>
                    <iframe className={styles.leyenda__article__video} width="560" height="315" src="https://www.youtube.com/embed/MQcXEWPesAw?si=eezqNxAGr_uhyAuu" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen></iframe>
                    <h2 className={styles.leyenda__article__title}>Khabib Estadísticas</h2>
                    <p className={styles.leyenda__article__text}>Khabib Nurmagomedov, ha peleado un total de 29 veces teniendo un récord invicto de 29-0. 29 victorias de las cuales 8 fueron por nocaut, 11 por sumisión y 10 por decisión, esto lo convierte en la racha invicta más larga en MMA, permaneciendo invicto a lo largo de toda su carrera profesional. Además cuenta con la salvajada de sólo haber perdido 2 asaltos dentro de la UFC, siendo uno, la primera ronda en su última pelea contra <Link href='/peleadores/justin-gaethje'>Justin Gaethje</Link> y el otro en la tercera ronda en su pelea contra <Link href='/peleadores/conor-mcgregor'>Conor McGregor</Link>.</p>
                    <p className={styles.leyenda__article__text}>A lo largo de su carrera, de 1444 golpes significativos intentados logró 705, lo que le da un 49% de efectividad. De 127 intentos de derribo logró 49, lo que implica un 48% de efectividad. Posee un 85% de precisión en defensa de derribno y un 65% de efectividad en la defensa de golpes significativos.</p>
                    <p className={styles.leyenda__article__text}>Además, en su pelea contra el estadounidense <b>Abel Trujillo</b> por UFC 160, logró el récord de la mayor cantidad de derribos en una pelea de UFC, completando 21 de 28 intentados. Aquella pelea luego de 3 asaltos se la terminaría llevando el ruso por decisión unánime.</p>
                </article>
                <AsideChamps />
            </section>
        </main>
    )
}