import PeleadoresHero from '@/app/peleadores/components/PeleadoresHero'
import poirier from '@/assets/peleadores__images/0-100/0-10/dustin-poirier/poirier.png'
import styles from '@/app/peleadores/components/peleador.module.css'
import Link from 'next/link'
import dynamic from 'next/dynamic'
import type { Metadata } from 'next'

const AsideChamps = dynamic(() => import('@/app/components/asides/AsideChamps'))
const EndArticle = dynamic(() => import('@/app/components/EndArticle'))

export const metadata: Metadata = {
    title: 'Dustin Poirier',
    description: 'Dustin Poirier es un peleador estadounidense de MMA que pelea en la división de Peso Ligero de la UFC desde enero de 2011, cuando haría su debut ante su compatriota Josh Grispi en el UFC 125. Ha destacado en la compañía al llegar a ser campeón interino de su división, luego de ganarle por decisión unánime al entonces campeón de peso pluma Max Holloway.',
    openGraph: {
        title: 'Dustin Poirier',
        description: 'Dustin Poirier es un peleador estadounidense de MMA que pelea en la división de Peso Ligero de la UFC desde enero de 2011, cuando haría su debut ante su compatriota Josh Grispi en el UFC 125. Ha destacado en la compañía al llegar a ser campeón interino de su división, luego de ganarle por decisión unánime al entonces campeón de peso pluma Max Holloway.',
        url: 'https://fullmma.org/peleadores/dustin-poirier'
    }
}

export default function Poirier () {
    return(
        <main>
            <PeleadoresHero peleadoresImage={poirier} w={30} l={10} d={0} nombre='Dustin Poirier' apodo='THE DIAMOND' categoria='Peso Ligero' time='2025-10-29' />
            <section className={styles.peleador__articles__container}>
                <article className={styles.peleador__article}>
                    <h2 className={styles.peleador__article__title}>Dustin Poirier UFC</h2>
                    <p className={styles.peleador__article__text}>Dustin Poirier es un peleador estadounidense de MMA que pelea en la división de Peso Ligero de la <Link href='/articulos/ufc'>UFC</Link> desde enero de 2011, cuando haría su debut ante su compatriota <b>Josh Grispi</b> en el UFC 125.  </p>
                    <p className={styles.peleador__article__text}>Es uno de los mejores peleadores que ha parido esta división en la UFC, siendo además de los peleadores más entretenidos para ver. No por nada a lo largo de su carrera en la compañía, Poirier ha sabido ganar el bono a La Pelea de la Noche en 10 ocasiones, siendo junto a <b>Edson Barboza</b>, el peleador que más veces ha ganado este bono en la compañía. Y no es para menos, ya que su carrera y los numeros de esta hablan por si solos, siendo uno de los peleadores con más nocauts en la historia de la división, siendo uno de los que más finaliza, contando con 40 combates en su espalda, el estadounidense es un auténtico perro de pelea que a cualquiera debería de inspirar respeto. </p>
                    <p className={styles.peleador__article__text}>Ha destacado en la compañía al llegar a ser campeón interino de su división, luego de ganarle por decisión unánime al entonces campeón de peso pluma <Link href='/peleadores/max-holloway'>Max Holloway</Link>, el día 13 de abril de 2019 en el evento estelar del UFC 236, en lo que además fue elegida como La Pelea de la Noche. </p>
                    <h2 className={styles.peleador__article__title}>Dustin Poirier Récord</h2>
                    <p className={styles.peleador__article__text}>Dustin Poirier en 41 peleas, ostenta un récord de 30-10 (1). Siendo 15 de sus victorias por la vía del nocaut, 8 por la vía de la sumisión sumisión y 7 por decisión. Mientras que 3 de sus 9 derrotas fueron la vía del nocaut, 4 por sumisión y sólo 3 por decisión. Además tiene un combate sin resultado contra <b>Eddie Alvarez</b>, que se paró debido a que Alvarez aplicó 2 rodillazos ilegales contra Poirier mientras estaba derribado.</p>
                    <h2 className={styles.peleador__article__title}>Dustin Poirier Historia</h2>
                    <p className={styles.peleador__article__text}>Dustin Glenn Poirier, nació el 19 de enero de 1989, en la ciudad de Lafayette, Luisiana, en Estados Unidos, ciudad donde hoy en día pasa la mayor parte del tiempo junto a su esposa e hija. Es de ascendencia francesa y comenzó a luchar en la secudaria en Northside High School en Lafayette, escuela y estudios que acabó abandonando en noveno grado, debido a que se metía repetidamente en problemas y peleas callejeras.</p>
                    <p className={styles.peleador__article__text}>Tuvo su primer pelea en 2007, pero recién comenzaría a competir como luchador de MMA en mayo de 2009, con apenas 20 años enfrentando a su compatriota <b>Aaron Suárez</b> y dejándolo KO en el primer minuto del primer asalto. Así conseguiría ganar los primeros 7 combates de su carrera, siendo todos por finalización con 4 de ellos siendo por nocaut y 3 por sumisión. </p>
                    <p className={styles.peleador__article__text}>Con este récord, firmaría por la promotora <b>WEC</b>, en la que debutaría el día 18 de agosto de 2010, enfrentando a <b>Danny Castillo</b>, contra quien recibiría la primera derrota de su carrera, al caer derrotado por decisión unánime. De igual manera en su siguiente combate sería capaz de recuperarse, al vencer por TKO a <b>Zach Micklewright</b> en el primer asalto del combate. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/U-w162eVpgc?si=vlbgo-JKG6ivm5OG" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>En aquella época, la compañía en la que estaba peleando cambiaría de manos, siendo absorvida por la UFC, por lo que todos los peleadores que competían allí pasarían a hacerlo ahora en la compañía de artes marciales mixtas más grande del mundo. Ahora en en esta nueva compañía, debutaría el 1 de enero de 2011 en el UFC 125, para enfrentar a <b>Josh Grispi</b> en lo que además sería su debut en el peso pluma, logrando llevarse la victoria por decisión unánime. </p>
                    <p className={styles.peleador__article__text}>En su siguiente pelea, se vería cara a cara ante el británico <b>Jason Young</b>, a quien enfrentaría el 11 de junio de ese mismo año por el UFC 131, consiguiendo una nueva victoria por decisión unánime. La última pelea del año la tendría el 12 de noviembre al enfrentar al luchador americano <b>Pablo Garza</b>, a quien lograría someter en el segundo asalto de la pelea. </p>
                    <p className={styles.peleador__article__text}>El 4 de febrero de 2012 en el UFC 143 se enfrentaría a quien en el futuro se convertiría en un peleador histórico, <Link href='/peleadores/max-holloway'>Max Holloway</Link>, contra quien tendría una actuación destacada en un combate que no pasaría del primer asalto, puesto que Poirier sería capaz de someter a Max en el priemr asalto de la pelea. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/bDq1OqW7aB4?si=Z_1CMI7dR0_D9My-" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Luego de aquella meritoria victoria, a Poirier se le presentaría la oportunidad de encabezar un evento por primera vez en su carrera, el día 15 de mayo de 2012, enfrentando para ello al histórico luchador coreano <b>Chang-sung Jung (The Korean Zombie)</b>, contra quien sufriría la primer derrota de su carrera en la UFC, al ser sometido al llegar al cuarto asalto del combate. Pese a aquella derrota, la pelea que dió le serviría para ganar el bono a la Pelea de la Noche, siendo elegida tiempo después aquella como la Pelea del Año 2012. </p>
                    <p className={styles.peleador__article__text}>En diciembre de ese mismo año volvería a pelear consiguiendo salir victorioso, al someter en el primer asalto a su rival <b>Jonathan Brookins</b>. Pelearía en 3 ocasiones en el año 2013, siendo la primera de estas peleas ante <b>Cub Swanson</b>, contra quien luego de 3 asaltos caería derrotado por decisión unánime. La segunda pelea del año la tendría el 31 de agosto, enfrentando para ello a <b>Erik Koch</b>, a quien vencería por decisión unánime. Finalmente pelearía en diciembre ante el brasileño <b>Diego Brandao</b>, con quien conseguiría una impresionante victoria por KO en el primer asalto. </p>
                    <p className={styles.peleador__article__text}>Durante el año siguiente tendría otras 2 peleas, siendo la primera el 16 de abril de 2014 ante el sueco <b>Akira Corassani</b>, contra quien lograría una importante victoria por TKO en el segundo asalto de la pelea, ganando además el bono a la Pelea de la Noche por su desempeño. La última pelea del año tendría lugar el 27 de septiembre ante el siempre controvertido <Link href='/peleadores/conor-mcgregor'>Conor McGregor</Link>, ante quien lamentablemente nuestro protagonista caería derrotado por TKO la primera parte del primer asalto. </p>
                    <p className={styles.peleador__article__text}>Luego de aquella derrota, decidiría moverse de división para empezar a competir en la división de peso ligero como al inicio de su carrera. Para ello, enfrentaría primero el 4 de abril de 2015 al brasileño <b>Carlos Diego Ferreira</b>, rival al que lograría dejar KO en el primer asalto, ganando además el bono a la Actuación de la Noche por su desempeño. El 6 de junio de ese mismo año volvería a subirse al octágono para enfrentar al estadounidense <b>Yancy Medeiros</b>, a quien nuevamente lograía noquear en el primer asalto, para ganar otra vez el bono a la Actuación de la Noche. </p>
                    <p className={styles.peleador__article__text}>A lo largo del 2016 se mantendría activo, teniendo 3 peleas en el año, en las que enfrentaría primeramente el 2 enero de al irlandés <b>Joe Duffy</b>, a quien vencería por decisión unánime; en su segunda pelea con fecha para el 4 de enero se vería a cara ante <b>Bobby Green</b>, a quien lograría dejar KO en el primer asalto; y por último, encabezando nuevamente un evento de la compañía, enfrentando a <b>Michael Johnson</b> el 17 de septiembre, caería derrotado de manera dolorosa por KO en el primer asalto de la pelea.</p>
                    <p className={styles.peleador__article__text}>El 11 de febrero de 2017 volvería a subir al octágono para enfrentar al histórico luchador de la compañía <Link href='/articulos/jim-miller-historia'>Jim Miller</Link>, a quien enfrentaría en el UFC 208, en un enfrentamiento que se extendería hasta los 3 asaltos donde Poirier se haría de la victoria por decisión unánime, y que haría a ambos peleadores merecedores del bono a La Actuación de la Noche. Volvería a pelear el 13 de mayo de ese mismo año, para enfrentar al histórico campeón de Bellator <b>Eddie Alvarez</b>, con quien tendría una pelea que finalmente acabaría sin resultado, luego de que Alvarez lanzara rodillazos ilegales cuando Dustin estaba derribado. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/31-uOsBYdw0?si=1nKiQXKiD0M4pRpk" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>En su siguiente enfrentamiento volvería a encabezar un Fight Night, cuando el día 17 de noviembre se enfrentaría a <b>Anthony Pettis</b>, con quien tendría un combate que terminaría en el tercer asalto, cuando nuestro protagonista sería capaz de someter a su rival, ganando además del combate, el bono a la Actuación de la Noche. </p>
                    <p className={styles.peleador__article__text}>El 14 de abril de 2018 tendría una de sus peleas más emblemáticas, cuando enfrentaría al histórico peleador de la división <Link href='/peleadores/justin-gaethje'>Justin Gaethje</Link>, en un evento encabezado por ambos peleadores, darían una auténtica guerra, en una pelea que acabaría en el cuarto asalto, cuando Poirier sería capaz de noquear a su rival. Por el espectáculo dado por ambos luchadores, se ganarían el bono a La Pelea de la Noche, en la que además tiempo después sería elegida como la Pelea del Año 2018. </p>
                    <p className={styles.peleador__article__text}>Luego del espectáculo dado por nuestro protagonista, se lo programaría para encabezar un nuevo evento en el que esta vez se vería cara a cara en una revancha ante <b>Eddie Alvarez</b>, el día 28 de julio de 2018. Aquella noche volvería a dar cátedra como luchador, al ser capaz de noquear a su rival en el segundo asalto de la pelea, ganando por su desempeño el bono a la Actuación de la Noche. </p>
                    <p className={styles.peleador__article__text}>Pese a lo grandiosa que ha sido su carrera, y a lo excelente luchador que ha demostrado ser a lo largo de los años, ha tenido la mala fortuna de coincidir con quienes posiblemente sean los mejores peleadores en la historia de la división de peso ligero de la UFC, lo que le impidió hacerse del cinturón de la división.</p>
                    <p className={styles.peleador__article__text}>Su primer intento de disputar el título, vino después de que consiguiera ganar el campeonato interino de peso ligero de UFC, al vencer por decisión unánime al ex-campeón de peso pluma de UFC <Link href='/peleadores/max-holloway'>Max Holloway</Link>, en la que sería elegida la Pelea de la Noche. Esta victoria le abriría la puerta para enfrentar a <Link href='/leyendas/khabib-nurmagomedov'>Khabib Nurmagomedov</Link>, contra quien perdería por sumisión en el tercer asalto, aunque estuvo cerca de finalizar una guillotina que casi le otorga la victoria, lamentablemente para nuestro protagonista dicha guillotina no prosperó.</p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/1yTHmY3EArE?si=b7O6tRaD-QgWee02" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Luego de aquella derrota sólo tendría una pelea en el año 2020, el día 27 de junio de 2020 en un evento encabezado por él, donde enfrentaría al luchador de Nueva Zelanda <b>Dan Hooker</b>, en lo que sería una de las mejores peleas que ví personalmente en mi vida, y que vale la pena completamente verla sin comentarios. Aquel combate se extendería hasta completar los 5 asaltos, con Poirier llevándose la victoria por decisión unánime, en la que sería elegida como la Pelea de la Noche, siendo esta la sexta pelea de nuestro protagonista en ser premiada con este bono. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/x5gZQfFUFk0?si=-fddwzBMUTPj8DWs" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Volvería al octágono el día 23 de enero de 2021, encabezando el UFC 257, donde enfrentaría en una revancha al luchador que una vez lo derrotó y a quien es la mayor estrella que tuvo este deporte, <Link href='/peleadores/conor-mcgregor'>Conor McGregor</Link>. En aquella pelea organizada en Abu Dhabi, nuestro protagonista sería capaz de vengar su última derrota al noquear a Conor en el segundo asalto, ganando además el bono a la Actuación de la Noche, como recompensa por su nocaut. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/6yu2AWK4rxo?si=rgGRZ2-rp7PgEMfT" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Se programaría una revancha para el 10 de julio de ese mismo año, para cerrar la rivalidad con el irlandés en una trilogía. Aquella noche en lo que fue el final del UFC 264, terminaría de forma anticlimática, cuando finalizando el primer asalto McGregor de forma accidental se rompería la pierna, siendo incapaz de seguir peleando dado que ni siquiera se podía poner de pie. Debido a esto la pelea terminaría en victoria para nuestro protagonista por TKO por parada médica. </p>
                    <p className={styles.peleador__article__text}>Luego de haber acumulado 3 victorias consecutivas ante rivales durísimos, a Poirier se le presentaría la oportunidad de volver a disputar el título de las 155lbs, enfrentando ahora al nuevo campeón brasileño <Link href='/peleadores/charles-oliveira'>Charles Oliveira</Link> en la última pelea del año con fecha para el 11 de diciembre en el UFC 269. Aquella noche, lamentablemente para Dustin, volvería a caer derrotado al ser sometido en el tercer asalto de la pelea. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/79fuJ72grPA?si=EUMiGi1od2Fp7l2g" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Durante el año 2022 sólo lo veríamos pelear una vez, al estar presente en el UFC 281 el 12 de noviembre. Aquella noche se enfrentaría al excampeón de Bellator <Link href='/peleadores/michael-chandler'>Michael Chandler</Link>, con quien tendría un combate que sería una absoluta guerra y que terminaría de la forma más épica posible, al llegar al tercer asalto luego de un reñido combate, en el que Poirier terminaría por someter a Chandler, volviendo a ganar el bono a la Pelea de la Noche por el espectáculo regalado. </p>
                    <p className={styles.peleador__article__text}>En el 2023 sólo volvería a pelear una vez nuevamente, para encabezar el UFC 291 el 29 de julio, en lo que sería una disputa por el cinturón <b>BMF</b>, que tendría como dispuntantes a quienes son los 2 peleadores más queridos de la división de peso ligero, como lo son el mismo Poirier, y su rival de aquella noche, <Link href='/peleadores/justin-gaethje'>Justin Gaethje</Link>, a quien volvería a enfrentar luego de haberlo noqueado hace 5 años. Lamentablemente para nuestro protagonista, aquella noche caería derrotado por KO en el segundo asalto, luego de recibir una patada en la cabeza que lo mandaría a la lona.</p>
                    <p className={styles.peleador__article__text}>Luego de aquella dolorosa derrota, debía recupera el sendero de la victoria si quería tener alguna oportunidad de volver a disputar el cinturón de la división, por lo que aceptó pelear el 9 de marzo de 2024 en el <Link href='/covertura-ufc/ufc299'>UFC 299</Link> en el evento coestelar ante quien era uno de los mayores prospecto de la división, como lo es el peleador francés <b>Benoit Saint Denis</b>, quien venía en pleno ascenso y ya llevaba acumuladas 5 victorias consecutivas. Sin embargo, Poirier hizo valer su experiencia y su calidad, logrando una increíble victoria por KO en el segundo asalto, que le haría ganar no solo la pelea, sino que también su noveno bono a La Pelea de la Noche. </p>
                    <p className={styles.peleador__article__text}>Luego de aquella increíble victoria, recibiría la última oportunidad de disputar el campeonato de la división, que se daría el 1 de junio de 2024, cuando enfrentaría al campeón <Link href='/peleadores/islam-makhachev'>Islam Makhachev</Link> en el <Link href='/covertura-ufc/ufc302'>UFC 302</Link>, en un combate donde Dustin dió todo lo que tenía para llevarse el cinturón por fin, terminó por perder la pelea en el quinto asalto por sumisión. Derrota que es especialmente dolorosa, dado que con sus 35 años, ya se ve muy difícil volver a ver al &quot;Diamante&quot; volver a disputar el cinturón. Además, luego del combate, dejó entrever que aquella podía ser la última pelea de su carrera.</p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/GNiOhJfG1qE?si=10Zm-cBuBNSGcTaf" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <h2 className={styles.peleador__article__title}>El Retiro de Dustin Poirier</h2>
                    <p className={styles.peleador__article__text}>Luego de perder la que ya era su última oportunidad de ser campeón indiscutido de la UFC, y ya con 36 años, nuestro protagonista decidió que tomaría una pelea más para retirarse oficialmente, tratándose de un evento especial para él, ya que se haría en su honor, en el Estado en que nació, Louisiana, rodeado de sus amigos, familia y comunidad. </p>
                    <p className={styles.peleador__article__text}>Esta pelea de retirada se haría por el cinturón <b>BMF</b> de la UFC, ante el actual campeón de este, <Link href='/peleadores/max-holloway'>Max Holloway</Link>, a quien ya había enfrentado y derrotado en 2 ocasiones. La fecha de la pelea sería el 19 de julio de 2025, en el <Link href='/eventos/ufc318'>UFC 318</Link>, con la pelea de ambos encabezando dicho evento. Aquella noche de UFC sería bastante emotiva, con un evento hecho claramente a medida para Dustin Poirier, para despedirlo como se lo merece una leyenda como él. La pelea sería espectacular, digno de 2 perros de pelea como lo son Poirier y Holloway, y quien se terminaría llevando la victoria lamentablemente para nuestro protagonista sera Max, quien luego de 5 asaltos ganaría por decisión unánime. Dando de esta manera, un adiós a la INMENSA carrera de Dustin &quot;El Diamante&quot; Poirier. </p>
                    <EndArticle />
                </article>
                <AsideChamps />
            </section>
        </main>
    )
}