import styles from '@/app/leyendas/components/leyenda.module.css'
import Link from 'next/link'
import AsideChamps from '@/app/components/asides/AsideChamps'
import CoutureHero from './CoutureHero'


export default function RandyCouture () {
    return(
        <main>
            <CoutureHero />
            <section className={styles.leyenda__articles__container}>
                <article className={styles.leyenda__article}>
                    <h2 className={styles.leyenda__article__title}>Randy Couture UFC</h2>
                    <p className={styles.leyenda__article__text}>Randy Couture es una leyenda de la <Link href='/articulos/ufc'>UFC</Link>, siendo el cuarto de sus peleadres en formar parte del Salón de la Fama de la UFC, siendo el único en ganar un título luego de ser nombrado parte del salón de la fama. Es el campeón más viejo en la historia de la UFC con 43 años, además es el primer peleador en convertirse en doble campeón de la compañía, habiéndo sido 4 veces campeón de la división de peso pesado y 2 veces campeón de la división de peso semipesado.</p>
                    <h2 className={styles.leyenda__article__title}>Randy Couture Récord</h2>
                    <p className={styles.leyenda__article__text}>Randy Couture terminó su carrera en las MMA con un récord de 19-11. Siendo 7 de esas victorias por nocaut, 4 por sumisión y 8 por decisión. Mientras que de sus 11 derrotas, 7 fueron por nocaut, 3 por sumisión y 1 por decisión. </p>
                    <h2 className={styles.leyenda__article__title}>Randy Couture Biografía</h2>
                    <p className={styles.leyenda__article__text}>Randall Duane Couture nació el 22 de junio de 1963 en la ciudad de Everett, ubicada en el Estado de Washington en Estados unidos. En la secundaria se dedicó a practicar wrestling en donde destacó al ganar el campeonato estatal en Washington. Luego de recibirse, serviría en el ejército de los Estados Unidos desde 1982 hasta 1988, periodo en el que obtendría el rango de Sargento en la 101. División Aerotransportada. Además, sería durante su estancia en el ejército cuando aprendería lucha greco-romana, en la que terminaría compitiendo profesinalmente y que le serviría en sus futuros años en las MMA.</p>
                    <p className={styles.leyenda__article__text}>Haría su debut en las MMA el 30 de mayo de 1997, a punto de cumplir sus 34 años. Sería convocado a pelear como suplente con 3 semanas de anticipación en UFC 13, durante aquella época la UFC todavía tenía un formato de eliminatoria para definir a sus campeones, por lo que Randy, primero enfrentó al finlandés <b>Tony Halme</b> en las semifinales del torneo, derrotándolo con un mataleón que lo sometió cumplido 1 minuto del combate. Ese mismo día, se enfrentaría a su compatriota <b>Steven Graham</b> en la final del torneo, a quien vencería por TKO en el primer asalt, convirtiéndose en campeón de la UFC en sus primeras 2 peleas como profesional.</p>
                    <p className={styles.leyenda__article__text}>Unos meses después, ese mismo año, Randy volvería a pelear en UFC, en esta ocasión contra el brasileño <b>Vitor Belfort</b>, en lo que sería una eliminatoria por el título. Por lo que el 17 de octubre de 1997 se enfrentaría al brasileño llevándose la victoria por TKO a los 8 minutos del primer asalto. La pelea por el título la tendría en diciembre, en el UFC Japón, donde enfrentaría a su compatriota <b>Maurice Smith</b>, quien era el vigente campeón en aquel momento, y terminaría llevándose la victoria por decisión mayoritaria luego de una pelea a un sólo asalto de 21 minutos.</p>
                    <iframe className={styles.leyenda__article__video} width="560" height="315" src="https://www.youtube.com/embed/wSEeb2_-qJI?si=ETnO6FW4x7-CLM5c" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.leyenda__article__text}>Aunque le ofrecieron una pelea para defender su título, Couture no la aceptaría y se iría a pelear a la promotora <b>Vale Tudo Japan</b>, por lo que sería despojado del título y quedaría vacante. En la nueva promotora sólo pelearía una vez y obtendría la primer derrota de su carrera, contra el japonés <b>Enson Inoe</b>, quen lo somtería en el primer minuto del primer asalto.</p>
                    <p className={styles.leyenda__article__text}>Luego pelearía en una promotora llamada <b>RINGS: King of Kings</b>, donde pelearía un total de 5 combates, perdiendo el primero contra el ruso <b>Mikhail Illoukhine</b> por sumisión, pero ganándo los 2 siguientes contra el estadounidense <b>Jeremy Horn</b> y contra el japonés <b>Ryushi Yanagisawa</b>, ambas por decisión. Entre medias tuvo una pelea por el campeonato de Peso Pesado de UFC contra <b>Kevin Randleman</b> en el año 2000, a quien vencería por TKO en el tercer asalto convirtiéndose en campeón de la compañía.</p>
                    <iframe className={styles.leyenda__article__video} width="560" height="315" src="https://www.youtube.com/embed/PkbX6zlCWVA?si=iONjh_1ERL5M6AO_" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.leyenda__article__text}>Sin embargo, antes de defender su título, tendría otras 2 peleas en RINGS, ambas el 24 de febrero del 2001. La primera sería una victoria por decisión unánime contra el japonés <b>Tsuyoshi Kohsaka</b>, y la segunda terminaría siendo una derrota contra le holandés <b>Valentijn Overeem</b> por sumisión en menos de un minuto.</p>
                    <p className={styles.leyenda__article__text}>Como dicen que uno no es campeón hasta que defiende, Couture pondría en juego su cinturón en mayo de 2001 contra el brasileño <b>Pedro Rizzo</b>, a quien luego de 5 asaltos vencería por decisión unánime, convirtiéndose esa en la Pelea del Año (2001). Pocos meses después le darían la revancha al brasileño, a quien esta vez nuestro protagonista vencería por TKO en el tercer asalto.</p>
                    <p className={styles.leyenda__article__text}>A esto le seguirían 2 derrotas en 2002, la primera contra <b>Josh Barnett</b> por TKO en el segundo asalto, que le haría perder su cinturón, y la segunda contra <b>Ricco Rodriguez</b> por sumisión en el quinto asalto, en una pelea en la que estaba en juego el Campeonato vacante de Peso Pesado de UFC.</p>
                    <p className={styles.leyenda__article__text}>Luego de 2 derrotas consecutivas, en el año 2003 Randy decidió moverse de división con los semipesados, donde competiría por el campeonato interino de la división contra el contendiente #1 <b>Chuck Liddell</b>, a quien, a pesar de partir como el underdog, fue capaz de noquear a golpes en el tercer asalto. </p>
                    <iframe className={styles.leyenda__article__video} width="560" height="315" src="https://www.youtube.com/embed/1EI5pfl2gjs?si=yy-xBQ-jb_hzRywn" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.leyenda__article__text}>Esta victoria lo llevaría enfrentar al campeón indiscutido <b>Tito Ortiz</b>, a quien vencería por decisión unánime, unificando el título. Luego enfrentaría al brasileño <b>Vitor Belfort</b>, contra Vitor Belfort, con quien perdería por TKO producto de un corte que sufrió sin haber cumplido un minuto de la pelea. Le daría una revancha inmediata, que esta vez acabaría en una victoria para nuestro protagonista por TKO, luego de terminado el tercer asalto por una parada médica. </p>
                    <p className={styles.leyenda__article__text}>Su siguiente defensa sería una revancha contra <b>Chuck Liddell</b>, quien sería capaz de dejarlo KO en el primer asalto. Esto llevaría a Couture a tener que vencer a <b>Mike van Arsdale</b> por sumisión en el tercer asalto, antes de volver a tener una pelea por el título con Chuck. Aunque la tercera pelea de la trilogía contra Chuck Liddell no terminaría muy diferente a su último enfrentamiento, dado que &quot;Icecold&quot; volvería a dejar KO a nuestro protagonista, esta vez en el segundo asalto.</p>
                    <p className={styles.leyenda__article__text}>Al acumular su segunda derrota consecutiva contra Chuck Liddell, Randy Couture decidió volver a la división de peso pesado, donde competiría inmediatamente por el título contra <b>Tim Silva</b>, a quien vencería por decisión unánime el 3 de marzo de 2007, que con 43 años lo convertiría en el campeón más viejo de la historia de la UFC, récord que aún posee y que parece difícil que alguien se lo arrebate en el corto plazo. Su primera defensa sería contra el brasileño <b>Gabriel Gonzaga</b>, a quien derrotaría por TKO en el tercer asalto.</p>
                    <p className={styles.leyenda__article__text}>Sin embargo, perdería su cinturón contra un peleador histórico de la WWE, que en ese entonces tenía un récord de 2-1 y sólo 2 peleas en la UFC, <Link href='/leyendas/brock-lesnar'>Brock Lesnar</Link>, quien en el segundo asalto lo venció por TKO.</p>
                    <iframe className={styles.leyenda__article__video} width="560" height="315" src="https://www.youtube.com/embed/PV28qas35hA?si=e0bQTiwK4OlMAw-x" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.leyenda__article__text}>Luego de aquella derrota, le seguiría otra contra <b>Antônio Rodrigo Nogueira</b>, quien en una pelea de 3 asaltos lo vencería por decisión unánime. Randy volvería a los pesos semipesados para enfrentar a <b>Brandon Vera</b>, a quien vencería por decisión unánime, convirtiéndose en el peleador más viejo en ganar una pelea en UFC. Poco después lograría otra cosa curiosa, al enfrentarse a <b>Mark Coleman</b> y derrtoarlo con una sumisión en el segundo asalto, ya que esta pelea sería la primera, y por el momento la única, en ver enfrentados a 2 miembros del <b>Salón de la Fama de la UFC</b>. Unos meses después retornaría a los pesos pesados, donde enfrentaría a <b>James Toney</b>, a quien sometería en el primer asalto, siendo esta la última victoria de su carrera.</p>
                    <iframe className={styles.leyenda__article__video} width="560" height="315" src="https://www.youtube.com/embed/c3-PEh04hjk?si=1eGexim6CUadqBi2" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.leyenda__article__text}>Lamentablemente su última pelea como profesional en la UFC sería contra el brasileño <b>Lyoto Machida</b> el 30 de abril de 2011, quien con una patada frontal lo dejaría KO, y haría que con casi 48 años, Couture decidiera colgar los guantes.</p>
                    <p className={styles.leyenda__article__text}>Más allá de su vida como peleador profesional de MMA, tuvo una destacada carrera como actor de hollywood, interpretando papeles secundarios y de extra desde el 2003, y obteniendo un papel importante como miembro del equipo de <b>The Expendables</b> (o Los Indestructibles en español), donde comparte pantalla con estrellas del calibre de <b>Sylvester Stallone</b>, <b>Jason Statham</b> y <b>Dolph Lundgren</b>. Esta debe ser la serie de cintas más destacadas de la que formó parte, teniendo una participación en cada una de las 4 películas, siendo la última estrenada en 2023.</p>
                    <p className={styles.leyenda__article__text}>Respecto a su vida personal, estuvo casado en 3 ocasiones, habiéndose divorciado en cada matrimonio, actualmente se encuentra en pareja con la estrella de televisión <b>Melinda Lynn Robinson</b>. Además tiene 3 hijos, entre ellos uno llamado <b>Ryan Couture</b>, quien también fue peleador profesional de MMA y que llegó a competir en la UFC en 2013, y que ya terminó su carrera, retirándose con un récord de 12-6.</p>
                </article>
                <AsideChamps />
            </section>
        </main>
    )
}