import PeleadoresHero from '@/app/peleadores/components/PeleadoresHero'
import styles from '@/app/peleadores/components/peleador.module.css'
import Image from 'next/image'
import Link from 'next/link'
import raquel from '@/assets/peleadores__images/mujeres/0-10/raquel-pennington/raquel.png'
import fight from '@/assets/peleadores__images/mujeres/0-10/raquel-pennington/raquel_fight.jpg'
import pennington from '@/assets/peleadores__images/mujeres/0-10/raquel-pennington/raquel_penington.jpg'
import AsideFighter from '@/app/components/asides/AsideFighter'
import type { Metadata } from 'next'
import EndArticle from '@/app/components/EndArticle'

export const metadata: Metadata = {
    title: 'Raquel Pennington',
    description: "Raquel Pennington es una luchadora de UFC que compite en la categoría de Peso Gallo femenino desde que hiciera su debut oficial en la compañía el 15 de marzo contra la brasileña Jessica Andrade con quien caería derrotada por decisión dividida, actualmente es la campeona indiscutida de su divsión.",
    openGraph: {
        title: 'Raquel Pennington',
        description: "Raquel Pennington es una luchadora de UFC que compite en la categoría de Peso Gallo femenino desde que hiciera su debut oficial en la compañía el 15 de marzo contra la brasileña Jessica Andrade con quien caería derrotada por decisión dividida, actualmente es la campeona indiscutida de su divsión.",
        url: 'https://fullmma.org/mujeres/raquel-pennington'
    }
}

export default function Raquel () {
    return(
        <main>
            <PeleadoresHero peleadoresImage={raquel} w={16} l={10} d={0} nombre='Raquel Pennington' apodo='ROCKY' categoria='Peso Gallo Femenino' time='2025-10-29' />
            <section className={styles.peleador__articles__container}>
                <article className={styles.peleador__article}>
                    <h2 className={styles.peleador__article__title}>Raquel Pennington UFC</h2>  
                    <p className={styles.peleador__article__text}>Raquel Pennington es una luchadora estadounidense de UFC que compite en la categoría de Peso Gallo femenino desde que hiciera su debut oficial en la compañía el 15 de marzo contra la brasileña <b>Jessica Andrade</b> con quien caería derrotada por decisión dividida, actualmente es la campeona indiscutida de su división.</p>
                    <p className={styles.peleador__article__text}>A lo largo de su carrera en la compañía supo destacar de sobremanera, consiguiendo ser campeona de su división en enero de 2024, cuando en el evento co-estelar de <Link href='/covertura-ufc/ufc297'>UFC 297</Link> enfrentando a la brasileña <Link href='/mujeres/mayra-bueno-silva'>Mayra Bueno Silva</Link>, conseguiría ganar por decisión a su rival, quedándose con el Campeonato Vacante de Peso Gallo Femenino. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/bZ3hNy7nS78?si=Md5rL3k2Wp5dSce1" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <h2 className={styles.peleador__article__title}>Raquel Pennington Récord</h2>  
                    <p className={styles.peleador__article__text}>Raquel Pennington cuenta con un récord de 16-10. 16 victorias de las cuales 1 fue por nocaut que consiguió en su debut como profesional en las MMA, 4 por sumisión y 11 por decisión. Además sus 10 derrotas están compuestas por apenas 1 nocaut, 1 por sumisión y 8 por decisión. </p>
                    <h2 className={styles.peleador__article__title}>Raquel Pennington Historia</h2>  
                    <p className={styles.peleador__article__text}>Raquel Pennington nació el 5 de septiembre de 1988 en la ciudad de Colorado Springs, perteneciente al Estado de Colorado de los Estados Unidos. Es de ascendencia mexicana y desde pequeña practicó muchos deportes, como el basquet, el softball, el voley y el cross-country, que es una modalidad del atletismo que consta de recorrer distancias a través del campo. Ya desde muy temprano Raquel estuvo interesada en el mundo del combate, originalmente queriendo ser boxeadora. Se graduó en 2007 del Harrison High School como secretaria del National Honors Society, con varias becas académicas y atléticas.</p>
                    <p className={styles.peleador__article__text}>Comenzó a entrenar artes marciales a la edad de 19 años, y aunque inicialmente sus padres no la dejarían pelear, terminó compitiendo de forma amateur entre 2009 a 2011, periodo en el que ganaría 7 combates (5 por sumisión) y perdería una sola pelea. Su arduó trabajo y entrenamiento la llevaron a ser actualmente cinturón violeta de Jiu-Jitsu brasileño.</p>
                    <Image className={styles.peleador__article__image} loading='lazy' src={pennington} alt='Raquel Pennington en el gimasio con su entrenador' />
                    <p className={styles.peleador__article__text}>Finalmente haría su debut oficial como profesional el día 13 de marzo de 2012 contra <b>Kim Couture</b> a quien vencería por nocaut en el segundo asalto. Pese a su buen debut profesional, lo cierto es que el inicio de la futura campeona de UFC, fue algo irregular, perdiendo su segundo combate por decisión unánime. Y aunque después de aquella derrota ganaría otras 2 peleas, 1 por sumisión y 1 por decisión, perdería las siguientes 2 por los mismo métodos, dejándola luegod e 6 combates con un récord de 3-3. Pese a esto, Pennington tendría la oportunidad de su vida, cuando sería invitada a participar del <b>TUF</b>, el reality de televisión de la UFC.</p>
                    <p className={styles.peleador__article__text}>Raquel fue anunciada como miembro del elenco de <b>The Ultimate Fighter: Team Rousey vs. Team Tate Finale</b>, donde compitió avanzando de ronda hasta llegar a enfrentarse en la semifinal a la excampeona de boxeo <b>Jessica Rakoczy</b>, a quien enfrentó a pesar de estar con una lesión en la mano, perdiendo el combate por decisión.</p>
                    <p className={styles.peleador__article__text}>Terminaría por hacer su debut promocional contra quie fue su compañera de equipo de TUF 18, <b>Roxanne Modafferi</b> a quien vencería por decisión unánime el 30 de noviembre de 2013. Y haría su debut en una cartelera en UFC 171, entraría en reemplazo de <Link href='/mujeres/julianna-pena'>Julianna Peña</Link> para enfrentarse a <b>Jéssica Andrade</b>, con quien perdería por decisión dividida. De igual manera conseguiría reponerse rápido de la derrota, al meses después, someter en el primer asalto a su compatriota <b>Ashlee Evans-Smith</b> en el UFC 181. </p>
                    <p className={styles.peleador__article__text}>En su siguiente pelea, Raquel perdería su combate ante la histórica peleadora femenina <Link href='/mujeres/holly-holm'>Holly Holm</Link>, quien por decisión dividida se llevó la pelea. Sin embargo, luego de esta derrota es cuando comenzaría una racha de 4 victorias consecutivas de Pennington que la llevarían a competir por el título de la división, siendo la primera de estas victorias en su revancha ante <b>Jessica Andrade</b>, a quien logró someter en el segundo asalto, ganando el bono a la actuación de la noche. Las siguientes 3 victorais serían ante <b>Bethe Correia</b>, ante <b>Elizabeth Philips</b> y ante <b>Miesha Tate</b>, todas por decisión.</p>
                    <p className={styles.peleador__article__text}>Con estas 4 victorias consecutivas, y un récord profesional de 9-5, y de 6-2 en UFC, Raquel se ganaría el derecho a pelear por el título de la división el día 12 de mayo de 2018 en el UFC 224, ante la histórica campeona <Link href='/leyendas/amanda-nunes'>Amanda Nunes</Link>, que venía de defender ante <Link href='/leyendas/ronda-rousey'>Ronda Rousey</Link> y ante <Link href='/mujeres/valentina-shevchenko'>Valentina Shevchenko</Link>. Pero para desgracia de nuestra protagonista, llegando al quinto y último asalto, caería noqueada por los golpes de la brasileña. </p>
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/Q_lFlY1d42Y?si=BBY1nkwg5HIeAm0B" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Lamentablemente le costaría un poco reponerse de esta derrota por el campeonato, dado que perdería su siguiente combate ante <b>Germaine de Randamie</b> por decisión unánime, y aunque luego ganaría por decisión dividida ante la mexicana <b>Irene Aldana</b> en julio de 2019, volvería a perder en su revancha contra <b>Holly Holm</b> el 18 de enero de 2020, en el UFC 246.</p>
                    <p className={styles.peleador__article__text}>Pero igual que la última vez, luego de esta derrota, Raquel volvería más fuerte y acumularía una importante racha de victorias, ganando sus siguientes 5 combates, ante <b>Marion Reneau</b> y <b>Pannie Kianzad</b> por decisión, ante su compatriota <b>Macy Chiasson</b> en diciembre de 2021, consiguiendo someter con una guillotina a su rival en una pelea realizada en peso pluma, y ante <b>Aspen Ladd</b> y <b>Ketlen Vieira</b> por decisión. </p>
                    <p className={styles.peleador__article__text}>Esta importante racha de victorias, le abrirían la oportunidad de, nuevamente, pelear por el título de la división, que luego del retiro de las MMA de Amanda Nunes había quedado vacante. De esta forma, se programó un combate entre Raquel Pennington y <Link href='/mujeres/mayra-bueno-silva'>Mayra Bueno Silva</Link> para el <Link href='/covertura-ufc/ufc297'>UFC 297</Link> organizado el 20 de enero de 2024 (con la pelea entre <Link href='/peleadores/sean-strickland'>Sean Strickland</Link> y <Link href='/peleadores/du-plessis'>Dricus Du Plessis</Link> como evento estelar).</p>
                    <p className={styles.peleador__article__text}>Finalmente, la pelea organizada en Canadá se extendería hasta los 5 asaltos, terminando con Raquel Pennigton siendo elegida como la ganadora por decisión unánime, convirtiéndose en la nueva campeona de la división de peso gallo femenino.</p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/CYiyIWA4gJs?si=b8YSzrAaHUIKxgU0" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Se programaría la primera defensa del título de la estadounidense para el 5 de octubre de 2024 en el <Link href='/covertura-ufc/ufc307'>UFC 307</Link>, ante la excampeona y #1 del ranking, <Link href='/mujeres/julianna-pena'>Julianna Peña</Link>, quien había peleado por última vez en 2022, perdiendo ante Amanda Nunes. Finalmente el combate se extendería hasta los 5 asaltos, y cuando llegó a la decisión de los jueces, dieron como ganadaro a Julianna Peña por decisión dividida, en lo que fue una pelea cerrada que terminó con la perdida del cinturón de nuestra protagonista, y en la primera derrota en UFC desde enero de 2020. </p>
                    <EndArticle />
                </article>
                {/* <AsideFighter /> */}
            </section>
        </main>
    )
}