import PeleadoresHero from '@/app/peleadores/components/PeleadoresHero'
import styles from '@/app/peleadores/components/peleador.module.css'
import Link from 'next/link'
import Image from 'next/image'
import vera from '@/assets/peleadores__images/0-100/0-10/chito-vera/chito_vera.png'
import AsideChamps from '@/app/components/asides/AsideChamps'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Marlon Vera',
    description: "Marlon 'Chito' Vera, es un peleador ecuatoriano de MMA que compite en la División de Peso Gallo de la UFC desde el 15 de noviembre de 2015, cuando haría su debut enfrentando al mexicano Marco Beltrán, donde caería derrotado por decisión. Sin embargo, desde entonces supo convertirse en un peleador importante de la compañía, llegando a disputar el cinturón de la división en una ocasión, cuando enfrentaría al estadounidense Sean O'Malley en marzo de 2024 en el UFC 299.",
    openGraph: {
        title: 'Marlon Vera',
        description: "Marlon 'Chito' Vera, es un peleador ecuatoriano de MMA que compite en la División de Peso Gallo de la UFC desde el 15 de noviembre de 2015, cuando haría su debut enfrentando al mexicano Marco Beltrán, donde caería derrotado por decisión. Sin embargo, desde entonces supo convertirse en un peleador importante de la compañía, llegando a disputar el cinturón de la división en una ocasión, cuando enfrentaría al estadounidense Sean O'Malley en marzo de 2024 en el UFC 299.",
        url: 'https://fullmma.org/peleadores/marlon-vera'
    }
}

export default function Chito () {
    return(
        <main>
            <PeleadoresHero peleadoresImage={vera} w={23} l={10} d={1} nombre='Marlon Vera' apodo='CHITO' categoria='Peso Gallo' />
            <section className={styles.peleador__articles__container}>
                <article className={styles.peleador__article}>
                    <h2 className={styles.peleador__article__title}>Chito Vera UFC</h2>
                    <p className={styles.peleador__article__text}>Marlon &quot;Chito&quot; Vera, es un peleador ecuatoriano de MMA que compite en la División de Peso Gallo de la <Link href='/articulos/ufc'>UFC</Link> desde el 15 de noviembre de 2015, cuando haría su debut enfrentando al mexicano <b>Marco Beltrán</b>, donde caería derrotado por decisión. </p>
                    <p className={styles.peleador__article__text}>Es uno de los peleadores más importantes de la división de peso gallo de la UFC, y es de los mayores representantes de latinoamérica que hay. De él siempre se ha destacado una particularidad a tener en cuenta para quienes lo enfrentan, y es que a pesar de haberse enfrentando varios de los mejores luchadores en su peso de la historia, jamás en sus más de 30 peleas pudieron noquearlo ni someterlo, por lo que hasta el momento, sólo ha perdido por la vía de la decisión. Esta estadística habla muy bien de la capacidad de aguante que tiene el ecuatoriano. </p>
                    <p className={styles.peleador__article__text}>Supo convertirse en un peleador importante de la compañía, llegando a disputar el cinturón de la división en una ocasión, cuando enfrentaría al estadounidense <Link href='/peleadores/sean-omalley'>Sean O&apos;Malley</Link> en marzo de 2024 en el <Link href='/covertura-ufc/ufc299'>UFC 299</Link>, donde lamentablemente no sería capaz de alcanzar su objetivo, dado que caería derrotado por decisión. </p>
                    <h2 className={styles.peleador__article__title}>Marlon Vera Récord</h2>
                    <p className={styles.peleador__article__text}>Marlon Vera cuenta con un récord de MMA profesional de 23-10-1. Siendo 8 de sus victorias por la vía del nocaut, 10 por sumisión y sólo 5 por decisión. Mientras que todas sus 10 derrotas fueron por decisión. También tiene un empate llegó en su enfrentamiento contra el brasileño <b>Fábio Bispo</b> con quien peleó en Lima, Perú.</p>
                    <h2 className={styles.peleador__article__title}>Marlon Vera Historia</h2>
                    <p className={styles.peleador__article__text}>Marlon vera nació ek 2 de diciembre de 1992 en la ciudad ecuatoriana de Chone, ubicada en la provincia de Manabí. Desde joven se confesó como un admirador de <Link href='/leyendas/george-st-pierre'>George St-Pierre</Link>, comenzando a entrenar artes marciales mixtas a los 16 años de la mano de su maestro <b>Frank Vidal</b> en Guayaquil, con quien aprendió tecnicas de Jiu-Jitsu, Muay Thai y boxeo. Chito acabaría ganandose el cinturón negro de jiu-jitsu brasileño en 2015.</p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/Pm8op4Dn9mo?si=BhbJkYhg5re8Gh4v" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Vera haría su debut profesional como luchador el día 24 de julio de 2010, cuando se enfrentaría a su compatriota <b>Romel Orosco</b>, a quien sería capaz de derrotar por sumisión en el segundo asalto. El inicio de su carrera seguiría en la línea de esta victoria, dado que el ecuatoriano sería capaz de ganar los primeros 7 combates de su carrera en un lapso de 3 años, ganando 5 de sus combates por la vía de la sumisión, sólo 1 por decisión y 1 por la vía del KO ante el peruano <b>Joel Iglesias</b> en abril de 2013. </p>
                    <p className={styles.peleador__article__text}>En su octavo combate con fecha para el 29 de junio de 2013 se enfrentaría al brasileño <b>Fábio Bispo</b>, contra quien, en un combate que se extendería hasta los 3 asaltos, terminaría por empatar dicha pelea. En su siguiente pelea ante el brasileño <b>Bruno Leandro Lobato</b>, contra quien perdería por decisión unánime en lo que sería su primera derrota de su carrera. </p>
                    <p className={styles.peleador__article__text}>En la última pelea de ese 2013 se enfrentaría al estadounidense <b>D&apos;Juan Owens</b>, a quien lograría someter en el primer asalto. De esta manera, con un récord de 8-1-1, se ganaría la oportunidad de participar en el reality de televisión de la UFC <b>The Ultimate Fighter</b> en el año 2014. En este reality, en su edición hecha en Latinoamérica, formaría parte del equipo de <b>Werdum</b>, donde conseguiría destacar ganando su primer combate ante el experimentado <b>Henry Briones</b>, a quien conseguiría noquear, para avanzar a las semifinales del torneo. Lamentablemente, no podría seguir participando del dicho torneo debido a un problema de piel que le impediría seguir compitiendo, teniendo que ser reemplazado por el argentino <b>Guido Cannetti</b>. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/w9onHo3NBPQ?si=Rs-pOqEY2QeQbrnO" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Pese a no poder seguir compitiendo en el TUF, Marlon Vera se ganaría un contrato con la UFC, en terminaría por hacer su debut el día 15 de noviembre de 2014 ante el peleador mexicano <b>Marco Beltrán</b>, contra quien perdería por decisión unánime. De igual forma, en la única pelea que tendría el año siguiente en 2015, lograría derrotar por sumisión en el segundo asalto al estadounidense <b>Roman Salazar</b>, en una actuación que le haría ganar el primer bono de su carrera a la Actuación de la Noche. </p>
                    <p className={styles.peleador__article__text}>En el año 2016 tendría 2 combates más, siendo el primero el 27 de febrero ante el inglés <b>Davey Grant</b>, contra quien tristemente caería derrotado por decisión unánime. De igual manera, en su segundo combate del año con fecha para el 27 de noviembre ante el luchador chino <b>Ning Guangyou</b>, en una pelea en peso pluma donde el ecuatoriano lograría hacerse con la victoria por decisión unánime. </p>
                    <p className={styles.peleador__article__text}>En el año 2017 sería más activo peleando en 3 ocasiones diferentes. Siendo la primera de estas peleas el 18 de marzo ante el inglés <b>Brad Pickett</b>, logrando una espectacular victoria por TKO en el tercer asalto luego de conectar una patada en la cabeza que derrumbaría a su rival, ganando por esto el bono a la Actuación de la Noche. Su siguiente pelea sería el 22 de junio ante el estadounidense <b>Brian Kelleher</b>, a quien sometería en el primer asalto de la pelea. La última pelea del año la tendría el 22 de julio, enfrentando al brasileño <b>John Lineker</b>, con quien caería derrotado por decisión unánime. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/a-9N9BvBn1A?si=rONqrcH_GmU9-tBd" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>A lo largo del 2018 pelearía nuevamente en 3 ocasiones diferentes. Comenzando con una derrota por decisión ante el brasileño <b>Douglas Silva de Andrade</b>, el 3 de febrero. Su siguiente pelea sin embargo, lo traería de vuelta al camino de la victoria, cuadno el 4 de agosto en el UFC 227 conseguiría noquear en el segundo asalto al chino <b>Wuliji Buren</b>. Por último, el 17 de noviembre participaría del evento de UFC en Argentina, enfrentando al argentino <b>Guido Cannetti</b>, a quien lograría someter en el segundo asalto de la pelea. </p>
                    <p className={styles.peleador__article__text}>Continuaría con esta racha activa de peleas, subiéndose al octágono en 3 ocasiones diferentes a lo largo del 2019. La primera de estas peleas la tendría el 23 de marzo, enfrentando al luchador americano <b>Frankie Saenz</b>, a quien lograría derrotar por TKO en el primer asalto de la pelea. El 6 de julio en el UFC 239 se enfrentaría a <b>Nohelin Hernández</b>, a quien lograría vencer por sumisión en el segundo asalto de la pelea. Finalmente, el 12 de octubre de se enfrentarí a <b>Andre Ewell</b>, consiguiendo una meritoria victoria por TKO en el tercer asalto, ganando por este desempeño el bono a la Actuación de la Noche. </p>
                    <p className={styles.peleador__article__text}>El 16 de mayo de 2020 se enfrentaría al luchador chino <b>Song Yadong</b> en peso pluma, en un combate que se extendería hasta el tercer asalto y que tristemente perdería por decisión unánime, aunque dicho combate le serviría al ecuatoriano para ganar el bono a La Pelea de la Noche. Unos meses después, el 15 de agosto de ese mismo año en el UFC 252, se enfrentaría al luchador estadounidense que entonces estaba invicto <Link href='/peleadores/sean-omalley'>Sean O&apos;Malley</Link>, a quien lograría quitarle dicho invicto, al derrotarlo por TKO en el primer asalto, con la peculiaridad de que en dicho combate Sean se lesionó la pierna, que de cierta forma terminaría influyendo en el resultado de la pelea. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/vgCrVNa3MQQ?si=nqtoS5ez5FzjV4Qr" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>El 19 de diciembre de ese mismo 2020, se enfrentaría a una leyenda viviente de este deporte, que hizo historia especialmente en la categoría de peso pluma, <Link href='/leyendas/jose-aldo'>José Aldo</Link>, con quien tendría un combate que se extendería hasta los 3 asaltos, cayendo por decisión unánime. </p>
                    <p className={styles.peleador__article__text}>En el 2021 tendría 2 grandes peleas que lo harían ir ascendiendo en la división. Enfrentando primero en una revancha al inglés <b>Davey Grant</b>, que como mencionamos antes, lo había derrotado en su primer combate, consiguiendo Chito Vera esta vez dar vuelta la historia al derrotarlo por decisión unánime, en la que sería elegida como La Pelea de la Noche. Por último, el 6 de noviembre en el UFC 268 se enfrentaría al histórico <b>Frankie Edgard</b>, a quien lograría derrotar en el tercer asalto por KO, luego de conectar una muy buena patada frontal que le haría ganar el bono a la Actuación de la Noche.</p>
                    <p className={styles.peleador__article__text}>En el año 2022 tendría otros 2 muy meritorios combates. Encabezando por primera vez un evento de UFC al enfrentar el día 20 de abril al estadounidense <b>Rob Font</b>, en un combate que se extendería hasta los 5 asaltos, y que nuestro protagonista sería capaz de ganar por deisión unánime. Además, por el espectáculo dado, ganaría nuevamente el bono a La Pelea de la Noche. </p>
                    <p className={styles.peleador__article__text}>El 13 de agosto de ese año volvería a protagonizar una cartelera de UFC, enfrentando en esta ocasión al histórico excampeón de la división <b>Dominick Cruz</b>, a quien en el cuarto asalto de la pelea, sería capaz de dejar KO con una patada en la cabeza que lo tumbaría al suelo. Por el desempeño dado nuevamente, ganaría el bono a la Actuación de la Noche. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/Nfz2dGBNBqo?si=gLpbs0R7D-KGCffU" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>En el 2023 pelearía en 2 ocasiones diferentes. Siendo la primera de estas ocasiones para enfrentar al estadounidense <b>Cory Sandhagen</b> el 25 de marzo, en una cartelera que nuevamente encabezaría. La pelea acabaría luego de 5 asaltos, teniendo que ir a la tarjeta de los jueces que por decisión dividida darían la victoria a Sandhagen. </p>
                    <p className={styles.peleador__article__text}>El 19 de agosto en el UFC 292 volvería a pelear para enfrentarse al brasileño <b>Pedro Munhoz</b>, a quien luego de 3 asaltos derrotaría por decisión unánime. </p>
                    <p className={styles.peleador__article__text}>En aquel UFC 292, sería cuando la división de peso gallo, en la que compite nuestro protagonista, coronaría como nuevo campeón al estadounidense <Link href='/peleadores/sean-omalley'>Sean O&apos;Malley</Link>, cuya única derrota sufrida había sido ante el mismo Marlon Vera. Debido a esto, es que al luchador ecuatoriano se le presentaría la oportunidad de discutirle el título al nuevo campeón, enfrentándolo el 9 de marzo de 2024 en el <Link href='/covertura-ufc/ufc299'>UFC 299</Link>, donde lastimosamente no sería capaz de coronar, cayendo derrotado por decisión unánime luego de 5 asaltos. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/YfppyiyE-Kk?si=NN5YLy1ub7LsoDs8" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Ese mismo año volvería a pelear el 3 de agosto en el <Link href='/covertura-ufc/fight-night-sandhagen-nurmagomedov'>UFC on ABC: Sandhagen vs. Nurmagomedov</Link>, para luchar ante le brasileño excampeón de peso paja <b>Deiveson Figueiredo</b>, con quien nuevamente caería derrotado por decisión unánime. </p>
                </article>
                <AsideChamps />
            </section>
        </main>
    )
}