import PeleadoresHero from '@/app/peleadores/components/PeleadoresHero'
import valentina from '@/assets/peleadores__images/mujeres/0-10/valentina-shevchenko/shevchenko.png'
import sparring from '@/assets/peleadores__images/mujeres/0-10/valentina-shevchenko/sparring.jpg'
import styles from '@/app/peleadores/components/peleador.module.css'
import Link from 'next/link'
import Image from 'next/image'
import AsideFighter from '@/app/components/asides/AsideFighter'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Valentina Shevchenko',
    description: "Valentina es una peleadora de MMA que compite en la UFC, donde pelea desde diciembre de 2015, cuando haría su debut derrotando a la canadiense Sarah Kaufman por decisión dividida, nacionalizada peruana, es la actual campeona de la división de peso mosca femenino.",
    openGraph: {
        title: 'Valentina Shevchenko',
        description: "Valentina es una peleadora de MMA que compite en la UFC, donde pelea desde diciembre de 2015, cuando haría su debut derrotando a la canadiense Sarah Kaufman por decisión dividida, nacionalizada peruana, es la actual campeona de la división de peso mosca femenino.",
        url: 'https://fullmma.org/mujeres/valentina-shevchenko'
    }
}

export default function Valentina () {
    return(
        <main>
            <PeleadoresHero peleadoresImage={valentina} w={23} l={4} d={1} nombre='Valentina Shevchenko' apodo='BULLET' categoria='Peso Mosca Femenino' />
            <section className={styles.peleador__articles__container}>
                <article className={styles.peleador__article}>
                    <h2 className={styles.peleador__article__title}>Valentina Shevchenko UFC</h2>
                    <p className={styles.peleador__article__text}>Valentina es una peleadora de MMA que compite en la <Link href='/articulos/ufc'>UFC</Link>, donde pelea desde diciembre de 2015, cuando haría su debut derrotando a la canadiense <b>Sarah Kaufman</b> por decisión dividida, nacionalizada peruana, es la actual campeona de la división de peso mosca femenino.</p>
                    <h2 className={styles.peleador__article__title}>Valentina Shevchenko Récord</h2>
                    <p className={styles.peleador__article__text}>Valentina Shevchenko tiene un récord de 24-4-1. Siendo 8 de sus 23 victorias por la vía del nocaut, 7 por sumisión, y 9 por decisión. Mientras que de sus 4 derrotas 1 fue por la vía del nocaut, 2 por decisión y 1 una por sumisión. Y su único empate fue en la pelea contra <Link href='/mujeres/alexa-grasso'>Alexa Grasso</Link> en la revancha por el título el 16 de septiembre de 2023.</p>
                    <h2 className={styles.peleador__article__title}>Valentina Shevchenko ¿por qué es peruana?</h2>
                    <p className={styles.peleador__article__text}>Originalmente, Valentina Shevchenko nació en Kirguistán o Kirguizistán, cuando esta todavía conformaba la hoy disuelta Unión Soviética. Pero en un viaje que hizó como turista junto a su hermana y su cuñado a Perú, en donde dió un seminario sobre Muay Thai, invitada por el peruano <b>Frank Paredes</b> quien es muy conocido en este deporte, quedó enamorada del país.</p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/TdbqwyqWlM0?si=VwT4iRCalMbeOLvS" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>A tal punto llegó su amor por Perú que decidió quedarse a vivir ahí. Comenzando incluso a realizar los trámites para nacionalizarse peruana. Cuando Shevchenko tuvo que describir cómo había sido su estancia en el país sudamericano, dijo: <b>&quot;la comida es rica, los paisajes son hermosos y la gente es cálida&quot;</b>. A esto hay que agragarle que a Valentina le encanta entrenar en exteriores, por lo que Perú tenía mucho que ofrecerle, dado que tiene lo necesario para subir a las montañas y prepararse en la altura, o bajar al nivel del mar para entrenar en función de a quién se tenga que enfrentar.</p>
                    <h2 className={styles.peleador__article__title}>Valentina Shevchenko Historia</h2>
                    <p className={styles.peleador__article__text}><b>Valentina Anatolievna Shevchenko</b>, nació el 7 de marzo de 1988 en la ciudad de Biskek, ciudad de Kirguistán, cuando todavía conformaba la Unión Soviética. Desde pequeña parecía tener marcado su destino con los deportes de combate, dado que sus padres le inculcaron tanto a ella como a su hermana Antonina a desarrollarse en el deporte, especialmente su madre quien era experta en Taekwondo y presidente de la federación de este deporte en Kirguistán. </p>
                    <p className={styles.peleador__article__text}>Tanto Valentina como su hermana Antonina, se inclinaron por el Muay Thai, deporte del cual se volvió una completa experta, viajando a pelear varias veces a Tailandia en diversos campeonatos, y sosteniendo un récord de 56-2. En su temprana carrera consiguió diversos logros entre los que destacan sus 5 campeonatos mundiales de Muay Thai, sus 2 campeonatos mundiales de Kickboxing y un campeonato mundial de valetodo.</p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/3iKdQK4NTzc?si=zSncTKCWpkFVcPbT" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>En su adultez viajaría a Perú, país del que quedaría completamente enamorada y donde terminaría viviendo, incluso nacionalizandose para poder representar este país en las competencias donde participa. Debido a esto no es raro verla con la bandera peruana cada vez que tiene un combate o enfrentamiento de UFC. </p>
                    <p className={styles.peleador__article__text}>Oficialmente haría su debut profesional en las MMA el 21 de abril de 2003, enfrentando a su compatriota <b>Eliza Aidaralieva</b>, a quien conseguiría derrotar en el segundo asalto de la pelea por TKO. Para finales de ese año volvería a pelear ante la surcoreana <b>Mi Choi Kim</b>, consiguiendo someterla en el primer asalto. En su tercer combate que tuvo lugar en el año 2004, se enfrentaría nuevamente a una compatriota llamada <b>Erkesh Kokoeva</b>, a quien vencería por TKO en el primer asalto de la pelea. </p>
                    <p className={styles.peleador__article__text}>En un viaje a Kazajistán que realizó, se enfrentaría el 21 de marzo de 2005 a la luchadora <b>Alla Iskarenova</b>, a quien sometería en el primer asalto, y al día siguiente volvería a pelear ante <b>Roza Kalieva</b>, a quien de igual forma somtería en el primer asalto. Valentina tendría un par de combates más en la zona euroasiática, siendo el primero de estos ante la surcoreana <b>Kyung Aeh Kim</b>, a quien sometería en el primer asalto; y el segundo de estos combates sería en marzo de 2006 ante la rusa <b>Yulia Nemtsova</b>, a quien lograría someter en el quinto asalto de la pelea, extendiendo su récord a un 7-0.</p>
                    <p className={styles.peleador__article__text}>Shevchenko se tomaría un tiempo de 4 años antes de volver a pelear en MMA, haciendo un regreso el 30 de septiembre de 2010, para enfrentar a la estadounidense <b>Liz Carmouche</b>, quien le propinaría la primer derrota de su carrera, aunque de una forma un tanto llamativa. Puesto que la pelea se detuvo porque Liz, su rival, le lanzó una pata ilegal a nuestra protagonista que le ocasionó un corte que le impidió continuar. De igual manera, Valentina se recuperaría rápido de su derrota e hilaría 4 victorias consecutivas: siendo la primera de estas ante la oriunda de Kazajistán <b>Akjarkyn Baiturbaeva</b>, a quien derrotó por decisión unánime en abril de 2011; la segunda ante la ecuatoriana <b>Priscila Orellana</b> en una pelea organizada por una promotora peruana llamada <b>Fusion Fighting Championship</b>, donde conseguiría por TKO en el primer asalto; la tercera victoria vendría en la misma promotora, esta vez ante la brasileña <b>Hellen Bastos</b>, a quien conseguiría vencer por TKO en el segundo asalto; y por último, en febrero de 2015, conseguiría derrotar por decisión unánime a la estadounidense <b>Jan Finney</b>. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/LDxX2L37Mz0?si=jny9s5dm3YqLIu-s" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Ya con un récord profesional de 11-1, a Valentina se le presentaría la oportunidad de pelear para la compañía de MMA más grande del mundo, haciendo su debut oficial en la UFC el 19 de diciembre de 2015 ante la canandiense <b>Sarah Kaufman</b>, a quien luego de 3 asaltos conseguiría vencer por decisión dividida. </p>
                    <p className={styles.peleador__article__text}>En su segundo combate, que se celebraría el 5 de marzo de 2016, en el histórico <b>UFC 196</b>, que tenía como evento principal la primer pelea entre <Link href='/peleadores/conor-mcgregor'>Conor McGregor</Link> y <Link href='/articulos/nate-diaz-historia'>Nate Diaz</Link>, nuestra protagonista se enfrentaría a la legendaría <Link href='/leyendas/amanda-nunes'>Amanda Nunes</Link>, contra quien caería derrotada luego de 3 asaltos por decisión unánime, siendo esta su segunda derrota profesional y la primer derrota dentro de la compañía. </p>
                    <p className={styles.peleador__article__text}>A pesar de aquella derrota, Shevchenko conseguiría 2 destacables victorias ante 2 peleadoras muy importantes en la historia del peso gallo femenino. Siendo la primera de estas, cuando enfrentaría a la legendaria campeona estadounidense <Link href='/mujeres/holly-holm'>Holly Holm</Link>, en un evento encabezado por ellas 2 que luego de 5 asaltos se lo acabaría llevando Valentina por decisión unánime. Y la segunda victoria la tendría al enfrentar a quien en el futuro se convertiría en campeona, <Link href='/mujeres/julianna-pena'>Julianna Peña</Link>, a quien enfrentó en enero de 2017, consiguiendo someterla en el segundo asalto de la pelea.</p>
                    <p className={styles.peleador__article__text}>Con estas 2 meritorias victorias, a la nacida en Kirguistán se le presentaría la oportunidad de disputar el título de peso gallo, y de vengar su última derrota, al enfrentar a la brasileña entonces campeona <b>Amanda Nunes</b>, contra quien, en una pelea que se extendería hasta los 5 asaltos, terminaría cayendo derrotada por decisión dividida. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/HvSO0kfcv90?si=3b8Pwx1hgGVqKltA" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Aquella derrota en una pelea por el cinturón, llevaría a Valentina a tomar la decisión de moverse de categoría, para comenzar a pelear en la división de Peso Mosca de la UFC, en donde debutaría el 3 de febrero de 2018, enfrentando a la brasileña <b>Priscila Cachoeira</b>, a quien conseguiría someter en el segundo asalto de la pelea. Luego de esta victoria, inmediatamente se le daría la posibilidad de disputar el título vacante de la división ante la polaca e histórica peleadora femenina de la UFC <b>Joanna Jedrzejczyk</b>, el día 8 de diciembre de 2018 en el UFC 231. Aquella noche conseguiría vencer a su rival luego de 5 asaltos por decisión unánime, y comenzaría uno de los reinados más largos en la historia de la UFC. </p>
                    <p className={styles.peleador__article__text}>Tendría 2 defensas del cinturón en el año 2019, siendo la primera de estas ante la estadounidense <b>Jessica Eye</b> en el UFC 238, a quien conseguiría conectarle un KO espectacular en el segundo asalto del combate, que le valdría para ganar el bono a La Actuación de la Noche. Su siguiente defensa sería una revancha de su primer derrota profesional, volviendo a enfrentar a <b>Liz Carmouche</b> en el evento de UFC organizado en Uruguay, esta vez nuestra protagonista conseguiría vengar su derrota, venciendo a su rival por decisión unánime luego de 5 asaltos. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/XGjJmcqunUs?si=wPiYVlB0sjvIxNcr" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Volvería a defender el 8 de febrero de 2020 en el UFC 247, enfrentando a la estaodunidense <b>Katlyn Chookagian</b>, a quien vencería por TKO en el tercer asalto de la pelea. Ese mismo año, el 21 de noviembre, defendería ante la brsileña <b>Jennifer Maia</b>, en lo que ya era su cuarta defensa del título, consiguiendo una victoria por decisión unánime, reteniendo de forma exitosa su cinturón nuevamente.</p>
                    <p className={styles.peleador__article__text}>El 24 de abril de 2021, concretaría su quinta defensa exitosa del título, cuando el UFC 261, enfrentando a la brasileña <b>Jéssica Andrade</b>, conseguiría vencer a esta por TKO en el segundo asalto. </p>
                    <p className={styles.peleador__article__text}>Su sexta defensa del cinturón no sería menos impresionante, logrando en septiembre de ese mismo año, derrotar por TKO a la estadounidense <b>Lauren Murphy</b> en el cuarto asalto de la pelea. </p>
                    <p className={styles.peleador__article__text}>En el 2022 sólo tendría un combate, en el que se vería cara a cara con la la luchadora de Brasil <b>Taila Santos</b>, y en lo que fue una pelea más cerrada que de costumbre, conseguiría llevarse el combate por decisión dividida, concretando de esta manera, su séptima defensa exitosa del título.</p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/inVogRDqpj8?si=i1UA6xRXMcFE9_Be" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Para el 4 de marzo de 2023, se programaría la octava defensa del título de nuestra protagonista, ante la retadora mexicana <Link href='/mujeres/alexa-grasso'>Alexa Grasso</Link>, quien venía acumulando una racha de 4 victorias consecutivas. Aquella noche, sorprendetemente Valentina perdería su cinturón, al ser sometida en tercer asalto de la pelea, siendo esta su primera derrota en más de 5 años, y cortando con el que venía siendo el reinado más largo de la historia del peso mosca femenino. </p>
                    <p className={styles.peleador__article__text}>Como era de esperarse, debido a la excelenta trayectoria de Shevhchenko, se programó una revancha inmediata, aunque esta sería en territorio hostil para nuestra protagonista, puesto que se enfrentarían el 16 de septiembre de 2023, el día de la independencia de México, en un evento encabezado por ellas 2. La pelea entre ambas luchadoras se extendería hasta los 5 asaltos, y cuando la victoria dependía del criterio de los jueces estos declararon un empate dividido, siendo uno de los 3 jueces vió ganar a Shevchenko, otro vió ganar a Grasso, y el tercero declaró un empate, que fue el resultado que terminó quedando. Este resultado le servía a Alexa Grasso para retener el cinturón y dejar sin nada a Valentina.</p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/RhosJSynMFo?si=CF8lx15QwpZegrSZ" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Debido a lo polémico que le pareció el empate a muchos fanáticos, incluidos la misma Valentina que se vió ganadora de la pelea, y que afirmaba que el estar peleando el día de la independencia de México ante una mexicana, influyo en la decisión de los jueces (como cuenta esta nota de <a target='_Blank' href='https://www.infobae.com/mexico/2023/09/18/valentina-shevchenko-relaciona-la-victoria-de-alexa-grasso-con-la-celebracion-del-dia-de-la-independencia/'>Infobae</a>), es que se programó una tercer pelea entre ambas, convirtiéndose la rivalidad entre Alexa Grasso y Valentina Shevchenko, la primera en llegar a una trilogía en la historia de las MMA femeninas en la UFC. </p>
                    <p className={styles.peleador__article__text}>La tercer pelea entre estas luchadoras se daría el 14 de septiembre de 2024 (nuevamente con una proximidad a la fecha festiva de México), en el <Link href='/covertura-ufc/ufc306'>UFC 306</Link>, que contaba con la peculiaridad de ser organizado en <b>La Esfera en Las Vegas</b>. Aquella noche, Valentina se encargaría de dar vuelta la historia, recuperando el cinturón que tantos años le perteneció, al derrotar por decisión unánime a su rival, en lo que fue una actuación muy dominante de su parte, que no dejaban dudas sobre la ganadora del encuentro.</p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/vWRif1_1My8?si=WxUoHbX5iAGNelvW" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                </article>
                <AsideFighter />
            </section>
        </main>
    )
}