import PeleadoresHero from '@/app/peleadores/components/PeleadoresHero'
import chandler from '@/assets/peleadores__images/0-100/10-20/michael-chandler/chandler.png'
import styles from '@/app/peleadores/components/peleador.module.css'
import Link from 'next/link'
import type { Metadata } from 'next'
import dynamic from 'next/dynamic'

const AsideChamps = dynamic(() => import('@/app/components/asides/AsideChamps'))
const EndArticle = dynamic(() => import('@/app/components/EndArticle'))

export const metadata: Metadata = {
    title: 'Michael Chandler',
    description: 'Michael Chandler es un peleador estadounidense de MMA que compite en la división de Peso Ligero de UFC, aunque previamete destacó en su carrera al haber sido campeón en multiples ocasiones en la compañía rival Bellator.',
    openGraph: {
        title: 'Michael Chandler',
        description: 'Michael Chandler es un peleador estadounidense de MMA que compite en la división de Peso Ligero de UFC, aunque previamete destacó en su carrera al haber sido campeón en multiples ocasiones en la compañía rival Bellator.',
        url: 'https://fullmma.org/peleadores/michael-chandler'
    }
}

export default function Chandler () {
    return(
        <main>
            <PeleadoresHero peleadoresImage={chandler} w={23} l={9} d={0} nombre='Michael Chandler' apodo='IRON' categoria='Peso Ligero' />
            <section className={styles.peleador__articles__container}>
                <article className={styles.peleador__article}>
                    <h2 className={styles.peleador__article__title}>Chandler UFC</h2>
                    <p className={styles.peleador__article__text}>Michael Chandler es un peleador estadounidense de MMA que compite en la división de Peso Ligero de <Link href='/articulos/ufc'>UFC</Link>, desde que hiciera su debut el día 24 de enero de 2021 en el UFC 257, ante el luchador de Nueva Zelanda <b>Dan Hooker</b>. </p>
                    <p className={styles.peleador__article__text}>Michael Chandler es uno de esos peleadores que siempre cumple con lo que esperas ver de él, dado que nunca falla a la hora de entregar espectáculo en sus combates, independientemente de si gana o pierde dichas peleas, en parte esto es lo que hace que constantemente lo veamos peleando contra los tops de su división. </p>
                    <p className={styles.peleador__article__text}>Supo destacar en su carrera de MMA al haber sido 3 veces ganador del cinturón de peso ligero de <b>Bellator</b>, donde compitió la mayor parte de su carrera, enfrentando a históricos y grandes rivales como <b>Eddie Alvarez</b> o <b>Benson Henderson</b>. Además, tuvo la oportunidad de disputar el campeonato de la UFC en una ocasión, enfrentando a <Link href='/peleadores/charles-oliveira'>Charles Oliveira</Link>, el día 15 de mayo de 2021 en el UFC 262, aunque terminaría por caer derrotado por TKO en el segundo asalto. </p>
                    <h2 className={styles.peleador__article__title}>Michael Chandler Récord</h2>
                    <p className={styles.peleador__article__text}>Actualmente Michael Chandler tiene un record de 23-9. De sus 23 victorias, 11 fueron por la vía del nocaut, 7 por sumisión y 5 por decisión. Mientras que de sus 8 derrotas, 4 fueron por la vía del nocaut, 4 por decisión y sólo 1 una por sumisión.</p>
                    <h2 className={styles.peleador__article__title}>Michael Chandler Historia</h2>
                    <p className={styles.peleador__article__text}>Michael Chandler Jr. nació el 24 de abril de 1986 en Nashville, Estados Unidos. Es el segundo de 4 hermanos e hijo de Michael Chandler Sr. y de Betty Chandler. Durante su adolescencia peleó como luchador y terminó segundo en el Campeonato de escuelas secundarias del Estado de Misuri.</p>
                    <p className={styles.peleador__article__text}>Luego de graduarse en 2004, Chandler entró a la Universidad de Misuri, donde se unió al equipo de wrestling. Chandler clasificó cuatro veces a la NCAA, consiguiendo 100 victorias en su carrera. Una vez terminada su carrera de wrestling, Michael Chandler comenzó a entrenar MMA por influencia de sus 2 amigos <b>Tyron Woodley</b>, quien luego se convertiría en campeón de peso wélter en la UFC, y <b>Ben Askren</b>, quien se convertiría en campeón de peso wélter en Bellator y ONE Championship. Comenzando a competir de forma profesional el 7 de febrero de 2009, al enfrentar a <b>Josh Flowers</b>, a quien conseguiría derrotar por TKO en el primer asalto. </p>
                    <p className={styles.peleador__article__text}>Tendría 2 combates más durante el 2009 ante <b>Mitchell Harris</b> en abril, a quien sometería en el primer asalto; y ante <b>Matt Delanoit</b> en agosto, a quien de igual forma sometería en el primer asalto de la pelea. Luego de estos 3 combates en 2009 y con un récord de 3-0, Chandler firmaría con <b>Bellator</b>, donde haría la mayor parte de su carrera y donde conseguiría sus mayores logros. De esta forma haría su debut en la compañía el día 15 de mayo de 2010 en el Bellator 31, enfrentando a su compatriota <b>Scott Stapp</b>, a quien lograría derrotar por TKO en el primer asalto de la pelea. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/3UMXEvQiUls?si=uYhaoUSMshqnIY6G" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Tan solo 2 semanas después tendría su siguiente combate en el Bellator 32, enfrentando a <b>Chris Page</b> el 14 de octubre de 2010, consiguiendo mantener su invicto y su racha de victorias por finalización, al ser capaz de somterlo en el primer asalto en el primer minuto del combate. </p>
                    <p className={styles.peleador__article__text}>Durante el año 2011 se mantendría muy activo, peleando en 4 ocasiones. Con la primera de estas peleas teniendo lugar el 12 de marzo, cuando enfrentaría al polaco <b>Marcin Held</b>, a quien sería capaz de someter en el primer asalto de la pelea; el segundo combate lo tendría ante <b>Lloyd Woodard</b>, quien sería el primer en aguantar 3 asaltos ante Chandler, llevando la pelea a la decisión que sería favorable para nuestro protagonista; el tercer combate sería el 14 de mayo ante el brasileño <b>Patricio Freire</b>, a quien vencería por nuevamente por decisión unánime; y por último, la última pelea del año sería hasta ese momento, la más importante de su carrera, contra el futuro campeón de la UFC, <b>Eddie Álvarez</b>, por el cinturón de peso ligero de Bellator, consiguiendo hacerse de este cuando sometió en el cuarto asalto del combate a su rival, siendo campeón por primera vez en la compañía. </p>
                    <p className={styles.peleador__article__text}>En 2012 pelearía sólo una vez, y aunque era campeón su pelea no fue una titular, por lo que su cinturón no estaba en juego. Lo haría el 4 de mayo ante el japonés <b>Akihiro Gono</b> en el Bellator 67, consiguiendo mantener su invicto al noquear en el primer minuto a su rival, extendiendo su récord a 10-0. </p>
                    <p className={styles.peleador__article__text}>Recién en el año 2013 tendría su primer defensa del cinturón, iniciando con <b>Rick Hawn</b>, a quien enfrentaría el 17 de enero, consiguiendo someterlo en segundo asalto de la pelea, concretando una primera defensa exitosa del título. </p>
                    <p className={styles.peleador__article__text}>El 31 de julio de ese año se defendería por segunda vez ante <b>David Rickels</b> en el Bellator 97, consiguiendo nuevamente una impresionante victoria por KO en el primer asalto de la pelea, de nuevo, antes de que termine el primer minuto del encuentro. Para su tercer defensa se programaría una revancha ante <b>Eddie Álvarez</b> para el día 2 de noviembre de 2013, con una pelea que en esta ocasión se extendería hasta los 5 asaltos, llegando a la decisión de los jueces que darían como vencedor a Álvarez por decisión dividida. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/BzF1FVI3oUE?si=vaWTS0Q07J0j6NMU" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>De forma inmediata, se lo pondría a pelear por el Campeonato interino de Bellator, enfrentando para esto a <b>Will Brooks</b> el 17 de mayo de 2014, aunque lamentablemente para nuestro protagonista caería derrotado por decisión dividida. </p>
                    <p className={styles.peleador__article__text}>Aunque debido a que luego de su pelea con Chandler, Eddie Álvarez había abandonado la compañía para ir a pelear en UFC, el cinturón de peso ligero quedaría vacante, por lo que se le programaría una revancha ante Will Brocks para disputar el cinturón ahora sin dueño. La pelea tendría lugar el 15 de noviembre y desafortunadamente nuestro protagonista volvería a caer derrotado, esta vez por TKO en el cuarto asalto. </p>
                    <p className={styles.peleador__article__text}>Si quería volver a pelear por el título, Chandler debía volver a la senda de la victoria, por eso aceptaría pelear en el Bellator 138, organizado el 19 de junio de 2015 ante <b>Derek Campos</b>, contra quien conseguiría volver a ganar, al somterlo en el primer asalto de la pelea. Ese mismo año, el 6 de noviembre, volvería a pelear para enfrentar a <b>David Rickels</b>, a quien conseguiría vencer por TKO en el segundo asalto del combate. </p>
                    <p className={styles.peleador__article__text}>Con 2 victorias seguidas, se lo pondría a pelear nuevamente por el cinturón, enfrentando para esto al brasileño <b>Patricky Freire</b> en el Bellator 157, donde lograría recuperar su cinturón al dejar KO a su rival en el primer asalto de la pelea. </p>
                    <p className={styles.peleador__article__text}>Michael Chandler volverái a defender en noviembre de ese mismo año, enfrentando para eso al excampeón de UFC, histórico de las 155lbs, <b>Benson Henderson</b>, a quien luego de finalizados los 5 asaltos de la pelea, le ganaría por decisión dividida. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/K50CfyCAlzM?si=GBvHQqali5K8FcBf" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Su segunda defensa la tendría el 24 de junio de 2017 ante el estadounidense <b>Brent Primus</b> en el Bellator NYC, donde lamentablemente caería derrotado por parada médica a los 2 minutos del primer asalto, luego de que se lesionara el tobilla de manera completamente accidental, perdiendo de esta forma su cinturón. </p>
                    <p className={styles.peleador__article__text}>Michael Chandler debería pelear en enero de 2018 ante el japonés <b>Goiti Yamauchi</b>, contra quien lograría una victoria por decisión unánime. La segunda pelea del año la tendría el 13 de abril, cuando enfrentaría a <b>Brandon Girtz</b>, a quien sometería con un triángulo de brazo en el primer asalto de la pelea. Finalmente su última pelea del año sería el 14 de diciembre en la revancha contra <b>Brent Primus</b>, nuevamente por el cinturón de las 155lbs, consiguiendo esta vez derrotarlo por decisión unánime, convirtiéndose en 3 veces campeón de peso ligero en Bellator. </p>
                    <p className={styles.peleador__article__text}>Desgraciadamente en este tercer campeonato no sería capaz de defender exitosamente su título, dado que ya en su siguiente combate con fecha para el 11 de mayo de 2019, caería derrotado por TKO en el primer asalto ante el brasileño <b>Patrício Freire</b>. </p>
                    <p className={styles.peleador__article__text}>Con esta derrota, Chandler sólo tendría 2 combates más en la compañía, siendo estos ante el estadounidense <b>Sidney Outlaw</b>, a quien derrotó por KO en el primer asalto de la pelea; y una revancha ante <b>Benson Henderson</b>, que esta vez no se extendería hasta la decisión de los jueces, y por el contrario acabaría con una victoria por KO a favor de nuestro protagonista. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/M013rAjdM3s?si=671naQzrJZIVxLwK" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <h3>Michael Chandler en la UFC</h3>
                    <p className={styles.peleador__article__text}>Con un récord acumulado de 21-5, habiendo sido campeón de Bellator en 3 ocasiones, y habiendo defendido el título varias veces, con victorias espectaculares, incluso ante futuros o pasados campeones de UFC, a Chandler no le quedaba ningún reto por cumplir en la compañía, por lo que con 34 años cambiaría de compañía, firmando finalmente con la UFC. </p>
                    <p className={styles.peleador__article__text}>Su debut oficial lo haría enfrentando al luchador de Nueva Zelanda, ranqueado #6 en el aquel momento, <b>Dan Hooker</b>, a quien enfrentaría el 24 de enero de 2021 en el UFC 257, donde conseguiría una nueva victoria por la vía del nocaut en el primer asalto de la pelea, ganando el primer bono de su carrera a La Actuación de la Noche. </p>
                    <p className={styles.peleador__article__text}>De esta forma se ganaría el derecho a pelear por el Campeonato Vacante de Peso Ligero de la UFC, que luego del retiro de <Link href='/leyendas/khabib-nurmagomedov'>Khabib Nurmagomedov</Link> había quedado sin dueño. Para esto, debería enfrentar el 15 de mayo de 2021 en el UFC 262, al brasileño <Link href='/peleadores/charles-oliveira'>Charles Oliveira</Link>, contra quien lamentablemente para él, caería derrotado por TKO en el segundo de la pelea. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/Z-B99m_jqJs?si=hlnQ8rzQXN6Y8YmI" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>En su siguiente combate que tuvo lugar en noviembre en el UFC 268, nos volvería a dar un espectáculo, enfrentando en la tercera pelea del año a <Link href='/peleadores/justin-gaethje'>Justin Gaethje</Link>, en un combate muy reñido que se extendería hasta los 3 asaltos, sería su rival Geathje quien se quedaría con la victoria por decisión unánime. Pero pese a perder, hizo meritos suficientes para ganar el bono a la Pelea de la Noche. </p>
                    <p className={styles.peleador__article__text}>Volvería a la senda de la victoria en el año 2022, dado que se le programaría una pelea para el 7 de mayo de 2022, para luchar en el UFC 274 ante una de las leyendas de la división <Link href='/peleadores/tony-ferguson'>Tony Ferguson</Link>, a quien en el segundo asalto de la pelea sería capaz de conectar una sorprendente patada frontal que dejaría KO al instante a su rival, ganando por tremendo desempeño nuevamente el bono a la Actuación de la Noche. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/Boa0BC_AA_s?si=I2TjtFIxARfD8PF6" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Pelearía una vez en el año 2022, enfrentando a otro estadounidense en el UFC 281, organizado el 12 de noviembre, compartiendo la cartelera estelar con <Link href='/peleadores/dustin-poirier'>Dustin Poirier</Link>, en un combate en el que ambos es conectaron muy buenos golpes, pero en el que pese a llegar al tercer asalto, terminaría en el momento que Poirier fuera capaz de finalizar a nuestro protagonista con un mataleón. De igual forma y pese a perder, volvería a ganar un bono a la Pelea de la Noche. </p>
                    <EndArticle />
                </article>
                <AsideChamps />
            </section>
        </main>
    )
}