import Link from 'next/link'
import PromotorasHero from '../PromotorasHero'
import styles from '../promo.module.css'

export default function One () {
    return(
        <main>
            <PromotorasHero title='One Championship' />
            <section className={styles.promotoras__container}>
                <article className={styles.promotoras__article}>
                    <h2 className={styles.promotoras__article__title}>MMA One</h2>
                    <p className={styles.promotoras__article__text}>One Cahmpionship (antes llamada One Fighting Championship), es una empresa de combate fundada el 14 de julio de 2011 por el empresario <b>Chatri Sityodtong</b> y el exejecutivo en jefe de ESPN Star Sports Victor Cui. Con sede en Singapur, además de ofrecer peleas de MMA, también organizan combates de <b>submission grappling</b>, <b>Kickboxing</b>, <b>Muay Thai</b> y peleas de <b>Lethwei</b>. Esta empresa tuvo un rápido crecimiento y expansión alrededor del mundo, distrubuyendo su contenido a más de 150 países y convirtiendose en una empresa cotizada en más de mil millones de dólares en 2018.</p>
                    <p className={styles.promotoras__article__text}>Su primer evento fue celebrado el 3 de septiembre de 2011 en el Estadio Cubierto de Singapur, que tiene una capacidad para 12000 espectadores, con el nombre de &quot;ONE Fighting Championship: Champion vs. Champion&quot;. Unos meses más tarde, la empresa firmaría con ESPN Star Sports un acuerdo importante para la retransmisión de sus eventos durante los próximos 10 años. De esta forma durante todo 2012 continuaron organizando eventos en diferentes localidades como las de Kuala Lumpur, Yakarta, Ciudad Quezón o la misma Singapur.</p>
                    <p className={styles.promotoras__article__text}>Con el paso del tiempo, figuras importantes se fueron sumando a la organización de la empresa, como es el caso del excampeón de Peso Mediano de la <Link href='/promotoras/ufc'>UFC</Link>, quien en 2014 fue nombrado vicepresidente de la empresa, o como es el caso del en su momento campeón del Peso Welter de boxeo, Manny Pacquiao, que también en 2014 compró un número no revelado de acciones, pero que a nivel mediático repercutió de forma positiva para la compañía. </p>
                    <p className={styles.promotoras__article__text}>La organización cambiaría su nombre en enero de 2015, recortándolo de &quot;ONE Fighting Championship&quot; a &quot;ONE Championship&quot;, en un momento de renovación donde buscaban cerrar nuevos patrocinadores, que se cree que no estaban convencidos de asociarse con una organización que tuviera la palabra &quot;fighting&quot; en la marca. Aunque uno de sus fundadores, Victor Cui afirmó que el cambio de nombre se debía principalmente por razones linguisticas y culturales, dado que en aquel momento estaban apostando por organizar eventos en China.</p>
                    <p className={styles.promotoras__article__text}>A lo largo de su historia, ha contado con figuras mediáticas en el mundo de las artes marciales mixtas, como lo son Bob Sapp, Rolles Gracie, Tim Sylvia, Andrei Arlovski, Bibiano Fernandes, Melvin Manhoef, Shinya Aoki o <b>Dimitrus Johnson</b>.</p>
                    <p>Los combates de One Championship hacen uso del <b>Reglamento de Rates Marciales Global</b>, que combina lo mejor de las prácticas de Asia y lo mejor de las no asiáticas. La duración de dichas peleas varía en caso de tratarse de un combate por el cameponato o no, siendo de 3 asaltos los combates regulares y de 5 los combates por el campeonato, aunque ningún asalto pasa de los 5 minutos independientemente de esto. </p>
                    <p className={styles.promotoras__article__text}>La victoria se consigue en favor del combatiente que logre, noquear o someter al rival, esto incluyendo los nocauts ténicos por parada del referi y las sumisiones verbales. En caso de que pasados los asaltos ninguna de estas cosas se consiga, la victoria pasa por la decisión de los jueces, quienes juzgan la pelea por completo y no asalto por asalto como en otras compañías, utilizando los siguientes criterios: estar cerca del nocaut o de la sumisión, daño (interno, acumulado, superficial), combinaciones de golpes y control de la jaula (control en el suelo, superioridad de posición), derribos conseguidos o defensa de derribos y agresiones.</p>
                    <p className={styles.promotoras__article__text}>Se considera que son ilegales los golpes a la ingle, la garganta, tráquea, nuca, cuello o columna. Tampoco están permitidos los pistones a la cabeza de un rival derribado, la manipulación de las articulaciones pequeñas, los cabezazos, tirar del pelo, los piquetes en los ojos, la inserción en orificios, escupir, ni agarrar la reja de la jaula. Las soccer kicks, es decir, las patas en la cabeza de un rival que está derribado, en un principio estaban permitidas si es que el peleador pedía permiso antes al referí, pero se terminaron por prohibir en 2016 con la intención de seguir expandiendo a nivel mundial la compañía, dado que pese a que hay estudios que dicen que estas patadas generan la misma fuerza que si se pateara a un oponente de pie, está técnica podía generar mala publicidad a la empresa.</p>
                    <h3>Submission Grappling</h3>
                    <p className={styles.promotoras__article__text}>En mayo de 2017, se introdujo por primera vez una &quot;súper pelea de grappling&quot; emtre <b>Shinya Aoki</b> y <b>Garry Tonon</b> con reglas de sólo sumisión. Poco después se anunciaría otra entre <b>Eddie Bravo</b> y <b>Kazushi Sakuraba</b>. Desde entonces ocacionalmente se organizan este tipo de combates en los eventos de ONE Championship.</p>
                    <p className={styles.promotoras__article__text}>Inicialmente estos combates estaban programados para durar 12 mintos y sólo se podían ganar por sumisión, si luego de ese tiempo ninguno de los peleadores era capaz de someter al otro, el combate terminaba en empate. Esto fue cambiado el 18 de abril de 2022, acortando el tiempo a 10 minutos y permitiendo que en caso de que ninguno sometiera a su rival, se pudiera ganar basandosé en el <b>número de intentos genuinos de sumisión</b>.</p>
                    <h2 className={styles.promotoras__article__title}>ONE Warrior Series</h2>
                    <p className={styles.promotoras__article__text}>ONE Warrior Series es un programa de televisión de la compañía ONE, hecho con el objetivo de buscar prospectos de las artes marciales en Asia, un poco parecido a lo que hace <Link href='/promotoras/ufc'>UFC</Link> con <b>The Ultimate Fighter</b>. El ganador de la competición se ganaría un contrato de 6 cifras con la organización, sin embargo, se prioriza premiar la actuación de los participantes más que la victoria que pudieran o no obtener en sus combates. El programa fue anunciado por el vicepresidente de ONE Rich Franklin, y se le dió luz verde en 2018, actualmente cuenta con 4 temporadas y puede verse en la app de ONE.</p>
                    <h2 className={styles.promotoras__article__title}>Chatri Sityodtong</h2>
                    <p className={styles.promotoras__article__text}>Chatri Trisiripisal, más conocido como Chatri Sityodtong, nació en 1971 en Tailandia, es un empresario fundador y actual CEO de la organización <b>ONE Championship</b>, aunque también es un intructor de artes marciales en Singapur. Chatri se graduó en Economía en la Universidad Tufts en 1994, y obtuvo una Mestría en Administración de Empresas en la Escuela de Negocios de Harvard en 1999. Emigró a Singapr a mediados del 2000, donde vive desde entonces.</p>
                    <p className={styles.promotoras__article__text}>Su interés en las artes marciales comenzaron cunado era niño y empezó a entrenar Muay Thai, arte marcial del cual es rango Kru. Además en 2005 empezó a entrenar jiu-jitsu brasileño, llegando a cinturón marrón bajo la tutela de <b>Renzo Gracie</b>. </p>
                    <p className={styles.promotoras__article__text}>En la actualidad, es es CEO de la mencionada ONE Championship, que es la compañía de deportes más grande Asia según Forbes, y es posicionada por <b>Nielsen</b> entre las 10 propiedades de deportes más grandes del mundo. Además fundó la cadena de academias de artes marciales <b>Evolve MMA</b> con sede en Asia en 2008. Además es destacable su labor de beneficiencia, siendo alguien que realiza constantes donaciones a Boys&apos; Town Home. que es una organización que ayuda a los niños abandonados y a los jóvenes necesitados. También apoya a Singapore Children&apos;s Society y a los niños con cáncer a través de Children&apos;s Cancer Foundation.</p>
                    <h2 className={styles.promotoras__article__title}>ONE Championship Dónde Ver</h2>
                    <p className={styles.promotoras__article__text}>Desde mayo de 2018 que en la mayoría de países se pueden ver todos sus eventos en vivo gratis en su canal oficial de Youtube <a href='https://www.youtube.com/@ONEChampionship' target='_Blank'>ONE Championship</a>.</p>
                    <p className={styles.promotoras__article__text}>Además, gracias a un acuerdo que se concreto el 27 de abril de 2022, <b>Amazon Prime Video</b> transmite al menos 12 eventos al año en horario central en Estados Unidos y Canada.</p>
                    <p className={styles.promotoras__article__text}>Y en el caso de las personas que vivan en Oriente Medio y en el Norte de África, los eventos pueden verse transmitidos a través de <b>BeIN Sports</b> con comentarios en inglés y en árabe.</p>
                </article>
            </section>
        </main>
    )
}