import PeleadoresHero from '@/app/peleadores/components/PeleadoresHero'
import grasso from '@/assets/peleadores__images/mujeres/0-10/alexa-grasso/grasso.png'
import alexa from '@/assets/peleadores__images/mujeres/0-10/alexa-grasso/alexa__grasso.jpg'
import styles from '@/app/peleadores/components/peleador.module.css'
import Image from 'next/image'
import Link from 'next/link'
import AsideFighter from '@/app/components/asides/AsideFighter'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Alexa Grasso',
    description: 'Alexa Grasso es una peleadora mexicana de mma que compite en la UFC desde noviembre de 2016, cuando haría su debut oficial en la final del TUF organizado en latinoamérica, enfrentando a la estadounidense Heather Jo Clark, a quien venció por decisión unánime. Destacó al volverse campeona de Peso Mosca Femenino de la UFC cuando derrotó a la histórica Valentina Shevchenvo en marzo de 2023 con una sumisión en el cuarto asalto en el UFC 285 de Las Vegas.',
    openGraph: {
        title: 'Alexa Grasso',
        description: 'Alexa Grasso es una peleadora mexicana de mma que compite en la UFC desde noviembre de 2016, cuando haría su debut oficial en la final del TUF organizado en latinoamérica, enfrentando a la estadounidense Heather Jo Clark, a quien venció por decisión unánime. Destacó al volverse campeona de Peso Mosca Femenino de la UFC cuando derrotó a la histórica Valentina Shevchenvo en marzo de 2023 con una sumisión en el cuarto asalto en el UFC 285 de Las Vegas.',
        url: 'https://fullmma.org/mujeres/alexa-grasso'
    }
}

export default function AlexaGrasso () {
    return(
        <main>
            <PeleadoresHero peleadoresImage={grasso} w={16} l={4} d={1} nombre='Alexa Grasso' apodo={null} categoria='Peso Mosca Femenino' />
            <section className={styles.peleador__articles__container}>
                <article className={styles.peleador__article}>
                    <h2 className={styles.peleador__article__title}>Alexa UFC</h2>
                    <p className={styles.peleador__article__text}>Alexa Grasso es una peleadora mexicana de mma que compite en la <Link href='/articulos/ufc'>UFC</Link> desde noviembre de 2016, cuando haría su debut oficial enfrentando a la estadounidense <b>Heather Jo Clark</b>, a quien venció por decisión unánime. Destacó en la compañía al volverse campeona de Peso Mosca Femenino de la UFC cuando derrotó a la histórica <Link href='/mujeres/valentina-shevchenko'>Valentina Shevchenvo</Link> en marzo de 2023 con una sumisión en el cuarto asalto en el UFC 285 de Las Vegas.</p>
                    <h2 className={styles.peleador__article__title}>Alexa Grasso Récord</h2>
                    <p className={styles.peleador__article__text}>Alexa Grasso tiene un record de 16-4-1. Siendo 4 de sus victorias por la vía del nocaut, 2 por sumisión y 10 por decisión. Mientras que sus 4 derrotas se componen de 1 por sumisión y de 3 por decisión. Su único empate fue en diciembre de 2023 contra <Link href='/mujeres/valentina-shevchenko'>Valentina Shevchenko</Link>.</p>
                    <h2 className={styles.peleador__article__title}>Alexa Grasso Biografía</h2>
                    <p className={styles.peleador__article__text}>Karen Alexa Grasso Montes, nació el 9 de agosto de 1993 en la ciudad mexicana de Guadalajara, en el Estado de Jalisco. Quienes la inspiraron a entrenar fueron su padre y su tío, a quien solía ver mientras entrenaba y daba clases en el gimnasio que les pertenecía a ambos. Alexa aprendió a hacer shadow boxing gracias a su padre y comenzó a tomar clases con su tío Francisco, al mismo tiempo cuando estos abrieron su gimnasio, nuestra protagonista los ayudó en la recepción, en la limpieza y en todo lo que pudo para estar involucrada en lo que se convertiría en un negocio familiar. </p>
                    <iframe className={styles.peleador__article__video} width="560" height="315" src="https://www.youtube.com/embed/Xeja8Ygq5CI?si=HNYIs87AyEWlfEx3" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Un día decidieron competir en un torneo nacional de Jiu-Jitsu, que resultó en que tanto Alexa, y quien en el futuro también se converitría en peleadora de UFC, <b>Irene Aldana</b>, terminaran en primer lugar del torneo. Grasso recuerda sentirse increíble por esto, y que esta sensación la hizo darse cuenta de que <b>&quot;quería volver a sentir lo mismo estando en el podio.&quot;</b> </p>
                    <p className={styles.peleador__article__text}>La mexicana comenzaría a entrenar MMA siguiendo una rutina compuesta por 3 entrenamientos al día, donde inicia con un entrenamiento de fuerza y condicionamiento en la mañana, luego practica wrestling y jiu jitsu, y finalmente en las noches se dedica a practicar el striking. </p>
                    <p className={styles.peleador__article__text}>Haría su debut profesional el 19 de diciembre de 2012 en un compañía local, enfrentando a su compatriota <b>Sandra del Rincón</b>, a quien sorprendetemente lograría dejar KO a los 15 segundos del combate. Algo parecido lograría unos meses después, cuando en el segundo combate de su carrera, enfrentando a la también mexicana <b>Lupita Hernández</b>, conseguiría dejarla KO a los 12 segundos de la pelea. </p>
                    <p className={styles.peleador__article__text}>Luego de aquellas 2 victorias, Alexa participaría de un torneo de MMA de la compañía <b>Xtreme Kombat</b>, donde enfrentaría a 2 rivales en una misma noche. Enfrentando primero a la peleadora <b>Alejandra Álvarez</b>, a quien vencería por TKO a los 36 segundos de la pelea, avanzando de ronda. Y luego, en la final del torneo, se enfrentaría a quien luego sería campeona en <b>Invicta</b>, <b>Karina Rodríguez</b>, logrando vencerla por decisión unánime y llevándose el cinturón de campeona. </p>
                    <p className={styles.peleador__article__text}>Ya con un récord de 4-0, Alexa firmaría por la promotora especializada en peleas de mujeres <b>Invicta FC</b>, donde tendría un total de 4 combates, siendo el primero de ellos el 6 de septiembre de 2014 ante la estadounidense <b>Ashley Cummins</b>, a quien vencería por decisión unánime. En su segunda pelea, enfrentaría a la americana <b>Alida Gray</b>, venciéndola por TKO en el primer asalto de la pelea. En sus últimas 2 peleas, conseguiría ganar por decisión unánime tanto a <b>Mizuki Inoue</b> en la que sería elegida la pelea de la noche, como a <b>Jodie Esquibel</b>, contra quien ganaría el bono a la Actuación de la Noche.</p>
                    <iframe className={styles.peleador__article__video} width="560" height="315" src="https://www.youtube.com/embed/OLZmjj4c1EU?si=azxEKtGWYpvEZspc" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Ya estando en Invicta, Alexa había conseguido apalabrar su entrada a la UFC con Dana White, por lo que una vez finalizado su contrato comenzaría a competir en la compañía de MMA más grande del mundo, haciendo su debut el 5 de noviembre de 2016, para enfrentar a la estadounidense <b>Heather Jo Clark</b> en un evento organizado en México, consiguiendo una victoria por decisión unánime. Lamentablemente para ella, en su segundo combate en la compañía llegaría la primer derrota de su carrera, cuando enfrentando a la luchadora <b>Felice Herrig</b>, caería derrotada por decisión unánime.</p>
                    <p className={styles.peleador__article__text}>Nuestro protagonista a partir de su primera derrota comenzaría a tener resultados un tanto irregulares, siendo capaz de ganar su siguiente pelea ante la Iraquí <b>Randa Markos</b>, pero por decisión dividida. Perdiendo su siguiente combate ante <b>Tatiana suarez</b>, al ser sometida en el primer asalto de la pelea. Ganando nuevamente en su quinta pelea en la compañía, consiguiendo luego de 3 asaltos vencer a la polaca <b>Karolina Kowalkiewicz</b> por decisión unánime. Y finalmente volvería a perder al enfrentar a la excampeona de peso paja <b>Carla Esparza</b>, quien la vencería por decisión mayoritaria en la que sería elegida la Pelea de la Noche.</p>
                    <iframe className={styles.peleador__article__video} width="560" height="315" src="https://www.youtube.com/embed/tqGe3WyAeAM?si=Nw-UQiqxbDIp68jI" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Sin embargo esta última derrota sería el fin de la racha irregular de la mexicana, dado que tomaría la decisión de moverse de categoría, para comenzar a pelear en la división de peso mosca, donde comenzaríamos a ver la mejor versión de Alexa Grasso, quien conseguiría una racha de 4 victorias consecutivas antes de lograr pelear por el título. Siendo la primera de estas victorias ante la surcoreana <b>Ji Yeon Kim</b>, a quien derrotaría por decisión unánime; conseguiría una segunda victoria por decisión ante la estadounidense <b>Maycee Barber</b>; en marzo de 2022 lograría una importante victoria ante la escocesa <b>Joanne Wood</b>, a quien sometería en el primer asalto; y finalmente, al enfrentar a la brasileña <b>Viviene Araújo</b>, conseguiría vencer por decisión unánime, ganándose el derecho a disputar el título de la división. </p>
                    <iframe className={styles.peleador__article__video} width="560" height="315" src="https://www.youtube.com/embed/0dWk5lVNT2g?si=w-eh2Ar9WRAYK-cq" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Esta racha de victorias finalmente la habilitarían al día 4 de marzo de 2023 a enfrentar a la histórica campeona de peso mosca femenino <Link href='/mujeres/valentina-shevchenko'>Valentina Shevchenko</Link>, quien para entonces llevaba 7 defensas exitosas de su título, desde que lo ganara en diciembre de 2018. En lo que fue la pelea coestelar del UFC 285, la mexicana Alexa Grasso conseguiría hacer lo histórico, lo épico, la gesta de someter en el cuarto asalto de la pelea a quien hasta entonces parecía invencible, proclamándose como la nueva campeona de la división, y ganando además el bono a la Actuación de la Noche por su desempeño. </p>
                    <iframe className={styles.peleador__article__video} width="560" height="315" src="https://www.youtube.com/embed/9X6ZJnLCr1c?si=BjMO-a_S-EV97uLA" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Como no podía ser de otra forma, se programaría una revancha para el 16 de septiembre de 2023, con fecha para el día de la independencia de mexico, ambas peleadoras encabezarían el evento, en lo que sería una pelea muy cerrada que se extendería hasta los 5 asaltos, y que finalmente terminaría en empate dividido a los ojos de los jueces. Dicha decisión causó algo de polémica entre los que habían visto ganar a una o a otra, pero la pelea había estado lo suficientemente cerrada como para que uno de los jueces viera a ganar a Alexa por 48-47, otro a Valentina también por 48-47, y para que finalmente el tercer juez viera un empate en el enfrentamiento entre ambas. El punto es que el empate le servía de igual forma a la mexicana para retener el cinturón, y concretar una defensa exitosa de su título. </p>
                    <iframe className={styles.peleador__article__video} width="560" height="315" src="https://www.youtube.com/embed/RhosJSynMFo?si=ZjOGsW-FbxLraAxb" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>De igual forma, la historia de Alexa Grasso y Valentina Shevchenko no terminaría acá, y la suya sería una rivalidad para los libros de historia de las MMA. Tanto Alexa como Valentina serían las encargadas de protagonizar la temporada 32 de <b>The Ultimate Fighter</b>, el reality de televisión de la UFC, como coachs de sus respectivos equipos, con la idea de finalizar todo en una tercera pelea entre las 2, que se convertiría en la primer trilogía femenina en tener lugar en la UFC. </p>
                    <p className={styles.peleador__article__text}>Finalmente se volverían a ver de nuevo el 14 de septiembre de 2024, de nuevo, por la proximidad de las fechas, con motivo de la celebración del Día de la Independencia de México, en un evento organizado en <b>La Esfera</b> de Las Vegas, en el <Link href='/covertura-ufc/ufc306'>UFC Noche</Link>. Ambas luchadoras protagonizarían la pelea coestelar del evento, y aquella noche la pelea volvería a extenderse a los 5 asaltos, aunque esta vez con una Valentina Shevchenko siendo una dominadora más clara del combate, llevándose la pelea por decisión unánime, arrebatándole lamentablemente para nuestra protagonista, el cinturón de las 125lbs. </p>
                </article>
                <AsideFighter />
            </section>
        </main>
    )
}