import styles from '@/app/peleadores/components/peleador.module.css'
import conor from '@/assets/peleadores__images/0-10/conor-mcgregor/mcgregor.png'
import conorIrlanda from '@/assets/peleadores__images/0-10/conor-mcgregor/conor.jpg'
import mcgregor from '@/assets/peleadores__images/0-10/conor-mcgregor/conor_mcgregor.jpg'
import pelea from '@/assets/peleadores__images/0-10/conor-mcgregor/mcgregor-peleando2.jpg'
import PeleadoresHero from '@/app/peleadores/components/PeleadoresHero'
import Image from 'next/image'
import Link from 'next/link'
import AsideChamps from '@/app/components/asides/AsideChamps'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Conor Mcgregor',
    description: 'Conor McGregor es un peleador irlandés de MMA que compite e hizo la mayor parte de su carrera en la UFC, donde compite desde abril de 2013, cuando hizo su debut ante el estadounidense Marcus Brimage. Es seguramente la mayor estrella con la que ha contado la UFC en su historia, habiendo puesto su nombre en lo más alto primero cuando consiguió ser campeón de peso pluma en diciembre de 2015, y después en noviembre de 2016 conseguiría el doble cinturón al campeonar en la división de peso ligero.',
    openGraph: {
        title: 'Conor Mcgregor',
        description: 'Conor McGregor es un peleador irlandés de MMA que compite e hizo la mayor parte de su carrera en la UFC, donde compite desde abril de 2013, cuando hizo su debut ante el estadounidense Marcus Brimage. Es seguramente la mayor estrella con la que ha contado la UFC en su historia, habiendo puesto su nombre en lo más alto primero cuando consiguió ser campeón de peso pluma en diciembre de 2015, y después en noviembre de 2016 conseguiría el doble cinturón al campeonar en la división de peso ligero.',
        url: 'https://fullmma.org/peleadores/conor-mcgregor'
    }
}

export default function Mcgregor () {
    return(
        <main>
            <PeleadoresHero peleadoresImage={conor} w={22} l={6} d={0} nombre='Conor Mcgregor' apodo='THE NOTORIOUS' categoria='Peso Ligero' />
            <section className={styles.peleador__articles__container}>
                <article className={styles.peleador__article}>
                    <h2 className={styles.peleador__article__title}>McGregor UFC</h2>
                    <p className={styles.peleador__article__text}>Conor McGregor es un peleador irlandés de MMA que compite e hizo la mayor parte de su carrera en la <Link href='/articulos/ufc'>UFC</Link>, donde compite desde abril de 2013, cuando hizo su debut ante el estadounidense <b>Marcus Brimage</b>. Es seguramente la mayor estrella con la que ha contado la UFC en su historia, habiendo puesto su nombre en lo más alto primero cuando consiguió ser campeón de peso pluma en diciembre de 2015, y después en noviembre de 2016 conseguiría el doble cinturón al campeonar en la división de peso ligero. </p>
                    <h2 className={styles.peleador__article__title}>Conor Mcgregor Récord</h2>
                    <p className={styles.peleador__article__text}>Conor Mcgregor posee un récord profesional en las MMA de 22-6-0. Siendo 19 de esas 22 victorias por la vía del nocaut, 1 por sumisión y siendo sólo 2 de sus victorias por decisión. Mientras sus 6 derrotas se componen de 4 por sumisión y 2 por la vía del nocaut.</p>
                    <h2 className={styles.peleador__article__title}>Conor Mcgregor Biografía</h2>
                    <p className={styles.peleador__article__text}>Conor Anthony Mcgregor nació el 14 de julio de 1988 en Dublín, Irlanda, donde se crío durante toda su infancia, de la mano de sus padres Tony y Margaret McGregor. De pequeño se interesó por los deportes, especialmente por el fútbol al que se dedicó a jugar hasta los 12 años, cuando comenzó a entrenar boxeo y en su adolescencia conoció al futuro peleador de ufc Tom Egan, con quien comenzó a entrenar artes marciales mixtas.</p>
                    <iframe className={styles.peleador__article__video} width="560" height="315" src="https://www.youtube.com/embed/3mPPMCa8Nxw?si=EeFRSj20_2-D7MLD" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Con sólo 18 años comenzaría su carrera en el mundo de las MMA peleando de manera amateur, haciendo su debut el 7 de febrero de 2007 contra <b>Kieran Campbell</b> en una promotora irlandesa llamada <b>Irish Ring of Truth</b>, consiguiendo ganar por nocaut en el primer asalto. Ese mismo día logró convertirse en profesional al firmar un contrato con esa misma promotora.</p>
                    <p className={styles.peleador__article__text}>De esta manera haría su debut profesional en las artes marciales mixtas el día 8 de marzo de 2008 en la promotora irlandesa ya mencionada, para enfrentar a su compatriota <b>Gary Morris</b>, a quien lograría derrotar por TKO en el segundo asalto de la pelea. El 3 de mayo tendría un nuevo combate ante <b>Mo Taylor</b>, a quien lograría de la misma manera, noqueándolo en el primer asalto. </p>
                    <p className={styles.peleador__article__text}>El 28 de junio de 2008 tendría una nueva pelea, esta vez debutando en peso pluma para enfrentar al lituano <b>Artemiji Sitenkov</b>, con quien sufriría su primer derrota profesional al ser sometido en el primer asalto. Finalmente tendría un combate más en diciembre de aquel año, en el que enfrentaría a <b>Stephen Bailey</b>, a quien lograría ganar por la vía del nocaut en el primer asalto de la pelea. </p>
                    <p className={styles.peleador__article__text}>Luego de 4 combates en su primer año como pro, no pelearía durante todo el año 2009, haciendo su regreso recién el 9 de octubre de 2010 para enfrentar al británico <b>Connor Dillon</b>, a quien vencería por TKO en el primer asalto luego de una parada del equipo de su rival. Ese mismo año y un mes y medio después, volvería a subirse al octágono para enfrentar a su compatriota <b>Joe Duffy</b>, en una pelea pactada en peso ligero en su debut en la promotora de Reino Unido <b>Cage Warriors</b>, donde lamentablemente volvería a perder al ser sometido en el primer asalto otra vez. </p>
                    <iframe className={styles.peleador__article__video} width="560" height="315" src="https://www.youtube.com/embed/9wp8h2e0NDE?si=5eeGP6zhJbykANQm" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Esta sería la última derrota de nuestro protagonista, puesto que desde entonces comenzaría uno de los ascensos más meteóricos en la historia de las MMA. Empezando con 5 victorias a lo largo del año 2011, siendo la primera por TKO en el primer asalto ante el británico <b>Hugh Brady</b> el 12 de febrero; la segunda llegaría exactamente un mes después, el 12 de marzo, ante <b>Mike Wood</b> por KO a los 16 segundos del combate; la tercera sería el 16 de abril ante <b>Paddy Doherty</b> por KO a los 4 segundos de iniciada la pelea; la cuarta victoria llegaría el 11 de junio, cuando lograría noquear en el segundo asalto al polaco <b>Artur Sowinski</b>; y por último, conseguiría la quinta y última victoria del año en su segunda pelea para Cage Warriors al enfrentar al noruego <b>Aaron Jahnsen</b>, en lo que sería otra pelea en peso ligero que se la llevaría al noquear en el primer asalto. </p>
                    <p className={styles.peleador__article__text}>Su camino al cinturón de peso pluma de la compañía comenzaría con su pelea ante <b>Steve O&apos;Keefe</b>, a quien enfrentaría el 18 de febrero de 2012, logrando noquear a este en el primer asalto de la pelea. Finalmente, luego de aquella victoria, se enfrentaría por el cinturón de la compañía a <b>Dave Hill</b> el día 2 de junio de ese mismo año, sacando un as bajo la manga que nunca volveríamos a ver en Conor, al someter con un mataleon a su rival en el segundo asalto, haciéndose de esta forma con el campeonato de peso pluma de la compañía. </p>
                    <iframe className={styles.peleador__article__video} width="560" height="315" src="https://www.youtube.com/embed/Uxmd4ea57Es?si=JLIEe1QXJEoBIJgK" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Una vez conseguida esta gesta, buscaría ir más allá al disputar de manera inmediata el cinturón de peso ligero de la compañía. Para ello, debería competir el 31 de diciembre de ese mismo año ante el eslovaco <b>Ivan Buchinger</b>, a quien sería capaz de dejar KO en el primer asalto de la pelea, convirtiéndose de esta manera en campeón de la división de peso ligero de Cage Warriors, y en doble campeón de la compañía. </p>
                    <iframe className={styles.peleador__article__video} width="560" height="315" src="https://www.youtube.com/embed/obgm6JNtyVo?si=N83lemhyZaMNFx7D" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Luego de haber logrado esto, firmaría con la compañía de artes marciales mixtas más grande del mundo, haciendo su debut de esta manera en la UFC el día 6 de abril de 2013, enfrentando al estadounidense <b>Marcus Brimage</b>, logrando noquear a este en el primer asalto en lo que sería su retorno a la división de peso pluma, ganando además aquella noche el bono al KO de la noche. </p>
                    <iframe className={styles.peleador__article__video} width="560" height="315" src="https://www.youtube.com/embed/HelivOF6vI8?si=TaWi5wohZ93ctq_r" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>En su segundo combate, con fecha para el 17 de agosto de ese mismo año, se enfrentaría a un joven <Link href='/peleadores/max-holloway'>Max Holloway</Link>, quien en el futuro se convertiría en campeón de la división y en un peleador histórico de la UFC, pero que en aquel entonces llevaba un puñado de peleas y estaba haciendo sus primeras armas en la compañía. El punto es que esta sería la primera pelea de nuestro protagonista en extenderse hasta los 3 asaltos, acabando en una victoria por decisión unánime en favor del irlandés. </p>
                    <iframe className={styles.peleador__article__video} width="560" height="315" src="https://www.youtube.com/embed/BCOy-PG8EIw?si=gUyr14r-2EmM4c7C" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Durante el año 2014 pelearía en 2 ocasiones, siendo la primera del año también el primer evento que encabezaría nuestro protagonista, en UFC Fight Night organizado en la ciudad irlandesa de Dublín el día 19 de julio, se enfrentaría al brasileño <b>Diego Brandao</b>, a quien sería capaz de derrotar por nocaut en el primer asalto de la noche, ganando por ello el bono a la Actuación de la Noche.</p>
                    <p className={styles.peleador__article__text}>En su siguiente pelea con fecha para el 27 de septiembre, se enfrentaría a otro que en el futuro se convertiría en un histórico y en un favorito de los fans, viéndose cara a cara con un joven <Link href='/peleadores/dustin-poirier'>Dustin Poirier</Link>, al que en tan sólo 1 minuto y 46 segundos dejaría KO, llevándose nuevamente el bono a la Actuación de la Noche por lo realizado en el octágono. </p>
                    <iframe className={styles.peleador__article__video} width="560" height="315" src="https://www.youtube.com/embed/xlYDpJSITSk?si=6SW6DTuXhH9WeNs-" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>El año 2015 se convertiría en hasta aquel momento, el más importante de su carrera. Iniciando con una pelea programada para el 18 de enero, en un nuevo evento encabezado por él, en el que enfrentaría al ruso <b>Dennis Silver</b>, a quien finalmente derrotaría por nocaut en el segundo asalto de la pelea, volviendo a ganar el bono a la Actuación de la Noche.</p>
                    <p className={styles.peleador__article__text}>El presidente de la UFC, Dana White, había anunciado antes de aquella pelea que, en caso de ganar, Conor pelearía por el cinturón de la división ante el campeón <Link href='/leyendas/jose-aldo'>José Aldo</Link>, por lo que se pogramaría esta pelea para el día 11 de julio en lo que sería el UFC 189. Sin embargo, el día 23 de junio, Aldo anunciaría que no podría competir debido a una lesión, por lo que en su lugar sería reemplazado por <b>Chad Mendes</b> para enfrentar a Conor por el cinturón interino de la división. Aquella noche, el irlandés no defraudaría, y conseguiría ganar la pelea por nocaut en el segundo asalto, convirtiéndose en el nuevo campeón interino de peso pluma, y ganando un nuevo bono a la Actuación de la Noche. </p>
                    <iframe className={styles.peleador__article__video} width="560" height="315" src="https://www.youtube.com/embed/J-dcm5sA4T0?si=f7jfnr-B2me7U0RD" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>De esta manera, la pelea por el título ante el brasileño <Link href='/leyendas/jose-aldo'>José Aldo</Link> se reprogramaría para el 12 de diciembre, en lo que sería el evento estelar del UFC 194. Aquella noche, nuestro protagonista lograría hacer historia de la forma más épica posible, al conseguir dejar KO al histórico campeón, que venía de 7 defensas exitosas del título. Con lo realizado en esta pelea, lograría ganar y unificar el campeonato de peso pluma de la UFC, ganaría un nuevo bono a la Actuación de la Noche, y rompería el récord al KO más rápido en una pelea por el título en la historia de la UFC. No es de extrañar que, por si ya no lo era, luego de esta pelea Conor McGregor obtuviera el estatus de estrella absoluta.</p>
                    <iframe className={styles.peleador__article__video} width="560" height="315" src="https://www.youtube.com/embed/7qrVQwjieac?si=fL8ydZvHtDYNS449" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Al igual que había hecho en Cage Warriors, Conor esperaba que su siguiente enfrentamiento fuera por el doble campeonato, enfrentando para ello el 5 de marzo de 2016 al brasileño entonces campeón <b>Rafael Dos Anjos</b>, sin embargo días antes del combate este se lesionaría, por lo que en su lugar, la pelea sería reemplazada por un combate de Conor ante el favortio de los fans <Link href='/articulos/nate-diaz-historia'>Nate Diaz</Link> en un combate pactado en peso wélter. Con este combate comenzaría una de las rivalidades más mediáticas de las MMA, debido al cariño que recibían ambos luchadores por parte de los fanáticos. La pelea finalmente terminaría en una victoria por sumisión en el segundo asalto a favor del estadounidense, propinándole la primer derrota de su carrera en la UFC a nuestro protagonista, además aquella sería elegida la Pelea de la Noche. </p>
                    <iframe className={styles.peleador__article__video} width="560" height="315" src="https://www.youtube.com/embed/Gi2Th1oWtVM?si=e7P3sD_ja3_pgGpL" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Luego de aquel combate se programaría una revancha inmediata, nuevamente en la división de peso wélter, para el 20 de agosto de 2016 en el <b>UFC 202</b>. Aquella noche en lo que sería una auténtica guerra, Conor sería capaz de vengar su derrota luego de pasados los 5 asaltos, llevándose la victoria por decisión mayoritaria, en lo que nuevamente sería elegida como La Pelea de la Noche. </p>
                    <iframe className={styles.peleador__article__video} width="560" height="315" src="https://www.youtube.com/embed/Yn65AjlAOKI?si=Gb4QxW1aE1b9S79n" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Una vez finalizados sus asuntos con Nate, iría a por el que su objetivo principal, enfrentando el 12 de noviembre de ese mismo año en el UFC 205, al nuevo campeón de la división de peso ligero, <b>Eddie Álvarez</b>, a quien sería capaz de noquear en el segundo asalto de la pelea. Ganando el bono a la Actuación de la Noche por su desempeño, convirtiéndose en campeón de peso ligero, y haciendo historia al convertirse en el primer doble campeón simultáneo en la historia de la compañía, entrando a la lista con el resto de <Link href='/articulos/dobles-campeones-de-ufc'>Dobles campeones del a UFC</Link></p>
                    <iframe className={styles.peleador__article__video} width="560" height="315" src="https://www.youtube.com/embed/HVLtIP6J5Hk?si=Un5albnSQk_R9u6I" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Luego de un tiempo terminaría por dejar ambos de sus cinturones vacantes, al ir en busca de algo inédito en la historia del mundo de las peleas, al retar al retirado campeón de boxeo <b>Floyd Mayweather</b> a una pelea de boxeo. Floyd se mostraría interesado en dicha súper pelea, que vería involucradas a la mayor estrella del mundo de las MMA con la mayor estrella del mundo del boxeo, afirmando que sólo saldría del retiro si era para enfrentar a McGregor. </p>
                    <p className={styles.peleador__article__text}>La pelea finalmente se organizaría el día 26 de agosto de 2017 en el T-Mobile Arena de Las Vegas, poniéndose en juego el <b>WBC Money Belt</b> en una pelea pactada en Peso Superwélter. En el que pese a la falta de experiencia del pelador irlandés, sería capaz de extender la pelea hasta el décimo asalto, en el que caería derrotado por nocaut técnico. En <Link href='/articulos/boxeador-vs-mma'>este artículo</Link> cubrimos otros de los curiosos enfrentamientos entre las MMA y el Boxeo. </p>
                    <iframe className={styles.peleador__article__video} width="560" height="315" src="https://www.youtube.com/embed/WfiN1UdMgp8?si=-qzoRfTtRnDtxMK_" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Luego de haberse tomado este año 2017 para preparar su pelea de boxeo ante Floyd, Conor prepararía su regreso para enfrentar al nuevo campeón de peso ligero, <Link href='/leyendas/khabib-nurmagomedov'>Khabib Nurmagomedov</Link> el 6 de octubre de 2018 en el UFC 229, en lo que iniciaría una de las rivalidades más salvajes del deporte, y que nos traería a la que probablemente es, la pelea <Link href='/articulos/most-ppv'>más vista en la historia de la UFC</Link>. Todo lo sucedido previo y posterior a este combate, lo cubrimos <Link href='/articulos/conor-vs-khabib'>aquí</Link>, pero en resumen podemos decir que la pica y animosidad que se tenían ambos luchadores, excede lo deportivo y entraba en un terreno más personal. </p>
                    <p className={styles.peleador__article__text}>Cuestión que aquella noche nuestro protagonista sufriría la segunda derrota de su carrera en la UFC, al ser sometido por el luchador daguestaní en el cuarto asalto de la pelea. </p>
                    <iframe className={styles.peleador__article__video} width="560" height="315" src="https://www.youtube.com/embed/JuBBIJ7adjM?si=eZ5uW_-FqHUfPnnb" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Luego de aquella derrota, McGregor se tomaría su tiempo para regresar, tomándose otro año sabático, sin tener demasiada actividad y sin amagar a un regreso durante el 2019. Volviendo recién a la jaula el día 18 de enero de 2020 para enfrentar al histórico luchador estadounidense <b>Donald &quot;Cowboy&quot; Cerrone</b>, en una pelea pactada en peso wélter, donde veríamos a un Conor mucho más relajado en la previa de la pelea, siendo bastante respetuoso con su rival al que sólo le dedicó palabras de halago. Aquella noche el irlandés volvería a la senda de la victoria con una impresionante victoria por TKO a los 40 segundos de la pelea, ganando el bono a la Actuación de la Noche por su desempeño. </p>
                    <iframe className={styles.peleador__article__video} width="560" height="315" src="https://www.youtube.com/embed/w5pT92NRWhI?si=HgbMVz_7Y8nZQ0mo" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>El 23 de enero de 2021 volvería a pelear para luchar contra un rival ranqueado de la división, enfrentando en una revancha a <Link href='/peleadores/dustin-poirier'>Dustin Poirier</Link>. Aquella noche, nuestro protagonista sufriría una de las derrotas más dolorosas de su carrera, al caer noqueado por primera vez en el segundo asalto de la pelea.</p>
                    <iframe className={styles.peleador__article__video} width="560" height="315" src="https://www.youtube.com/embed/6yu2AWK4rxo?si=HvcI8-DC-Lr7Yy3f" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Se programaría una revancha inmediata para que volviera a enfrentar a Poirier el día 10 de julio de ese mismo año, encabezando el UFC 264. Sin embargo, aquella noche volvería a caer derrotado por TKO, aunque en esta ocasión debido a una parada média, dado que cuando estaba finalizando el primer asalto de la pelea, nuestro protagonista de manera completamente accidental, se rompería la pierna al dar un paso atrás, quedando de esta manera imposibilitado de seguir peleando.</p>
                    <iframe className={styles.peleador__article__video} width="560" height="315" src="https://www.youtube.com/embed/G6ymIhvWQug?si=sZzv0rGgVyZGjEHV" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>En parte por esta lesión es que después pasaríamos por la étapa de inactividad más larga hasta ahora en la carrera de Conor, sin pelear en lo que quedó de 2021, sin pelear durante todo el 2022, sin pelear durante el 2023 y sin pisar un octágono durante el 2024, pese a que tenía programada una pelea para julio ante <Link href='/peleadores/michael-chandler'>Michael Chandler</Link> que terminaría cancelando debido a una lesión. </p>
                </article>
                <AsideChamps />
            </section>
        </main>
    )
}