import PeleadoresHero from '@/app/peleadores/components/PeleadoresHero'
import jones from '@/assets/peleadores__images/0-100/10-20/jon-jones/jon_jones.png'
import styles from '@/app/peleadores/components/peleador.module.css'
import Link from 'next/link'
import type { Metadata } from 'next'
import dynamic from 'next/dynamic'

const AsideChamps = dynamic(() => import('@/app/components/asides/AsideChamps'))
const EndArticle = dynamic(() => import('@/app/components/EndArticle'))

export const metadata: Metadata = {
    title: 'Jon Jones',
    description: 'Jon Jones es un peleador estadounidense de MMA que compite en la UFC desde agosto de 2008. Destacó en la UFC al ser campeón de la división de peso semipesado y de la división de peso pesado, en la que compite actualmente. Tiene una innumerable cantidad de logros que lo ponen en la consideración de muchos como el mejor artista marcial mixto de la historia.',
    openGraph: {
        title: 'Jon Jones',
        description: 'Jon Jones es un peleador estadounidense de MMA que compite en la UFC desde agosto de 2008. Destacó en la UFC al ser campeón de la división de peso semipesado y de la división de peso pesado, en la que compite actualmente. Tiene una innumerable cantidad de logros que lo ponen en la consideración de muchos como el mejor artista marcial mixto de la historia.',
        url: 'https://fullmma.org/peleadores/jon-jones'
    }
}

export default function JonJones () {
    return(
        <main>
            <PeleadoresHero peleadoresImage={jones} w={28} l={1} d={0} nombre='Jon Jones' apodo='BONES' categoria='PESO PESADO' />
            <section className={styles.peleador__articles__container}>
                <article className={styles.peleador__article}>
                    <h2 className={styles.peleador__article__title}>Jon Jones UFC</h2>
                    <p className={styles.peleador__article__text}>Jon Jones es un peleador estadounidense de MMA que compite en la UFC desde agosto de 2008, cuando haría su debut en el UFC 87 enfrentando al brasileño <b>André Gusmao</b>, a quien derrotaría por decisión unánime. </p>
                    <p className={styles.peleador__article__text}>Cuando hablamos de Jon Jones, aunque para algunas persona pueda suene controversial, estamos hablando del mejor peleador de la historia. Es el Lionel Messi de las artes marciales mixtas. Tiene experiencia desde su juventud en Wrestling, que más tarde le serviría para aplicar en su carrera como artista marcial mixto, pero Jon ha trascendido eso, independientemente del estilo, supo evolucionar para que sin importar quien se le ponga enfrente, pueda encontrar el camino a la victoria, derrotando a oponentes de alto calibre con diferentes estilos y técnicas, de diferentes generaciones incluso, demostrando que es el mejor en lo que hace.</p>
                    <p className={styles.peleador__article__text}>Aún con sus controversias extradeportivas, que involucran el uso de sustancias dopantes, de otras sustancias prohibidas, y con la violación de la ley en varias ocasiones. Incluso con las controversias dentro del octágoono (tengo que admitir que no soy fan de las patadas oblicuas y de los piquetes de ojos a los que recurrió en más de una ocasión), es muy difícil poner a un peleador por encima de él. </p>
                    <h2 className={styles.peleador__article__title}>Jon Jones Record</h2>
                    <p className={styles.peleador__article__text}>Jon Jones posee un récord profesional de 28-1 (1). Siendo 11 de sus victorias por la vía del nocaut, 7 por la vía de la sumisión y 10 por decisión. Mientras que su única derrota profesional, fue por descalificación ante <b>Matt Hamill</b>, luego de arrojarle unos codazos ilegales. Además tiene una pelea quedó sin resultado ante <Link href='/leyendas/daniel-cormier'>Daniel Cormier</Link>, a quien originalmente había derrotado pero que luego de realizarse una prueba anti dopaje, y dar positivo, se terminó por anular el resultado de la pelea. </p>
                    <h2 className={styles.peleador__article__title}>Jon Jones historia</h2>
                    <p className={styles.peleador__article__text}>Jonathan Dwight Jones nació el 19 de julio de 1987 en la ciudad de Rochester, en Nueva York. Nació en el seno de una familia religiosa, siendo su hijo de un pastor que lo crió junto a sus 3 hermanos, Chandler, Arthur y Carmen, esta última falleciendo a la edad de 18 años, y fue en honor a ella que Jon se hizo su famoso tatuaje en el pecho que dice <b>Filipenses 4:13</b>, que era el pasaje bíblico favorita de su hermana. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/KzXA8kuQAwk?si=zgfThcaOOXTor7IL" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Sus hermanos se durante la secundaria y la universidad se dedicaron a jugar fútbol americano, y aunque un inicio Jon seguiría sus pasos, terminaría por transicionar al Wrestling, donde destacaría rápidamente. Según el mismo confiesa a la UFC, comenzó a entrenar MMA en el 2007, cuando tuvo un hijo inesperado en la universidad y necesitaba hacer dinero, en parte por esto se explica lo mega activo que estuvo al inicio de su carrera, teniendo 8 combates en su primer año como profesional. </p>
                    <p className={styles.peleador__article__text}>De esta forma haría su debut en las MMA el 12 abril de 2008 ante <b>Brad Bernard</b>, logrando una victoria por nocaut en el primer asalto. Una semana después tendría su segundo combate, ante el brasileño <b>Carlos Eduardo</b>, dejándolo KO en el tercer asalto de la pelea. Tan sólo 6 días después volvería a pelear, para enfrentar a <b>Anthony Pina</b>, a quien sometería en el primer asalto. El 9 de mayo enfrentaría a <b>Ryan Verrett</b>, a quien noquearía a los 14 segundos de iniciada la pelea. El 20 de junio volvería a pelear para enfrentar al futuro peleador de UFC <b>Parker Porter</b>, a quien dejaría KO a los 36 segundos del combate. En julio volvería al octágono para enfrentar a <b>Moyses Gabin</b>, derrotándolo por TKO en el segundo asalto, y ganando en este combate el <b>Campeonato de Peso Semipesado de USKBA.</b></p>
                    <p className={styles.peleador__article__text}>De esta manera, con un récord profesional de 6-0, conseguiría abrirse camino para firmar con la UFC, en donde debutaría menos de un mes después de su último combate, el 9 de agosto en el UFC 87, para enfrentar al brasileño <b>André Gusmao</b>, en lo que sería la primer pelea de nuestro protagonista en concluir los 3 asaltos, ganando de igual forma el combate por decisión unánime. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/ONurh1UOQHg?si=cTgmaHI3sH16T93x" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>En enero de 2009 tendría su segundo combate en la compañía ante <b>Stephan Bonnar</b>, a quien conseguiría derrotar por decisión unánime. Pelearía en el UFC 100 ante <b>Jake O&apos;Brien</b>, consiguiendo una victoria por sumisión en el segundo asalto. Y finalmente tendría una pelea en diciembre de ese año, que sería la única &quot;derrota&quot; de su récord, cuando enfrentando a <b>Matt Hamill</b>, en un combate que Jones estaba dominando completamente, le lanzó unos codazos ilegales desde arriba, que llevaron al árbitro a separarlos, a para la pelea, y a descalificar a Jon Jones, dando como ganandor a su rival. </p>
                    <p className={styles.peleador__article__text}>Pese a esto, volvería a pelear en marzo de 2010 ante <b>Brandon Vera</b> en un evento encabezado por ellos 2, consiguiendo volver a ganar al mediante codazos y golpes, noquear a su rival en el primer asalto del combate, ganando el ya extinto bono al KO de la noche, convirtiéndose esta en la décima victoria de su carrera.</p>
                    <p className={styles.peleador__article__text}>Pelearía el 1 de agosto de ese mismo año ante el luchador de Bielorrusia <b>Vladimir Matyushenko</b>, en un Fight Night encabezado por ellos 2, en donde lograría llevarse otra victoria por TKO mediante codazos en el primer asalto de la pelea. El 5 de febrero de 2011 en el UFC 126 se subiría al octágono para competir ante su compatriota <b>Ryan Bader</b>, a quien en el segundo asalto sería capaz de someter con una guillotina, ganando el extinto premio a la Sumisión de la Noche. </p>
                    <p className={styles.peleador__article__text}>Con un récord de 12-1, siendo 6 de sus victorias en la UFC, a Jones se la daría la oportunidad de pelear por el título de los semipesados de la UFC ante el legendario luchador brasileño <b>Maurício Rua</b>, a quien enfrentaría el 19 de marzo de 2011 en el UFC 128. Aquella noche haría historia, al ser capaz de derrotar por TKO al campeón en el tercer asalto de la pelea, ganando él el Campeonato de Peso Semipesado de la UFC, y con sus 23 años, convirtiéndose en <Link href='/articulos/campeon-mas-joven-de-ufc'>el campeón más joven en la historia de la UFC.</Link></p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/xjseqRSfBTc?si=DoANJlbvn8BUZch7" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Poca gente lo sabía en ese entonces, pero a partir de ese momento iniciaría uno de los reinados más largos de la historia de la compañía y de este deporte. Realizando su primera defensa ante el estadounidense y excampeón <b>Quinton &quot;Rampage&quot; Jackson</b>, encabezando el evento de UFC 135 el 24 de septiembre de 2011, noche en la que conseguiría su primer defensa exitosa al someter a su rival en el cuarto asalto de la pelea, en la que luego sería elegida como la Pelea de la Noche. </p>
                    <p className={styles.peleador__article__text}>Su segunda defensa la haría el legendario también excampeón brasileño <b>Lyoto Machida</b>, quien venía de una victoria por KO ante <Link href='/leyendas/randy-couture'>Randy Couture</Link>. Enfrentándose el 10 de diciembre de ese mismo año por el UFC 140, donde nuestro protagonista volvería a demostrar que su nivel estaba por encima de todos, logrando conectar una guillotina de pie, en lo que fue una de las sumisiones más terrorificas que se han visto en el deporte, con su rival cayendo desmayado al suelo producto de la técnica de Jones. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/Pzi8UFEWRxI?si=h-VbIbn1hnaDw_G6" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>En el 2012 defendería 2 veces su cinturón, haciendo la primer defensa efectiva el 21 de abril en el UFC 145, cuando enfrentaría a <b>Rashad Evans</b>, a quien derrotaría luego de 5 asaltos por decisión unánime. Y la segunda defensa del año la haría el 22 de septiembre en el UFC 152, enfrentando al histórico excampeón de la división <b>Vitor Belfort</b>, a quien en el cuarto asalto del combate lograría someter, ganando nuevamente el bono a la Sumisión de la Noche. </p>
                    <p className={styles.peleador__article__text}>El 2013 lo iniciaría peleando el 27 de abril, en lo que sería su quinta defensa del cinturón ante &quot;El Invicto&quot; <b>Chael Sonnen</b>, quien luego de haber perdido su oportunidad de ser campeón de peso mediano al enfrentar a <Link href='/leyendas/anderson-silva'>Anderson Silva</Link>, subiría de categoría para buscar el campeonato ante nuestro protagonista. Aquel evento de UFC 159, acabaría con Jon Jones acabando con Sonnen vía TKO en el primer asalto. </p>
                    <p className={styles.peleador__article__text}>En septiembre de ese año tendría uno de los combates más recordados de su carrera, en el que hizo historia, y donde por primera vez lo vimos estar en serios aprietos. Dado que para el UFC 165, se enfrentaría al luchador sueco <b>Alexander Gustafsson</b>, quien tenía la misma edad que nuestro protagonista, y que venía imparable, habiendo perdido sólo 1 de sus últimos 15 enfrentamientos, viniendo además de una racha de 6 victorias consecutivas. Este peleador sería el primer en realmente dar pelea a Jones, dando lo que fue un combate disputado, donde cualquiera de los 2 podría haber ganado, finalmente la pelea se extendió hasta los 5 asaltos, y los jueces dieron como ganador al estadounidense por decisión unánime. </p>
                    <p className={styles.peleador__article__text}>Esta pelea fue elegida la Pelea de la Noche, que significó un nuevo bono para Jon Jones, y tiempo después sería elegida como La Pelea del Año 2013. Además, con esta victoria, Jones rompía el record de la mayor cantidad de defensas consecutivas del título en la división de peso semipesado de la UFC, con 6. </p>
                    <p className={styles.peleador__article__text}>En 2014 sólo pelearía una vez, contra quien en el futuro se converitría en uno de los <Link href='/articulos/campeon-viejo-ufc'>Campeones más viejos de la historia</Link>, <b>Glover Teixeira</b>, a quien en una pelea que se extendería hasta los 5 asaltos, conseguiría derrotar por decisión unánime, extendiendo a 7 las defensas consecutivas de su título. </p>
                    <p className={styles.peleador__article__text}>A partir de este momento es cuando se daría inicio a una de las mayores rivalidades en la historia de la UFC, y a los hechos extradeportivos que involucran la vida privada de Jon Jones más conocidos. Dado que para el 3 de enero de 2015, se lo programaría para luchar ante el entonces invicto <Link href='/leyendas/daniel-cormier'>Daniel Cormier</Link>, que para la fecha de la pelea tenía un récord de 15-0. Ambos luchadores encabezarían lo que sería el UFC 182, en un ambiente muy caldeado debido a la antipatía que ambos peleadores se tenían. Aquella noche finalmente sería Jon Jones el que se haría con la victoria por decisión unánime, siendo el primer luchador en ser capaz de derribar a Cormier. La pelea sería elegida como la Pelea de la Noche, y Jones extendería el récord de defensas consecutivas a 8. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/ES8zfCqOlUk?si=CcFwxi7gepVVANIv" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Se programaría una novena defensa ante <b>Anthony Johnson</b>, a quien debía enfrentar el 23 de mayo de 2015, sin embargo, unos días antes del evento, Jones fue protagonista de un accidente de transito, en el que salió herida una mujer que estaba embarazada, abandonando el lugar del accidente. Esta acción por su parte le significó repercusiones legales, además de una sanción por parte de la UFC, que lo despojó de su título por violar el código de conducta de la compañía. </p>
                    <p className={styles.peleador__article__text}>Para el año siguiente en el 2016, una vez finalizada su suspensión se tendría previsto que haga su regreso al octágono para enfrentar en una ravancha a Cormier, quien en este tiempo se había convertido en el campeón de la división, pero esta vez fue su rival el que no pudo asistir a la cita, debido a una lesión que le impidió pelear. Por esto entró en su lugar como reemplazo, el estadounidense <b>Ovince Saint Preux</b>, para disputar el título interino contra nuestro protagonista, a quien sería capaz de ganar aquella pelea por decisión unánime. </p>
                    <p className={styles.peleador__article__text}>Se reprogramaría la pelea con Cormier para el gran evento, que estaba pensado para ser el más importante de la historia de la compañía, el <b>UFC 200</b>, donde ambos peleadores serían quienes encabecen el evento. Pero lamentablemente, nuestro protagonista nuevamente no podría acudir debido a sólo 2 días antes de que se hiciera la pelea, dió positivo por dopaje, siendo retirado de la cartelera. </p>
                    <p className={styles.peleador__article__text}>Finalmente su ansiado regreso al octágono se haría efectivo el 29 de julio de 2017, cuando encabezando el UFC 214 enfrentaría en la revancha a <Link href='/leyendas/daniel-cormier'>Daniel Cormier</Link>, en una pelea en la que Jones conseguiría derrotar por KO a su rival, con una patada a la cabeza y golpes con los puños que le otorgarían la victoria. Gracias a esta actuación, ganaría el bono a la Actuación de la Noche y recuperaría el título del que había sido despojado. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/17hQxcm8KHU?si=yn2yyoqIu1KDOUG4" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Sin embargo, todo lo ganado aquella noche lo volvería a perder de un momento para otro como consecuencia de sus propios actos, puesto que en mes después de aquella pelea, USADA (la Agencia Antidopaje de Estados Unidos) dió a conocer que las 2 pruebas que le hicieron al peleador estadounidense el día del pesaje el 28 de julio (un día antes del combate), dieron positivo en un esteroide anabólico, por lo que la Comisión Atlética del Estado de California, decidió dejar aquella pelea oficialmente sin resultado, revirtiendo la victoria que había obtenido. Además, tiempo después el mismo Dana White lo despojaría del cinturón de campeón para retornárselo a Daniel Cormier. </p>
                    <p className={styles.peleador__article__text}>Jon Jones tardaría más de un año en regresar a pelear, haciéndolo para enfrentar en una revancha a <b>Alexander Gustafsson</b>, el día 29 de diciembre de 2019 en el UFC 232. Debido a que Cormier luego de una defensa más del cinturón, había dejado la división de los semipesados para moverse a los pesos pesados, es que el cinturón quedaría vacante y se los disputarían estos 2 luchadores. Aquella noche, el peleador americano conseguiría hacerse con la victoria por TKO en el segundo asalto, recuperando ahora sí su cinturón de campeón del que en 2 ocasiones fue despojado. </p>
                    <p className={styles.peleador__article__text}>Iniciaría su segundo reinado defendiendo ante <b>Anthony Smith</b> en marzo de 2019 en el UFC 235, consiguiendo derrotar a este peleador por decisión unánime. Su segunda defensa sería en julio de ese mismo año, siendo cabeza de evento en el UFC 239, enfrentando al brasileño <b>Thiago Santos</b>, a quien luego de 5 asaltos conseguiría derrotar por decisión unánime. </p>
                    <p className={styles.peleador__article__text}>Su tercera y última defensa del cinturón, la tendría en el que quizás sea el combate más polémico que tuvo, y el que sin dudas lo dejó más cercano a la derrota. Cuando en el UFC 247 organizado en febrero de 2020, enfrentaría a <b>Dominick Reyes</b>, en una pelea que duraría los 5 asaltos de campeonato, y donde los jueces lo terminarían dando como ganador. Sin embargo, la decisión de los jueces fue motivo de debate, dado que muchos, entre los que se incluye el mismo Dana White, como confesaría en la rueda de prensa posterior a la pelea, habían visto ganar a Reyes, y creían que él debía ser quien se quedara con la victoria. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/ub8_c-X9mh0?si=H-piyNPwQCpjt7lM" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Luego de aquel combate, Jones tomaría una decisión en pos de su legado agigantar aún más su inmenso legado. Optaría por dejar vacante su cinturón en la división de peso semipesado, para tomarse su tiempo para preparse y finalmente subir a los pesos pesados, en busca del doble campeonato, habiendo enfrentando ya a todos los rivales y a los mejores luchadores que la división de 205lbs, era momento de buscar un nuevo reto más difícil que lo hasta entonces conseguido. </p>
                    <p className={styles.peleador__article__text}>Por eso, luego de aquella última pelea en 2020, no lo volveríamos regresar hasta marzo del 2023, cuando en el UFC 285 haría su regreso para enfrentar al francés y principal contendiente al título <Link href='/peleadores/ciryl-gane'>Ciryl Gane</Link>, con quien se disputaría el cinturón de los pesos pesados de la UFC. En aquella ocasión, Jones demostraría porqué es el mejor de todos los tiempos, al en sólo 2 minutos de la pelea, someter con una guillotina a quien debía ser el hombre más peligroso de la compañía, convirtiéndose en el octavo doble-campeón de la UFC, y ganando además el bono a la Actuación de la Noche. </p>
                    <EndArticle />
                </article>
                <AsideChamps />
            </section>
        </main>
    )
}