import PeleadoresHero from '@/app/peleadores/components/PeleadoresHero'
import fighter from '@/assets/peleadores__images/0-100/40-60/paulo-costa/paulo_costa.png'
import styles from '@/app/peleadores/components/peleador.module.css'
import Link from 'next/link'
import type { Metadata } from 'next'
import dynamic from 'next/dynamic'
import { YouTubeEmbed } from '@next/third-parties/google'

const AsideChamps = dynamic(() => import('@/app/components/asides/AsideChamps'))
const EndArticle = dynamic(() => import('@/app/components/EndArticle'))

export const metadata: Metadata = {
    title: 'Paulo Costa',
    description: '',
    openGraph: {
        images: '',
        title: 'Paulo Costa',
        description: '',
        url: 'https://fullmma.org/peleadores/paulo-costa'
    }
}

export default function PauloCosta () {
    return(
        <main>
            <PeleadoresHero peleadoresImage={fighter} w={16} l={4} d={0} categoria='Peso Semipesado' nombre='Paulo Costa' apodo='THE ERASER' time='2026-04-15' />
            <section className={styles.peleador__articles__container}>
                <article className={styles.peleador__article}>
                    <h2 className={styles.peleador__article__title}>¿Quién es Paulo Costa?</h2>
                    <p className={styles.peleador__article__text}>Paulo Costa es un peleador de MMA brasileño que compite en la división de peso semipesado de la UFC. Es uno de los luchadores más populares de la compañía, siendo de los más carismáticos y más divertidos de seguir en redes sociales, ha destacado por su striking agresivo y su estilo de lucha que siempre es entretenido de ver, ganando un montón de combates por la vía del nocaut y ganando varios bonus de la compañía. </p>
                    <p className={styles.peleador__article__text}>Luego de años de pelear en la división de peso medio, llegando hasta competir por el cinturón ante el histórico campeón nigeriano <Link href='/peleadores/israel-adesanya'>Israel Adesanya</Link>, ha dado el salto a la división de peso semipesado, donde se lo sigue viendo muy grande, y donde, hasta el momento, conserva el nivel que le vimos en las 185lbs. </p>
                    <h2 className={styles.peleador__article__title}>Paulo Costa Récord</h2>
                    <p className={styles.peleador__article__text}>Paulo Costa posee un récord profesional en MMA de 16-4. Con 12 de sus victorias proveniendo por la vía del nocaut, sólo 1 siendo por sumisión y 3 siendo por decisión. Mientras que de sus 4 derrotas sólo 1 fue por la vía del nocaut, y 3 fueron por decisión.</p>
                    <h2 className={styles.peleador__article__title}>Paulo Costa Historia</h2>
                    <p className={styles.peleador__article__text}>Paulo Henrique Costa nació el 21 de abril de 1991 en Belo Horizonte, Brasil. Creció jugando al fútbol en las calles junto a su hermano mayor Carlos (que años después se convertiría en peleador profesional y que hoy en día es entrenador de Paulo), aunque no era muy bueno y se metía constantemente en problemas y peleas callejeras, por lo que a los 8-9 años empezó a entrenar Muay Thai, con la idea de aprender disciplina, evitar meterse en más problemas y ganar auto-control. Aunque su madre al principio fue escéptica con esto, creyó en los entrenadores de su hijo y reconoció que esta actividad realmente había calmado a su hijo. </p>
                    <p className={styles.peleador__article__text}>No era hijo de una familia rica, su padre tenía trabajos ocasionales e improvisaba pesas caseras con latas de tomas rellenas de cemento para que su hijo pudiera entrenar biceps. Ambos padres eran pastores evangélicos, por lo que creció en un ambiente familiar muy religioso. </p>
                    <p className={styles.peleador__article__text}>A los 17 años tuvo que lidiar con la dolorosa pérdida de su padre, quien falleció por cáncer de garganta, lo que cual dejó a la familia en una situación económica difícil y a Paulo con una sensación de &quot;estar perdido&quot; durante un tiempo. Debido a esto dejó entrenar y comenzó a trabajar para ayudar economicamente a su madre, teniendo una pasantía como asistente de computación; trabajando en telemarketing; siendo profesor de informática; y trabajando como vendedor inmobiliario, lo cual le daba buen dinero pero no le dejaba tiempo disponible para entrenar. </p>
                    <p className={styles.peleador__article__text}>Un par de años después decidiría volver a entrenar Jiu-Jitsu brasileño, esta vez bajo la tutela de su hermano mayor que era cinturón púrpura, y rápidamente destacó, con su hermano viendo un potencial enorme en él. El punto de inflexión fue en 2012, cuando la UFC llegó a realizar un evento en su ciudad en el UFC 147, que se celebró en Belo Horizonte, ambos hermanos asistieron al evento y salieron convencidos de que eso era lo que querían hacer con sus vidas. </p>
                    <p className={styles.peleador__article__text}>Su hermano Carlos convenció a su madre de que apoyé a nuestro protagonista para que se dedicara a entrenar y competir a tiempo completo en las MMA, convencido de que tenía un gran futuro y de que podían llegar a hacer cosas grandes. Su madre aceptó y vaya que hicieron lo correcto, porque Paulo Costa pasaría a tener una carrera sobresaliente. </p>
                    <p className={styles.peleador__article__text}>Haría su debut profesional el día 5 de febrero de 2012 ante el brasileño <b>Teo Esteves</b>, logrando derrotarlo por nocaut a los 2 minutos del primer asalto. Al año siguiente pelearía 2 veces, obteniendo otras 2 victorias por nocaut, primero el 15 de junio ante su compatriota <b>Ademilson Borges Duarte</b>, y luego el 1 de noviembre ante <b>Fabio Moreira</b>. </p>
                    <YouTubeEmbed videoid='ptxAslIwvYI' />
                    <p className={styles.peleador__article__text}>En 2014 sólo pelearía una vez, enfrentando a <b>Gerson da Silva Conceicao</b>, a quien vencería por TKO, por parada médica en el primer asalto.</p>
                    <p className={styles.peleador__article__text}>El 15 de abril de 2015, ganaría su primer cinturón profesional, al enfrentar a su compatriota <b>Wagner Silva Gomes</b>, noqueándolo en el primer asalto. Luego de esto firmaría con la promotora <b>Jungle Fight</b> un contrato de 3 peleas: </p>
                    <p className={styles.peleador__article__text}>La primer pelea en esta promotora brasileña la tendría el 5 de diciembre de ese mismo año ante un luchador llamado <b>Bruno Assis</b>, a quien noquearía en el primer asalto. El 21 de mayo de 2016 se ganaría la oportunidad de pelear por el cinturón de la compañía ante <b>Eduardo Ramon</b>, contra quien solo le bastaría de un asalto para llevarse la victoria por sumisión, siendo la primera de su carrera. Defendería en una ocasión el cinturón el 3 de septiembre de ese mismo año, enfrentando a <b>Adriano Silverio Balby de Araujo</b>, dejándolo KO a los 3 minutos del primer asalto. </p>
                    <h2 className={styles.peleador__article__title}>Paulo Costa UFC</h2>
                    <p className={styles.peleador__article__text}>Habiendo sido campeón en 2 compañías diferentes, con una defensa del título incluída, habiendo cosechado un récord profesional de MMA invicto de 8-0, y habiendo ganado todas sus peleas por finalización en el primer asalto, con 7 nocauts y 1 sumisión, Paulo Costa se pondría rápidamente en el radar de la UFC, quienes le ofrecería un contrato y la posibilidad de debutar en la compañía de artes marciales mixtas más grande del mundo en país natal, Brasil. </p>
                    <p className={styles.peleador__article__text}>De esta forma, debutaría el día 11 de marzo de 2017 en un evento organizado en Fortaleza, enfrentando al luchador sudafricano <b>Garreth McLellan</b>, contra quie conseguiría, una vez más, noquear en el primer asalto, ganando gracias a esto el bono a la Actuación de la Noche. </p>
                    <p className={styles.peleador__article__text}>Pocos meses después, el 3 de junio, volvería a subirse al octágono para enfrentar al nigeriano <b>Oluwale Bamgbose</b>, en el <b>UFC 212</b>, que también se celebraría en Brasil, en el que sería el primer combate que pasaría del primer asalto en su carrera, logrando una victoria por nocaut en el segundo asalto del combate. Finalmente cerraría el año el 4 de noviembre en el <b>UFC 217</b>, enfrentando al estadounidense <b>Johny Hendricks</b>, a quien vencería por nocaut en el segundo asalto de la pelea. </p>
                    <p className={styles.peleador__article__text}>Siguiendo con su ascenso meteórico, el 7 de julio de 2018 aceptaría pelear contra el luchador de Jamaica <b>Uriah Hall</b>, derrotándolo por nocaut en el segundo asalto, y ganando el segundo bono de su carrera a la Actuación de la Noche. </p>
                    <h3>Paulo Costa vs Yoel Romero</h3>
                    <p className={styles.peleador__article__text}>El 17 de agosto de 2019 tendría su gran chance, peleando en una pelea eliminatoria por el cinturón de la división, lo que significaba que de ganar pelearía por el título contra el campeón. Para ello debió enfrentarse a la leyenda cubana <Link href='/articulos/yoel-romero-genetica'>Yoel Romero</Link> en el <b>UFC 241</b>, aquella noche seríamos testigos de una de las peleas más memorables en la historia moderna de la UFC, con Paulo Costa siendo quein finalmente resultaría ganador por decisión unánime, y con el el cubano resultando en el único peleador que fue capaz de llevar a la decisión a nuestro protagonista. Costa ganaría el combate, ganaría un nuevo bono, esta vez a La Pelea de la Noche, y finalmente ganaría la oportunidad de pelear por el título de la UFC. </p>
                    <YouTubeEmbed videoid='mQCvriuwRDo' />
                    <h3>Paulo Costa vs Israel Adesanya</h3>
                    <p className={styles.peleador__article__text}>La pelea por el cinturón tendría lugar el 26 de septiembre de 2020 en el <b>UFC 253</b> ante el histórico campeón africano <Link href='/peleadores/israel-adesanya'>Israel Adesanya</Link>, en uno de los combates más esperados por los fanáticos, lamentablemente nuestro protagonista recibiría la primer derrota profesional de su carrera, cayendo vía TKO en el segundo asalto del combate, perdiendo de esta manera su tan ansiada oportunidad de campeonar. </p>
                    <p className={styles.peleador__article__text}>Por si no fuera suficiente, debido a los problemas que estaba teniendo nuestro protagonista para dar el peso, acepta un combate en peso semipesado ante el italiano <b>Marvin Vettori</b>, que en aquel momento estaba ranqueado también en peso mediano, en una pelea a 5 asaltos en un evento encabezado por ambos, donde Costa volvería a caer derotado, acumulando su segunda derrota consecutiva, esta vez por decisión unánime. </p>
                    <p className={styles.peleador__article__text}>Como mencioné anteriormente, debido a que nuestro protagonista estaba sufriendo enormemente para dar el peso en la váscula, pelearía de manera cada vez más espaciada, eso explica que su siguiente pelea fuera en agosto de 2022, completando 5 peleas en 5 años. Se enfrentaría al estadounidense <b>Luke Rockhold</b>, y aunque terminaría ganando el combate, sorprendentemente el combate llegaría a la decisión de los jueces, siendo incapaz de finalizar a un luchador que estaba de retiarada. De igual forma ganaría un nuevo bono a La Pelea de la Noche. </p>
                    <p className={styles.peleador__article__text}>Se tomaría 2 años para volver a pelear, pero esta vez lo haría de forma más activa, teniendo 2 combates importantísimos en el año 2024. Primero enfrentaría al excampeón australiano de la división <Link href='/peleadores/robert-whittaker'>Robert Whittaker</Link>, contra quien caería derrotado por decisión unánime. Y por último pelearía el 1 de junio de 2024 ante el también excampeón, el estadounidense <Link href='/peleadores/sean-strickland'>Sean Strickland</Link>, en un combate a 5 asaltos en la coestelar del <b>UFC 302</b>, donde volvería a caer derrotado por decisión unánime, acumulando su segunda derrota consecutiva y recibiendo su cuarta derrota en 5 peleas. </p>
                    <p className={styles.peleador__article__text}>Sin embargo, esta última derrota sería un punto de inflexión, ya que pasaría de pelear contra el último campeón de la división, a enfrentar al ruso <b>Roman Kopylov</b>, en un combate donde muy probablemente se estaba jugando su lugar en los rankings, basicamente era una pelea que le puso la UFC para ver si estaba acabado o todavía quedaba algo del Paulo Costa primer. Por lo que lo enfrentaría el 19 de julio en el <Link href='/eventos/ufc318'>UFC 318</Link>, donde obtendría una victoria por decisión unánime, esta vez mostrándose más maduro, controlando mejor la distancia, eligiendo mejor sus golpes, arriesgando menos que de costumbre y mostrando que todavía tiene mucho por dar. </p>
                    <h3>Paulo Costa en Peso Semipesado</h3>
                    <p className={styles.peleador__article__text}>Finalmente, luego de mucho tiempo en el que sufrió para dar el peso en las 185lbs, se decidió a subir de división, y en ese paso importante la UFC le puso uno de los rivales más difíciles que le podrían haber dado. Puesto que el 11 de abril de 2026 en el <b>UFC 327</b>, se lo programaría para enfrentar al peleador ruso invicto <b>Azamat Murzakanov</b>, quien venía de una victoria espectacular por KO ante <b>Rakic</b> y estaba ranqueado #6 en peso semipesado. Sin embargo aquella noche Paulo Costa sorprendería a todos al dar un combate espectacular ante su rival, manteniendo la distancia y moviéndose constamente para ir ganando el combate en caso de llevarse a la decisión, cosa que no haría falta porque ahí es cuando el brasileño haría lo increíble, conectando una patada espectacular a la cabeza de su rival tumbándolo en el suelo, llevándose la victoria por TKO en el tercer asalto. </p>
                    <YouTubeEmbed videoid='8stXBaQjnes' />
                    <p className={styles.peleador__article__text}></p>
                    <p className={styles.peleador__article__text}></p>
                    <p className={styles.peleador__article__text}></p>
                    <EndArticle />
                </article>
                <AsideChamps />
            </section>
        </main>
    )
}