import PeleadoresHero from '@/app/peleadores/components/PeleadoresHero'
import holloway from '@/assets/peleadores__images/0-100/10-20/max-holloway/holloway.png'
import traje from '@/assets/peleadores__images/0-100/10-20/max-holloway/holloway_traje.jpg'
import styles from '@/app/peleadores/components/peleador.module.css'
import Image from 'next/image'
import Link from 'next/link'
import type { Metadata } from 'next'
import dynamic from 'next/dynamic'

const AsideChamps = dynamic(() => import('@/app/components/asides/AsideChamps'))
const EndArticle = dynamic(() => import('@/app/components/EndArticle'))

export const metadata: Metadata = {
    title: 'Max Holloway',
    description: 'Max Holloway es un peleador estadounidense de MMA que actualmente compite en la división de peso pluma de la UFC, destacando en la compañía al llegar a ser campeón interino de Peso Pluma luego derrotar por TKO en el tercer asalto a Anthony Pettis en UFC 206, para luego convertirse en el campeón indiscutido de la división al vencer por TKO también en el tercer asalto al histórico José Aldo el 3 de junio de 2017.',
    openGraph: {
        title: 'Max Holloway',
        description: 'Max Holloway es un peleador estadounidense de MMA que actualmente compite en la división de peso pluma de la UFC, destacando en la compañía al llegar a ser campeón interino de Peso Pluma luego derrotar por TKO en el tercer asalto a Anthony Pettis en UFC 206, para luego convertirse en el campeón indiscutido de la división al vencer por TKO también en el tercer asalto al histórico José Aldo el 3 de junio de 2017.',
        url: 'https://fullmma.org/peleadores/max-holloway'
    }
}

export default function Holloway () {
    return(
        <main>
            <PeleadoresHero peleadoresImage={holloway} w={27} l={8} d={0} nombre='Max Holloway' apodo='BLESSED' categoria='Peso Pluma' time='2025-10-29' />
            <section className={styles.peleador__articles__container}>
                <article className={styles.peleador__article}>
                    <h2 className={styles.peleador__article__title}>Max Holloway UFC</h2>
                    <p className={styles.peleador__article__text}>Max Holloway es un peleador estadounidense de MMA que actualmente compite en la división de peso pluma de la <Link href='/articulos/ufc'>UFC</Link>, destacando en la compañía al llegar a ser campeón interino de Peso Pluma luego derrotar por TKO en el tercer asalto a <b>Anthony Pettis</b> en UFC 206, para luego convertirse en el campeón indiscutido de la división al vencer por TKO también en el tercer asalto al histórico <Link href='/leyendas/jose-aldo'>José Aldo</Link> el 3 de junio de 2017.</p>
                    <p className={styles.peleador__article__text}>Desde su llegada a la UFC hace 11 años, Holloway ha roto todo tipo de records, desde cantidad de golpes conectados en toda la UFC, hasta cantidad de bonos ganados por pelea de la noche o por actuación de la noche, siendo una leyenda vivienda del deporte y de la compañía, y uno de los peleadores más destacados de la actualidad.</p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/Fh-PoFV6Xdk?si=cEc-MIfkbA7ofnSq" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <h2 className={styles.peleador__article__title}>Max Holloway Récord</h2>
                    <p className={styles.peleador__article__text}>Max Holloway tiene un récord de 27-8. Siendo 12 de sus 27 victorias por nocaut, 2 por sumisión y 13 por decisión. Mientras que de sus 8 derrotas, 1 ha sido por sumisión, 6 por decisión, y sólo 1 por la vía del nocaut.</p>
                    <h2 className={styles.peleador__article__title}>Max Holloway Historia</h2>
                    <p className={styles.peleador__article__text}>Jerome Max Keli&apos;i Holloway nació el 4 de diciembre de 1991 en Honolu, Hawái. Viviendo una infancia en un entorno familiar complicado, debido a que cuando su padre se enteró de que su madre estaba embarazada, abandonó completamente a su familia. Pese a esto, la madre de Max era capaz de contactar con su padre cada tanto, resultando en fugaces reconciliaciones, que terminaban en el momento en que su padre le lavantaba la mano a su mujer.</p>
                    <p className={styles.peleador__article__text}>Debido a la ausencia de su padre, y a la poca responsabilidad de su madre, quien sufría de una adicción a ciertas sustancias jodidas, es que tanto Max, como sus hermanos, fueron educados principalmente por sus abuelos. El descubrir sobre el problema con las adicciones que su madre atravesaba, lejos de llevar a nuestro protagonista por el mismo camino, lo incentivo a alejarse lo más posible, dedicando su tiempo a hacer deporte en su lugar, siendo el Kickboxing el arte marcial que aprendería durante la adolescencia, y que le abriría las puertas a las MMA y a otras artes marciales que también practica como el Jiu Jitsu y el Muay Thai.</p>
                    <Image className={styles.peleador__article__image} src={traje} alt='Max Holloway con un traje de Karate' />
                    <p className={styles.peleador__article__text}>Durante su juventud, comenzaría a competir a una edad muy temprana, participando de torneos amateur en kickboxing, y posteriormente transicionando a las MMA, donde se haría con un récord de 5-0 en combates amateur. Esta excelente racha de victorias, lo incentivarían a pelear profesionalmente, debutando el 11 de septiembre de 2010, con una victoria por decisión unánime contra <b>Duke Saragosa</b>.</p>
                    <p className={styles.peleador__article__text}>Max, conseguiría ganar su siguiente combate ante <b>Bryson Kamaka</b> por KO en el primer asalto, y el siguiente por decisión dividida ante <b>Harris Sarmiento</b>, quien era un veterano con más de 50 peleas a sus espaldas, siendo en este combate, cuando Max conseguiría ganar el título de <b>X-1</b>, que es la promotora que organiza los eventos más grandes en la isla de Hawái. Holloway conseguiría ganar un combate más ante <b>Eddie Rincón</b>, a quien derrotó por decisión unánime en julio de 2011, y esta última victoria, ya con un récord profesional de 3-0, sería la que le conseguiría un contrato con la UFC.</p>
                    <p className={styles.peleador__article__text}>Max debutaría en la compañía más grande artes marciales mixtas del mundo, enfrentando a nadie menos que <Link href='/peleadores/dustin-poirier'>Dustin Poirier</Link>, el 4 de febrero de 2012 en el UFC 143, obteniendo la primer derrota de su carrera al ser sometido por el estadounidense en el primer asalto. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/bDq1OqW7aB4?si=kZXrsion6TYby0a9" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Pese a esta primer derrota, Max sería capaz de ganar su siguiente combate 4 meses después por decisión unánime ante <b>Pat Schilling</b>, ganaría por TKO en el segundo asalto ante <b>Justin Lawrence</b> en el UFC 150, y vencería por decisión dividida a <b>Leonard García</b> en el UFC 155, acumulando 3 victorias consecutivas.</p>
                    <p className={styles.peleador__article__text}>El 25 de mayo de 2013 en el UFC 160 se enfrentaría al estadounidense <b>Dennis Bermúdez</b>, contra quien caería derrotado por decisión dividida, en lo que era la segunda derrota de su carrera. Lamentablemente para Max, su siguiente combate sería ante un joven <Link href='/peleadores/conor-mcgregor'>Conor McGregor</Link>, quien en ese entonces venía de una racha de 9 victorias consecutivas, y quien derrotaría a nuestro protagonista por decisión unánime, en lo que era la segunda derrota consecutiva de Holloway, y la tercera de su carrera. </p>
                    <p className={styles.peleador__article__text}>Sin embargo, esta última derrota ante el irlandés, llevaría a nuestro protagonista a sacar lo mejor de sí, dado que desde esa fecha lograría acumular la increíble racha de 13 victorias consecutivas. Comenzando la racha con 4 peleas en el año 2014, destacando la primera de ellas ante <b>Will Chope</b>, a quien ganaría por TKO en el segundo asalto, ganando además el primer bono de su carrera al KO de la noche; la segunda ante <b>Andre Fili</b> por sumisión en el tercer asalto; la tercera ante <b>Clay Collard</b>, a quien con una patada a la cabeza y golpes dejaría KO en el tercer asalto; y la cuarta ante el sueco <b>Akira Corassani</b>, a quien dejó KO en el primer asalto de la pelea.</p>
                    <p className={styles.peleador__article__text}>En el 2015, volvería a pelear en otras 4 ocasiones, logrando una victoria ante <b>Cole Miller</b> por decisión unánime; una victoria ante el estadounidense <b>Cub Swanson</b> por sumisión en el tercer asalto, ganando un nuevo bono a la actuación de la noche; ganaría su pelea ante el histórico brasileño <Link href='/peleadores/charles-oliveira'>Charles Oliveira</Link> por TKO en el primer asalto, luego de que durante la pelea el brasileño sufriera una lesión en medio del combate; por último, en diciembre de ese año, pelearía ante <b>Jeremy Stephens</b>, derrotándolo por decisión unánime. </p>
                    <p className={styles.peleador__article__text}>El 2016 sería un año histórico y muy importante para Max Holloway, dado que primero participaría del UFC 199 el 4 de junio enfrentando al estadounidense <b>Ricardo Lamas</b>, a quien ganaría por decisión unánime luego de 3 asaltos. </p>
                    <p className={styles.peleador__article__text}>Ya con 9 victorias consecutivas, y un récord profesional de 16-3, se ganaría la oportunidad de disputar el Campeonato Interino de Peso Pluma, ante el histórico peleador <b>Anthony Pettis</b>, el día 10 de diciembre de 2016 en el UFC 206, consiguiendo derrotar a su rival por TKO en el tercer asalto de la pelea, ganando nuevamente el bono a La Actuación de la Noche. Convirtiéndose en el campeón interino de la división de peso pluma con sólo 25 años. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/2uw6GoqMHRQ?si=N7HZoNSD59VYS-8H" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Esta victoria, le daría la oportunidad de pelear por unificar el título, ante quien posiblemente sea el GOAT de la división de peso pluma de la UFC, el brasileño <Link href='/leyendas/jose-aldo'>José Aldo</Link>. La pelea entre Holloway y Aldo estaría programada para el 3 de junio de 2017 en el UFC 2012, y terminaría con una actuación espectacular por parte de nuestro protagonista, quien lograría una victoria por TKO en el tercer asalto, unificando el cinturón, convirtiéndose en el campeón indiscutido de la división, y ganando un nuevo bono, esta vez por protagonizar la Pelea de la Noche.</p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/DPRgp2dR444?si=3vOA_8P0N9dUiYbg" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Como primera defensa por parte del hawaiano, se programaría una revancha ante el excampeón José Aldo, a quien debería enfrentar el 2 de diciembre de 2017, encabezando el UFC 218 en Detroit, Míchigan. Aquella pelea terminaría de igual forma que la primera, con un Max que sería capaz de noquear a su rival en el tercer asalto, siendo esta su primer defensa exitosa del título de las 145lbs. </p>
                    <p className={styles.peleador__article__text}>En su siguiente combate, Max Holloway realizaría una de sus actuación más memorables para los fans de las MMA, cuando enfrentando a <b>Brian Ortega</b> el día 8 de diciembre de 2018, le daría literalmente una clase de boxeo magistral, siendo tan superior en el striking a su rival, que incluso paró de pelear durante unos segundos para corregir la técnica de boxeo de su rival. Esta impresionante actuación culminaría luego de finalizado el cuarto asalto, cuando Max se llevaría la victoria por TKO debido a una parada médica, dado que su rival ya no estaba en condiciones de seguir peleando un asalto más. Por esta pelea, Holloway ganaría los bonos a La Actuación de la Noche y a La Pelea de la Noche, reteniendo el título y concretando su segunda defensa del cinturón. </p>
                    <p className={styles.peleador__article__text}>Luego de un más que notable desempeño en la división de 145lbs, a Max se le presentaría la oportunidad de subir de división para disputar el título de campeón de la división de peso ligero el 13 de abril de 2019 en el UFC 236, donde se vería frente a frente ante un viejo conocido, <Link href='/peleadores/dustin-poirier'>Dustin Poirier</Link>, a quien como mencioné, ya había enfrentado en su primer combate en la UFC, cuando Poirier aún competía en el peso pluma. </p>
                    <p className={styles.peleador__article__text}>Holloway iba en busca de lograr el doble campeonato, pero lamentablemente para él, cuando llegara el día de la pelea, sufriría el estar compitiendo en una división superior por primera vez, que terminaría pagando con una derrota por decisión unánime, que por lo menos le valdría para ganar el bono a La Pelea de la Noche. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/l_BIP8W7vzE?si=gPxGPZ_uWyzyx03A" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Pese a esto, Max volvería a demostrar porque es uno de los mejores peleadores de la UFC, al defender su título de peso pluma unos 3 meses después ante un rival durísimo como lo es <b>Frankie Edgard</b>, a quien el 27 de julio  de 2019 conseguiría vencer por decisión unánime, en lo que era su tercer defensa consecutiva del título. </p>
                    <p className={styles.peleador__article__text}>El 14 de diciembre de ese mismo año, a Max le tocaría defender su título contra quien se convertiría en su caballo negro, enfrentando al australiano <Link href='/peleadores/alexander-volkanovski'>Alexander Volkanovski</Link>, quien luego de 5 asaltos derrotaría a nuestro protagonista, desponjándolo del título de las 145lbs. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/t_5G7bGTPxs?si=G7DjC2crMkmAba31" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Debido a la excelente trayectoria de Max, y a que la pelea había sido lo bastante cerrada como para requerir de una segunda parte, es que se programó una revancha inmediata entre los peleadores, con fecha para el 11 de julio de 2020 en el UFC 251. Aunque aquella noche las cosas no saldrían muy diferentes, puesto que en lo que fue una pelea bastante cerrada en la que se puede discutir el resultado de la misma,luego de 5 asaltos los jueces dieron por ganador a Alexander Volkanovski por decisión dividida. </p>
                    <p className={styles.peleador__article__text}>Holloway se mantendría activo, enfrentado a 2 importantes prospectos en el año 2021, enfrentando primero en enero al estadounidense <b>Calvin Kattar</b> en un evento encabezado por ellos 2, donde luego de 5 asaltos conseguiría llevarse la victoria por decisión unánime y ganar un nuevo bono a la Pelea de la Noche. Y luego se enfrentaría al mexicano <b>Yair Rodríguez</b> el 13 de noviembre, a quien luego de 5 asaltos vencería por decisión unánime, ganando otra vez el bono a la Pelea de la Noche.</p>
                    <p className={styles.peleador__article__text}>Con estas 2 contundentes victorias, el nacido en Hawai había hecho méritos suficientes para disputar nuevamente el cinturón que una vez supo ser suyo a Volkanovski, por lo que se programó una pelea para el 2 de julio de 2022 en el UFC 276. Pero lamentablemente para Max, volvería a caer derrotado por tercera vez ante el mismo rival, esta vez de forma contundente, por lo que Alex se terminó llevando la victoria por decisión unánime. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/vE-Vu1EA94A?si=PH-XWYPvDY4YakWd" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Aunque volver a tener la oportunidad de pelear una vez más por el título ya iba a ser super difícil, al haber perdido 3 veces ante el campeón, Max a lo largo de su carrera siempre fue un peleador activo, por lo que en 2023 tendría otras 2 peleas: siendo la primera ante un nuevo prospecto, como lo era el inglés <b>Arnold Allen</b>, a quien luego de 5 asaltos conseguiría derrotar de forma contundente por decisión unánime; y siendo el segundo combate ante el veterano e histórico de la división, el corenao <b>Chan-sung Jung (The Korean Zombie)</b>, en la que era su pelea del retiro, Max conseguiría dejarlo KO en el tercer asalto, ganando un nuevo bono a la actuación de la noche. </p>
                    <p className={styles.peleador__article__text}>El 13 de abril de 2024, en el <Link href='/covertura-ufc/ufc300-main-event'>UFC 300</Link>, Max Holloway tendría otro de esos desempeños que quedan para la historia de las MMA. Para esa fecha, al Max ya quedar sin rivales en su competición, aceptaría subir de categoría nuevamente para enfrentar a uno de los mejores pesos ligeros del momento y de la historia, como lo es <Link href='/peleadores/justin-gaethje'>Justin Gaethje</Link>, para disputar el cinturón <b>BMF</b>. </p>
                    <p className={styles.peleador__article__text}>En lo que fue una tremenda pelea, que de hecho acabaría siendo elegida La Pelea de la Noche, luego de dominar durante los 5 asaltos del combate, Max Holloway apuntaría al centro del octágono faltando 10 segundos, para comenzar un intercambio de golpes ante su rival. En este intercambio de golpes, Max dejaría KO a Gaethje exactamente en el minuto 4:59, empatando la finalización más tardía de la historia de la UFC, en lo que sin dudas se convertirá en uno de los momentos más memorables de la historia de la compañía y del deporte. Por esta actuación además, Holloway ganaría el bono a la Actuación de la Noche.</p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/h9KBcib8pHc?si=tYF6oJSZcb-HgaSX" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Debido a esta meritoria racha de victorias, y que el cinturón de la división de peso pluma había cambiado de manos, es que a Max se le presentaría la oportunidad de enfrentar al nuevo campeón <Link href='/peleadores/ilia-topuria'>Ilia Topuria</Link> el día 26 de octubre de ese mismo año en el <Link href='/covertura-ufc/ufc308'>UFC 308</Link>. Lamentablemente para él, sufriría una dolorosa derrota por KO en el tercer asalto, siendo esta la primera vez que perdía por esta vía. </p>
                    <EndArticle />
                </article>
                <AsideChamps />
            </section>
        </main>
    )
}