import PeleadoresHero from '@/app/peleadores/components/PeleadoresHero'
import adesanya from '@/assets/peleadores__images/0-100/20-30/israel-adesanya/israel-adesanya.png'
import styles from '@/app/peleadores/components/peleador.module.css'
import AsideChamps from '@/app/components/asides/AsideChamps'
import Link from 'next/link'
import type { Metadata } from 'next'
import EndArticle from '@/app/components/EndArticle'

export const metadata: Metadata = {
    title: 'Israel Adesanya',
    description: 'Israel Adesanya es un luchador nacido en Nigeria que compite en la UFC y es sin duda uno de los mejores luchadores de la historia de los peso medio de la compañía desde que llegara e hiciera su debut en febrero de 2018, cuando venció por TKO al australiano Rob Wilkinson. El nacionalizado neozelandés supo ser campeón de la compañía en 2 ocasiones y pudo defender su cinturón en varias ocasiones.',
    openGraph: {
        title: 'Israel Adesanya',
        description: 'Israel Adesanya es un luchador nacido en Nigeria que compite en la UFC y es sin duda uno de los mejores luchadores de la historia de los peso medio de la compañía desde que llegara e hiciera su debut en febrero de 2018, cuando venció por TKO al australiano Rob Wilkinson. El nacionalizado neozelandés supo ser campeón de la compañía en 2 ocasiones y pudo defender su cinturón en varias ocasiones.',
        url: 'https://fullmma.org/peleadores/israel-adesanya'
    }
}

export default function Prochazka () {
    return(
        <main>
            <PeleadoresHero peleadoresImage={adesanya} w={24} l={5} d={0} nombre='Israel Adesanya' apodo='The Last Stylebender' categoria='Peso Medio' />
            <section className={styles.peleador__articles__container}>
                <article className={styles.peleador__article}>
                    <h2 className={styles.peleador__article__title}>Israel Adesanya UFC</h2>
                    <p className={styles.peleador__article__text}>Israel Adesanya es un luchador nacido en Nigeria que compite en la <Link href='/articulos/ufc'>UFC</Link> y es sin duda uno de los mejores luchadores de la historia de los peso medio de la compañía desde que llegara e hiciera su debut en febrero de 2018, cuando venció por TKO al australiano <b>Rob Wilkinson</b>. </p>
                    <p className={styles.peleador__article__text}>Su gran trayectoria en el kickboxing han marcado lo que es su estilo en las MMA, siendo de los mejores strikers que ha visto la UFC. Fue uno de los campeones más dominantes que han exisitido en la división de peso medio de la compañía, cosa que sumado a su personalidad, lo han posicionado como uno de los peleadores más mediáticos de la década. </p>
                    <h2 className={styles.peleador__article__title}>Israel Adesanya Récord</h2>
                    <p className={styles.peleador__article__text}>Israel Adesanya en sus 28 peleas como profesional ha cosechado un récord de 24-5. Siendo 16 de sus victorias por la vía del nocaut, mientras que 8 de sus victorias fueron por decisión. Mientras que de sus 5 derrotas, 2 fueron por nocaut, 1 fue por sumisión y 2 fueron por decisión.</p>
                    <h2 className={styles.peleador__article__title}>Israel Adesanya Biografía</h2>
                    <p className={styles.peleador__article__text}>Israel Mobolaji Temitayo Odunayo Oluwafemi Owolabi Adesanya nació el 22 de julio de 1989 en la ciudad de Nigeria, Lagos. Es el mayor de 5 hermanos y desde muy pequeño comenzó a entrenar Taewkwondo, hasta que su madre lo obligó a dejar este deporte cuando sufrió una lesión. Durante su niñez se trasladó un tiempo a Ghana, pero como sus padres querían que recibiera una buena educación, cuando Israel tenía 10 años se mudaron a Nueva Zelanda. </p>
                    <p className={styles.peleador__article__text}>Pese a esa corta experiencia que Adesanya había tenido entrenando Taekwondo, lo cierto es que nunca estuvo muy interesado en las artes marciales, sino más bien disfrutaba de ver anime, con series como <b>Death Note</b> o <b>Naruto</b>. Durante su secundaria fue víctima de bullyng, factor que él mismo atribuye que lo inspiró a entrenar artes marciales, comenzando a practicar kickboxing a los 18 años.</p>
                    <h2 className={styles.peleador__article__title}>Israel Adesanya Kickboxing</h2>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/KfGqlQrt5EA?si=wV6FAheMiY62hywF" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Finalmente Adesanya decidiría abandonar sus estudios universitarios para perseguir una carrera como kickboxer, habiendo acumulado un récord amateur de 32-0 iría a competir en profesionalmente en China. A los 21 años caería bajo la tutela de <b>Eugene Bareman</b>, con quien comenzaría a entrenar artes marciales mixtas, y con quien conocería a futuras estrellas de la UFC, como <b>Dan Hooker</b> o como el excampeón <Link href='/peleadores/alexander-volkanovski'>Alexander Volkanovski</Link>.</p>
                    <p className={styles.peleador__article__text}>Resumiendo bastante su carrera como kickboxer profesional, según su página de <a href='https://en.wikipedia.org/wiki/Israel_Adesanya' target='_Blank'>Wikipedia</a> en inglés, tiene un récord de 75-5, siendo 29 de sus victorias por la vía del nocaut.</p>
                    <p className={styles.peleador__article__text}>En 2016, luego de vencer en las semifinales al canadiense <b>Robert Thomas</b> por decisión unánime, se enfrentaría al neerlandés <b>Yousri Belgaroui</b> a quien vencería por decisión dividida, ganando el <b>Glory Middleweight Contender Tournament</b>, convirtiéndose en campeón de kickboxing en su división.</p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/Fmbdl9xJZvc?si=NhmKPnqc2759YxAA" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>En este deporte y en esta etapa de su vida, se encontraría con quien sería uno de sus mayores rivales como deportista en general, dado que cuando tenía un abultado récord positivo con sólo 4 derrotas por decisión, ya habiendo sido campeón del deporte, se enfrentaría a un luchador que le propinaría su primer KO, <Link href='/peleadores/alex-pereira'>Alex Pereira</Link>, a quien ya había enfrentado en el pasado perdiendo por decisión, el 4 de marzo de 2017 lo velvería a enfrentar y en el tercer asalto, con uno de sus peligrosísimos ganchos con la izquierda, conectó a nuestro protagonista dejándolo KO.</p>
                    <h2 className={styles.peleador__article__title}>Israel Adesanya MMA</h2>
                    <p className={styles.peleador__article__text}>Luego de aquella dolorosa derrota contra Alex Pereira, Adesanya se retiraría del kickboxing para dedicarse de lleno a su carrera como luchador de MMA. En este deporte haría su debut el 24 de marzo de 2012 contra el neozelandés <b>James Griffiths</b>, a quien vencería por TKO a los 2 minutos del primer asalto. </p>
                    <p className={styles.peleador__article__text}>Israel mantendría un extenso récord invicto donde ganaría todas sus peleas por la vía del nocaut, ganando el título de AFC de peso medio al vencer por TKO al estadounidense <b>Melvin Guillard</b> y el título vacante de Hex Fighting Series al vencer a <b>Stuart Dare</b> por KO en el primer asalto, antes de llegar a la UFC.</p>
                    <p className={styles.peleador__article__text}>Llegando con un récord perfecto de 11-0, el 11 de febrero de 2018 Adesanya debuta en la UFC contra <b>Rob Wilkinson</b> en el UFC 221, venciendo por TKO en el segundo asalto, y ganando el bono a la actuación de la noche.</p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/zea_QpSpfGs?si=gXDrXtsJ9jDbf7F7" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Adesanya ganaría sus primeros 5 combates en la compañía antes de ganarse una oportunidad de pelear por el título, siendo la última de estas victorias contra el legendario luchador de la UFC y de peso mediano <Link href='/leyendas/anderson-silva'>Anderson Silva</Link>, a quien luego de 3 asaltos vencería por decisión unánime, siendo esta elegida la pelea de la noche.</p>
                    <p className={styles.peleador__article__text}>El 12 de abril de 2019 se enfrentaría al americano <b>Kelvin Gastelum</b> en el UFC 236, por el título interino de la división de peso medio. Aquella noche nuestro protagonista vencería por decisión unánime luego de los 5 asaltos, ganando el título y además, siendo elegida aquella como la pelea del año tiempo después. </p>
                    <p className={styles.peleador__article__text}>El 5 de octubre de 2019 se enfrentaría al campeón <b>Robert Whittaker</b> para unificar cinturones en el evento <b>UFC 243</b>. Aquella noche Israel sería capaz de noquear a Whittaker en el segundo asalto, convirtiéndose en el campeón indiscutido y ganando el bono a la actuación de la noche.</p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/ZK5Mjq0UGoE?si=ZUIw86Pk7M9wwIU4" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Su primera defensa sería contra <b>El Soldado de Dios</b>, el cubano <b>Yoel Romero</b>, a quien en lo que fue un combate bastante decepcionante para muchos, terminaría venciendo por decisión unánime, reteniendo el título. Su segunda defensa sería contra el brasileño <b>Paulo Costa</b> en septiembre de 2020 en el UFC 253, ganando esta vez por TKO en el segundo asalto, ganando nuevamente el bono a la actuación de la noche.</p>
                    <p className={styles.peleador__article__text}>La primer derrota de su carrera llegaría cuando intentaría subir de categoría en busca del doble campeonato, enfrentando al entonces campeón <b>Jan Blachowicz</b>, contra quien caería derrotado por decisión unánime.</p>
                    <p className={styles.peleador__article__text}>Seguiría defendiendo su cinturón en 2 revanchas contra el italiano <b>Marvin Vettori</b> y contra el australiano <b>Robert Whittaker</b>, venciendo en ambas peleas por decisión unánime. Luego tendría una pelea contra el estadounidense <b>Jared Cannonier</b> a quien también conseguiría vencer por decisión unánime.</p>
                    <p className={styles.peleador__article__text}>Para desgracia de nuestro protagonista, el mismo <Link href='/peleadores/alex-pereira'>Alex Pereira</Link> que lo había vencido 2 veces en kickboxing, propinándole el único KO de su carrera, había decidido seguir el mismo camino que Izzy persiguiendo una carrera en las MMA. Se enfrentarían en noviembre de 2022 y quien a esta altura se estaba convirtiendo en el &quot;Coco&quot; de Adesanya, lograría nuevamente, conectar un KO en el último asalto de la pelea, perdiendo por primera vez una defensa del título.</p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/l8s2fsfIpUA?si=It6BA8RO-ENUjT75" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Luego de esta derrota, Israel Adesanya se tomaría 6 meses para volver a pelear, consiguiendo una revancha para el 8 de abril de 2023 en el UFC 287. En esta ocasión, en el segundo asalto de la pelea, el nacido en Nigeria lograría vengar sus 3 derrotas conectando unos golpes que dejarían KO al brasileño, recuperando su título y ganando el bono a la actuación de la noche. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/IVXgOlEOF-Q?si=HtCjoAZxJ8xdz7Dh" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>A los pocos meses, Izzy ya se sentía listo para volver a defender su título, por lo que se programó una pelea para el 9 de septiembre de 2023 en Sídney, Australia, con la idea de que Adesanya encabece el UFC 293. Sin embargo, orignalmente se había planificado una pelea entre <Link href='/peleadores/du-plessis'>Dricus Du Plessi</Link> contra el nigeriano, ya que además era un combate entre 2 peleadores que ya tenían &quot;beef&quot; entre sí.</p>
                    <p className={styles.peleador__article__text}>Debido a esto, se buscó a un reemplazo de último momento, y quien terminó aceptando pelear fue <Link href='/peleadores/sean-strickland'>Sean Strickland</Link>, quien en ese momento estaba ranqueado #5 y que había peleado hacía un mes para cuando le avisaron que tenía que pelear de nuevo. Para sorpresa de todos, el retador lograría dominar de principio a fin a un campeón que durante años parecía invencible, teniendo como resultado que luego de los 5 asaltos que duró el combate, Sean Strickland ganara por decisión unánime convirtiéndose en el neuvo campeón.</p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/m3jNtOxIyDA?si=WBS-rrUAHLe61REL" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Pese a la derrota, menos de un año después, el día 18 de agosto de 2024 en el <Link href='/covertura-ufc/ufc305'>UFC 305</Link> organizado nuevamente en Australia, se lo programaría para volver a pelear por el título de la división de peso medio de la UFC, esta vez, ante el nuevo campeón <Link href='/peleadores/du-plessis'>Dricus Du Plessis</Link>. Pero lamentablemente para nuestro protagonista, en lo que estaba siendo una buena pelea para Adesanya, terminó por caer derrotado al ser sometido en el cuarto asalto de la pelea por el sudafricano. </p>
                    <EndArticle />
                </article>
                <AsideChamps />
            </section>
        </main>
    )
}