import styles from './coverturaUFC.module.css'
import ArticlePreview from '../articulos/components/ArticlePreview'
/* UFC IMAGES */
/* 0-15 */
import ufc297 from '@/assets/covertura_ufc/ufc/0-100/0-15/ufc297.jpg'
import ufc298 from '@/assets/covertura_ufc/ufc/0-100/0-15/ufc298_preview.jpg'
import ufc299 from '@/assets/covertura_ufc/ufc/0-100/0-15/ufc299.jpg'
import ufc300MainEvent from '@/assets/covertura_ufc/ufc/0-100/0-15/ufc300.jpeg'
import ufc301 from '@/assets/covertura_ufc/ufc/0-100/0-15/ufc301-preview.jpg'
import ufc302 from '@/assets/covertura_ufc/ufc/0-100/0-15/ufc302-preview.jpg'
import ufc303 from '@/assets/covertura_ufc/ufc/0-100/0-15/ufc303-preview.jpg'
import ufc304 from '@/assets/covertura_ufc/ufc/0-100/0-15/ufc304.jpg'
import ufc305 from '@/assets/covertura_ufc/ufc/0-100/0-15/ufc305.jpg'
import ufc306 from '@/assets/covertura_ufc/ufc/0-100/0-15/ufc306.jpg'
import ufc307 from '@/assets/covertura_ufc/ufc/0-100/0-15/ufc307.jpg'
import ufc308 from '@/assets/covertura_ufc/ufc/0-100/0-15/ufc308.jpg'
import ufc309 from '@/assets/covertura_ufc/ufc/0-100/0-15/ufc309.jpg'
import ufc310 from '@/assets/covertura_ufc/ufc/0-100/0-15/ufc310.jpg'
import ufc311 from '@/assets/covertura_ufc/ufc/0-100/0-15/ufc311.jpg'
/* 15-30 */
import ufc312 from '@/assets/covertura_ufc/ufc/0-100/15-30/ufc312.jpg'
/* UFC FIGHT NIGHT IMAGES */
import whittakerVSaliskerov from '@/assets/covertura_ufc/fight_night/0-100/0-15/whittaker-vs-aliskerov.jpg'
import lewisVsNascimento from '@/assets/covertura_ufc/fight_night/0-100/0-15/lewis-vs-nascimento-preview.jpg'
import cannonierVSimano from '@/assets/covertura_ufc/fight_night/0-100/0-15/fightnight-cannonier-imanov-preview.jpg'
import sandhagenVSnurmagomedov from '@/assets/peleadores__images/0-100/30-40/umar-nurmagomedov/umar_nurmagomedov-card.jpg'
import moicanoVSsaintdenis from '@/assets/covertura_ufc/fight_night/0-100/0-15/moicano_vs_saintdenis.jpg'
import yanVSfigueiredo from '@/assets/covertura_ufc/fight_night/0-100/0-15/yan-vs-figueiredo.jpg'
import ufcTampa from '@/assets/covertura_ufc/fight_night/0-100/0-15/covington-vs-buckley.jpg'
import ufcVegas101 from '@/assets/covertura_ufc/fight_night/0-100/0-15/fight-night-dern-ribas-2.jpg'
import ufcSaudiArabia from '@/assets/covertura_ufc/fight_night/0-100/0-15/adesanya_imavov.jpg'
import ufcVegas102 from '@/assets/covertura_ufc/fight_night/0-100/0-15/cannonier_rodrigues.jpg'
import ufcSeattle from '@/assets/covertura_ufc/fight_night/0-100/0-15/ufc_seattle.jpg'


export default function CoverturaUFC () {
    return(
        <main className={styles.covertura__container}>
            <h2 className={styles.covertura__subtitle}>UFC Numerado</h2>
            <section className={styles.covertura__articles__container}>
                <ArticlePreview img={ufc312} url='/covertura-ufc/ufc312' title='UFC 312: ¡Dricus Du Plessis Derrota a Sean Strickland y Retiene el Cinturón de Peso Mediano!' author={null} text='¡Aleksandre Topuria debuta con victoria ante ante Colby Thicknesse! ¡Zhang Weili derrota a Tatiana Suarez y retiene su cinturón!' date='08/02/2025' />
                <ArticlePreview img={ufc311} url='/covertura-ufc/ufc311' title='UFC 311: ¡Islam Makhachev Somete a Renato Moicano en el Primer Asalto! ¡Merab Dvalishvili Derrota a Umar Nurmagomedov y Retiene Cinturón de Peso Gallo!' author={null} text='Ailín Pérez logra una victoria por decisión unánime ante Karol Rosa y se Mete en el top 10. Jailton Almeida gana por nocaut a Spivac. Jiri Prochazka Noquea a Jamahal Hill.' date='18/01/2025' />
                <ArticlePreview img={ufc310} url='/covertura-ufc/ufc310' title='UFC 310: ¡Alexandre Pantoja vs Kai Asakura por el Campeonato de Peso Mosca de UFC! ¡Shavkat Rakhmonov vs Ian Garry!' author={null} text='Movsar Evloev Gana su Pelea por Decisión. Vicente Luque Logra una Victoria por Sumisión en el Primer Asalto. Además Dominick Reyes Derrota a Anthony Smith por TKO en el Segundo Asalto' date='09/12/2024' />
                <ArticlePreview img={ufc309} url='/covertura-ufc/ufc309' title='UFC 309: ¡Jon Jones Noquea a Stipe Miocic en el Tercer Asalto en su Primer Defensa del Título! ¡Charles Oliveira Derrota a Michael Chandler por Decisión en La Pelea de la Noche!' author={null} text='¡Bo Nical derrota a Paul Craig y mantiene su invicto de 7-0! Además el brasileño Mauricio Ruffy vence al peruano James Llontop por decisión en su segunda pelea en la UFC.' date='16/11/2024' />
                <ArticlePreview img={ufc308} url='/covertura-ufc/ufc308' title='UFC 308: ¡Ilia Topuria Noquea a Max Holloway en el Tercer Asalto! ¡Khamzat Chimaev Somete a Robert Whittaker en el Primer Asalto!' author={null} text='Tenemos un tremendo evento que además cuenta con el regreso al octágono de Shara Magomedov, con la pelea de Dan Ige y Lerone Murphy, y la pelea entre Ankalaev y Rakic acompañando la cartelera estelar.' date='26/10/2024' />
                <ArticlePreview img={ufc307} url='/covertura-ufc/ufc307' title='UFC 307: ¡Alex Pereira Noquea a Khalil Rountree En El Cuarto Asalto y Sigue Siendo Campeón! ¡Julianna Peña es Nueva Campeona de UFC al Derrotar a Raquel Pennington!' author={null} text='Kayla Harrison gana luego de una actuación dominante en su pelea por decisión unánime. Roman Dolidze gana por parada médica luego de una lesión de Kevin Holland. Mario Bautista gana su pelea contra José Aldo por decisión dividida.' date='05/10/2024' />
                <ArticlePreview img={ufc306} url='/covertura-ufc/ufc306' title='UFC 306: ¡Merab Dvalisvhili Nuevo Campeón de Peso Gallo! ¡Valentina Shevchenko Vuelve a Ser Campeona al Derrotar Por Decisión a Alexa Grasso!  ¡Esteban Ribovics Gana en un Peleón al Mexicano Daniel Zellhuber!' author={null} text='¡Ronaldo Rodríguez Gana por Decisión ante Ode Osbourne! ¡Diego Lopes Derrota a Brian Ortega por Decisión Unánime! ¡Raúl Rosas Jr. Logra La Primer Victoria de la Noche en La Esfera!' date='15/09/2024' />
                <ArticlePreview img={ufc305} url='/covertura-ufc/ufc305' title='UFC 305: ¡Dricus Du Plessis Derrota Por Sumisión a Israel Adesanya!¡Kai Kara-France Noquea a Steve Erceg en el Primer Asalto!' author={null} text='¡Carlos Prates deja KO a Li Jingliang en el segundo asalto! ¡Dan Hooker consigue una victoria ante Mateusz Gamrot!' date='18/08/2024' />
                <ArticlePreview img={ufc304} url='/covertura-ufc/ufc304' title='UFC 304: ¡Belal Muhammad Vence Por Decisión Unánime a Leon Edwards y es Nuevo Campeón! ¡Tom Aspinall Noquea a Curtis Blaydes en el Primer Asalto!' author={null} text='¡Paddy Pimblett somete a Bobby Green en el primer asalto de la pelea! Tom Aspinall logra otra victoria por nocaut en su revancha ante Blaydes. Belal Muhammad es nuevo campeón de peso wélter en la UFC.' date='27/07/2024' />
                <ArticlePreview img={ufc303} url='/covertura-ufc/ufc303' title='UFC 303: ¡Alex Pereira Noquea a Jiri Prochazka en el Segundo Asalto!¡Diego Lopes Vence a Dan Ige Que Tomó la Pelea con 4 Horas de Antelación!' author={null} text='En esta noche de MMA tenemos peleas fantásticas, con la pelea por el título de semipesados como evento estelar de esta jornada, y con la pelea inédita de Diego Lopes y de Dan Ige, que aceptó combatir unas pocas horas antes de la pelea.' date='29/06/2024' />
                <ArticlePreview img={ufc302} url='/covertura-ufc/ufc302' title='UFC 302: ¡Islam Makhachev Somete a Poirier en el Último Asalto de la Pelea!' author={null} text='Islam Makhachev somete a Dustin Poirier en lo que hasta ahora parecería ser la última pelea de su carrera. Además Sean Strickland se lleva una esperable victoria contra Paulo Costa por decisión unánime.' date='02/06/2024' />
                <ArticlePreview img={ufc301} url='/covertura-ufc/ufc301' title='UFC 301: ¡José Aldo se Retira con una Victoria contra Jonatha Martinez y Alexandre Pantoja Retiene su Título!' author={null} text='José Aldo se retira con victoria de la UFC enfrentando a un peleador ranqueado con sus 37 años de edad, y Pantoja es capaz de retener el cinturón en su primera defensa.' date='05/05/2024' />
                <ArticlePreview img={ufc300MainEvent} url='/covertura-ufc/ufc300-main-event' title='UFC 300: ¡Alex Pereira Noquea en el Primer Asalto a Hill! ¡Max Holloway Noquea a Gaethje en el Último Segundo de la Pelea!' author={null} text='Alex Pereira defiende su cinturón ante Jamahal Hill noqueando en el primer asalto. Max Holloway se convierte en el nuevo BMF al noquear a Justin Gaethje en el último asalto. Además Zhang Weili, Bo Nickal y Arman Tsarukyan ganan sus peleas.' date='14/04/2024' />
                <ArticlePreview img={ufc299} url='/covertura-ufc/ufc299' title='UFC 299: ¡Sean Omalley vence a Chito y Sigue Siendo Campeón!¡Dustin Poirier Gana por Nocaut en el Segundo Asalto!' author={null} text='Además, Michael Venom Page logra una victoria en su debut en la UFC y Jack Della Maddalena logra una victoria por nocaut ante Gilbert Burns que lo hace escalar en los rankings.' date='10/03/2024' />
                <ArticlePreview img={ufc298} url='/covertura-ufc/ufc298' title='UFC 298: ¡Ilia Topuria Noquea a Volkanovski y es el Nuevo Campeón de UFC!' author={null} text='En una noche histórica fuimos testigos de como el peleador español Ilia Topuria, noquea y acaba con el dominio de Volkanovski en la división de Peso Pluma de la UFC.' date='18/02/2024' />
                <ArticlePreview img={ufc297} url='/covertura-ufc/ufc297' title='UFC 297: ¡Dricus Du Plessis y Raquel Pennington Nuevos Campeones de UFC!' author={null} date='21/01/2024' text='En una pelea que se terminó con polémica por la decisión de los jueces, Du Plessis se consagra como nuevo campeón de peso mediano en UFC.' />
            </section>
            <h2 className={styles.covertura__subtitle}>UFC Fight Night</h2>
            <section className={styles.covertura__articles__container}>
                <ArticlePreview img={ufcSeattle} url='/covertura-ufc/fight-night-cejudo-song' title='UFC Seattle: ¡Song Yadong Derrota a Henry Cejudo Por Decisión Técnica Luego de Parada Médica!' author={null} text='¡Jean Silva Noquea a Melsik Baghdasaryan en el Primer Asalto! !Anthony Hernandez Derrota a Brendan Allen por Decisión Unánime! ' date='22/02/2025' />
                <ArticlePreview img={ufcVegas102} url='/covertura-ufc/fight-night-cannonier-rodrigues' title='UFC VEGAS 102: ¡Jared Cannonier Noquea a Gregory Rodrigues en el Cuarto Asalto!' author={null} text='Noche de UFC en Las Vegas: ¡Youssef Zalal derrota a Calvin Kattar y se mete en los rankings de la UFC!' date='15/02/2025' />
                <ArticlePreview img={ufcSaudiArabia} url='/covertura-ufc/fight-night-adesanya-imavov' title='UFC SAUDI ARABIA: ¡Nassourdine Imavov Noquea a Israel Adesanya en el Segundo Asalto! ¡Michael Venom Page le Quita el Invicto a Shara Bullet!' author={null} text='Noche de UFC en Arabia Saudita, que además nos trae la pelea entre Shara Magomedov y Michael Venom Page, y la pelea de peso pesado entre Pavlovich y Jairzinho' date='01/02/2025' />
                <ArticlePreview img={ufcVegas101} url='/covertura-ufc/fight-night-dern-ribas-2' title='UFC VEGAS 101: ¡Mackenzie Dern Somete a Amanda Ribas al Final del Tercer Asalto! ¡Santiago Ponzinibbio Vence Por TKO a Carlston Harris en el Tercer Asalto!' author={null} text='Roman Kapylov noquea a Chris Curtis faltando un segundo para que termine la pelea. ¡Cesar Almeida deja KO a su rival en el primer asalto!' date='11/01/2025' />
                <ArticlePreview img={ufcTampa} url='/covertura-ufc/fight-night-covington-buckley' title='UFC TAMPA: ¡Joaquin Buckley Gana a Colby Covington por TKO! ¡Joel Álvarez Noquea a Drakkar Klose!' author={null} text='Manel Kape logra una victoria por Nocaut en el tercer asalto de la pelea. Cub Swanson derrota a Billy Quarantillo por nocaut en el tercer asalto en la pelea de la noche. ' date='14/12/2024' />
                <ArticlePreview img={yanVSfigueiredo} url='/covertura-ufc/fight-night-yan-figueiredo' title='UFC CHINA: ¡Yan Xiaonan Derrota a Tabatha Ricci! ¡Petr Yan Derrota a Deiveson Figueiredo en la Pelea de la Noche!' author={null} text='Carlos Ulberg derrota a Vokan Oezdemir por decisión en una excelente actuación por su parte. Gabriella Fernandes da la sorpresa y Somete a Wang Cong. Muslim Salikhov noquea a Song Kenan en el primer asalto.' date='23/11/2024' />
                <ArticlePreview img={moicanoVSsaintdenis} url='/covertura-ufc/fight-night-moicano-saintdenis' title='UFC FRANCIA: ¡Renato Moicano Derrota a Benoit Saint Denis TKO en el Segundo Asalto! ¡Imavov Derrota a Allen Por Decisión Unánime! ¡Ailín Pérez Somete en el Primer Asalto a Zhelezniakova!' author={null} text='Noche de UFC en Francia donde tuvimos la victoria de la argentina Ailín Pérez en el primer asalto por sumisión y la victoria del español Daniel Barez por decisión unánime.' date='28/09/2024' />
                <ArticlePreview img={sandhagenVSnurmagomedov} url='/covertura-ufc/fight-night-sandhagen-nurmagomedov' title='UFC FIGHT NIGHT: ¡Umar Nurmagomedov Gana Por Decisión Unánime a Cory! ¡El Ecuatoriano Marlon Vera Cae Derrotado por el Brasileño Figueiredo Por Decisión Unánime!' author={null} text='Joel Álvarez gana por nocaut en el tercer asalto de la pelea. Tony Ferguson vuelve a perder una vez más, cayendo derrotado en esta ocasión ante Michael Chiesa, y dejando entrever su retiro. Shara Bullet gana por decisión unánime su tercer pelea en la UFC.' date='03/08/2024' />
                <ArticlePreview img={whittakerVSaliskerov} url='/covertura-ufc/fight-night-whittaker-aliskerov' title='UFC Fight Night: ¡Whittaker Noquea en el Primer Asalto a Aliskerov! ¡Shara Bullet Noquea a su Rival en el Tercer Asalto!' author={null} text='Un evento donde contamos con emocionantes combates como el que tendran Johnny Walker y Volkan Oezdemir abriendo la cartelera principal, la pelea coestelar entre Sergei Pavlovich y Alexander Volkov, y el evento principal protagonizado por Robert Whittaker y Ikram Aliskerov.' date='22/06/2024' />
                <ArticlePreview img={cannonierVSimano} url='/covertura-ufc/fight-night-cannonier-imanov' title='UFC Fight Night: ¡Imanov Noquea a Canonnier! ¡Dominick Reyes Gana por Nocaut en el Primer Asalto! y ¡Raul Rosas JR Somete en el Segundo Asalto!' author={null} text='El UFC Fight Night Canonnier vs Imanov, nos dejó 5 nocauts, 1 sumisión y un montón de peleas espectaculares que valen la pena ver, en una cartelera organizada en la ciudad de Loisville en el Estado de Kentucky.' date='09/06/2024' />
                <ArticlePreview img={lewisVsNascimento} url='/covertura-ufc/fight-night-lewis-nascimento' title='UFC Fight Night: ¡El Argentino Ribovics Noquea a su Rival a los 35 Segundos! ¡Lewis Noquea a Nascimento en el Tercer Asalto!' author={null} text='En el UFC Fight Night Lewis vs Nascimento fuimos testigos de una espectacular patada de Ribovics a los pocos segundos de empezar el combate, de la victoria por nocaut de Derrick Lewis en el evento principal, de un nocaut a los 12 segundos por parte de Carlos Ulberg, y mucho más.' date='12/05/2024' />
            </section>
        </main>
    )
}