import PeleadoresHero from '@/app/peleadores/components/PeleadoresHero'
import fighter from '@/assets/peleadores__images/0-100/40-60/brandon-moreno/brandon_moreno.png'
import styles from '@/app/peleadores/components/peleador.module.css'
import Link from 'next/link'
import Image from 'next/image'
import AsideChamps from '@/app/components/asides/AsideChamps'
import type { Metadata } from 'next'
import EndArticle from '@/app/components/EndArticle'

export const metadata: Metadata = {
    title: 'Brandon Moreno',
    description: 'Brandon Moreno es un luchador de MMA mexicano que compite en la división de peso mosca de la UFC, donde compite desde el 1 de octubre de 2016, cuando haría su debut ante el estadounidense Louis Smolka, mientras competía en The Ultimate Fighter.',
    openGraph: {
        title: 'Brandon Moreno',
        description: 'Brandon Moreno es un luchador de MMA mexicano que compite en la división de peso mosca de la UFC, donde compite desde el 1 de octubre de 2016, cuando haría su debut ante el estadounidense Louis Smolka, mientras competía en The Ultimate Fighter.',
        url: 'https://fullmma.org/peleadores/brandon-moreno'
    }
}

export default function BrandonMoreno () {
    return(
        <main>
            <PeleadoresHero peleadoresImage={fighter} w={22} l={8} d={2} categoria='Peso Mosca' nombre='Brandon Moreno' apodo='THE ASSASSIN BABY' />
            <section className={styles.peleador__articles__container}>
                <article className={styles.peleador__article}>
                    <h2 className={styles.peleador__article__title}>Brandon Moreno MMA</h2>
                    <p className={styles.peleador__article__text}>Brandon Moreno es un luchador de MMA mexicano que compite en la división de peso mosca de la <Link href='/articulos/ufc'>UFC</Link>, donde compite desde el 1 de octubre de 2016, cuando haría su debut ante el estadounidense <b>Louis Smolka</b>, mientras competía en <b>The Ultimate Fighter</b>.</p>
                    <p className={styles.peleador__article__text}>Supo destacar en la compañía al proclamarse campeón de la división en 2 ocasiones, ambas al derrotar al brasileño <b>Deiveson Figueiredo</b>, a quien venció por sumisión en 2021 y por TKO en 2023. Además de haber sido campeón interino de la compañía al derrotar al luchador de Nueva Zelanda <b>Kai Kara-France</b> en 2022.</p>
                    <h2 className={styles.peleador__article__title}>Brandon Moreno Récord</h2>
                    <p className={styles.peleador__article__text}>Brandon Moreno posee un récord profesional en las MMA de 22-8-2. Siendo 5 de sus victorias por la vía del nocaut, 11 por la vía de la sumisión y 6 por decisión. Mientras que todas sus 8 derrotas fueron decisión. Además, posee 2 empates a lo largo de su carrera.</p>
                    <h2 className={styles.peleador__article__title}>Brandon Moreno Historia</h2>
                    <p className={styles.peleador__article__text}>Brandon Moreno Carillo nació el día 7 de diciembre de 1993 en la ciudad de Tijuana, Baja California, México. Moreno se describe a sí mismo de pequeño como un gran fan del boxeo, que no tenía idea de la existencia de otros deportes de combate. Tiempo más tarde, se interesaría en la capoeira, pero al no ser capaz de encontrar una escuela que enseñe este arte marcial en su ciudad, terminó topándose con una gimnasio de MMA, donde comenzó a entrenar a los 12 años, aprendiendo kickboxing y jiu-jitsu. </p>
                    <p className={styles.peleador__article__text}>El 30 de abril de 2011, con tan sólo 17 años, Brandon hace su debut profesional en las MMA, peleando en la categoría de peso gallo ante el estadounidense <b>Atiq Jihad</b>, para una promotora nacional llamada <b>UWC México</b>, donde conseguiría un debut con victoria al ser capaz de someter a su rival en el primer asalto. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/9uTcmdsY3ls?si=Lh6SkXKHg1JzYVLo" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Sin embargo, el inicio de su carrera sería un tanto irregular, dado que en sus 6 primer peleas profesionales, acumularía un récord 3-3, perdiendo 3 peleas por decisión, y ganando 3 por sumisión. Aunque esta racha irregular se iría a partir de su séptimo combate, cuando enfrentaría al estadounidense <b>Jesse Cruz</b>, el día 22 de septiembre de 2022, consiguiendo una victoria por decisión dividida. </p>
                    <p className={styles.peleador__article__text}>En su octavo combate profesional obtendría la primer victoria por nocaut de su carrera, al enfrentar a <b>Jason Carbajal</b>, en marzo de 2013, y venciendo a este luchador en el tercer asalto. </p>
                    <p className={styles.peleador__article__text}>Para el año 2014 firmaría con la promotora estadounidense <b>World Fighting Federation</b>, debutando el día 28 de junio ante <b>Alex Contreras</b>, en una pelea que ganaría por sumisión en el tercer asalto, y en lo que sería su última pelea en peso gallo, puesto que después de este combate tomaría la decisión de moverse a pelear en la categoría de peso mosca. </p>
                    <p className={styles.peleador__article__text}>En esta nueva división de peso, debutaría peleando por el campeonato de la promotora, enfrentando a <b>C.J Soliven</b>, el 20 de septiembre de 2014, consiguiendo someter a este luchador en el primer asalto, convirtiéndose en el campeón de peso mosca de la WFF. </p>
                    <p className={styles.peleador__article__text}>Defendería el cinturón de la compañía en 3 ocasiones de manera exitosa. Siendo la primera de estas defensas ante <b>Matt Betxold</b>, a quien sería capaz vencer por decisión unánime. Más tarde, pelearía contra <b>Tyler Bialeck</b>, a quien derrotaría en el primer asalto por sumisión, luego de conectar un mataleón. Finalmente, la última defensa del título en la compañía la haría ante el americano <b>Isaac Camarillo</b>, a quien sometería en el tercer asalto del combate, siendo esta también su última pelea en <b>WFF</b>. </p>
                    <h2 className={styles.peleador__article__title}>Brandon Moreno UFC</h2>
                    <p className={styles.peleador__article__text}>De esta manera, con un récord profesional de 11-3, y ya sabiendo lo que es ser campeón, ganaría la oportunidad de paricipar en el reality televiso de la UFC <b>The Ultimate Fighter</b>. Fue en esta temporada 25 de la serie cuando el mexicano se enfrentaría a uno de sus mayores rivales, y al luchador que se terminaría convirtiendo en su coco, siendo este <Link href='/peleadores/alexandre-pantoja'>Alexandre Pantoja</Link>, contra quien caería derrotado en el primer combate del torneo por sumisión, en julio de 2016, aunque esta pelea no contaría para el récord de ninguno de los 2. </p>
                    <p className={styles.peleador__article__text}>De igual forma, en un movimiento extraño, poco usual para la compañía, Brandon Moreno firmaría para la compañía y debutaría cuando la temporada de <b>TUF</b> aún se estaba emitiendo. De esta manera tendría su primer pelea en la compañía de artes marciales mixtas más grande del mundo el día 1 de octubre de 2016, enfrentando a <b>Louis Smolka</b>, a quien sometería en el primer asalto, ganando ya en su primer pelea, el bono a la Actuación de la Noche. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/weIO61HTogM?si=J4LjKYMOL1k9ahSX" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Su siguiente pelea sería el 3 de diciembre de 2016, cuando enfrentaría a <b>Ryan Benoit</b>, a quien vencería por decisión dividida. Su tercer pelea para la compañía sería contra <b>Dustin Ortiz</b>, a quien sometería en el segundo asalto de la pelea en abril de 2017, ganando de esta forma el segundo bono a la Actuación de la Noche de su carrera. </p>
                    <p className={styles.peleador__article__text}>Debido a sus destacadas actuaciones, en su cuarta pelea para la compañía protagonizaría su primer cartelera en el evento de la UFC organizado en México, enfrentando para ello a <b>Segio Pettis</b>, contra quien sufriría su primer derrota en la compañía, al luego de 5 asaltos caer derrotado por decisión unánime. Para peor, en su siguiente pelea se vería cara a cara con el brasileño <Link href='/peleadores/alexandre-pantoja'>Alexandre Pantoja</Link>, contra quien volvería a caer derrotado, esta vez, por decisión unánime. </p>
                    <p className={styles.peleador__article__text}>Luego de aquella pelea con Pantoja, la UFC no renovaría el contrato con nuestro protagonista, por lo que este iría a pelear por el cinturón de <b>LFA</b>, enfrentando al cubano <b>Maikel Pérez</b>, a quien vencería por TKO en el cuarto asalto del combate. Tan sólo un mes después de esta pelea, Moreno dejaría vacante su cinturón para volver a firmar con la UFC. </p>
                    <p className={styles.peleador__article__text}>En su vuelta a la UFC, volvería a pelear en un evento organizado en México el día 21 de septiembre de 2019, enfrentando al ruso <b>Askar Askarov</b>, en una pelea que acabaría en empate por decisión dividida. Ese mismo año, el 14 de diciembre, se enfrentaría al neozelandés <b>Kai Kara-France</b>, en el UFC 245, venciendo a este por decisión unánime. </p>
                    <p className={styles.peleador__article__text}>Volvería a pelear el 14 de marzo de 2020, enfrentando al brasileño <b>Jussier Formiga</b>, en un evento organizado en Brasil, consiguiendo la victoria por decisión unánime. La segunda pelea del año la tendría ante el estadounidense <b>Brandon Rovyal</b>, a quien conseguiría vencer en el UFC 255 por TKO, faltando tan sólo 1 segundo para que termine el primer asalto. </p>
                    <h2 className={styles.peleador__article__title}>La Rivalidad Entre Brandon Moreno y Deiveson Figueiredo</h2>
                    <p className={styles.peleador__article__text}>Menos de un mes después, Brandon estaría dispuesto a encabezar el siguiente evento numerado, el UFC 256 organizado el 12 de diciembre, para disputarle el cinturón al entonces campeón brasileño <b>Deiveson Figueiredo</b>, con quien tendría una de las mejores peleas del año. El combate se extendería hasta el quinto asalto, cuando los jueces terminaron puntuando el combate como un empate por decisión mayoritaria, en el que ambos luchadores ganarían el bono a la Pelea de la Noche. </p>
                    <p className={styles.peleador__article__text}>Debido a lo cerrado del primer combate, Brandon se ganaría el derecho a pelear otra vez por el cinturón ante Figueiredo, programándose una pelea para el 12 de junio de 2021 en el UFC 263. En esta ocasión, el mexicano sería capaz de derrotar al campeón por sumisión, al conectar un mataleón en el tercer asalto. Ganando de esta manera otro bono por desempeño a la Actuación de la Noche, y convirtiéndose en el Campeón de Peso Mosca de la UFC.</p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/Xqq2htxnCfE?si=5ilK4w2rZmrcXzec" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>La historia entre estos 2 peleadores estaría lejos de terminar, dado que se programaría una tercer pelea para el 22 de enero de 2022 en el UFC 270. En este tercer combate el brasileño sería capaz de vengar su derrota y recuperar su cinturón, al vencer por decisión unánime a nuestro protagonista, en lo que sería elegido nuevamente como La Pelea de la Noche. </p>
                    <p className={styles.peleador__article__text}>A Brandon Moreno le tocaría pelear en una revancha por el cinturón interino de peso mosca ante <b>Kai Kara-France</b>, en el UFC 277, organizado el 30 de julio de 2022. Brandon sería capaz de imponerse ante su rival, al derrotarlo por TKO en el tercer asalto del combate, ganando otra vez el bono a La Pelea de la Noche. </p>
                    <p className={styles.peleador__article__text}>Esta victoria, y este cinturón interino, lo pondría en linea para pelear nuevamente, por cuarta vez, ante el campeón <b>Deiveson Figueiredo</b> el día 21 de enero de 2023 en el UFC 283. Aquella noche conseguiría ponerle fin a la rivalidad, al derrotar por TKO en el tercer asalto a su rival, por parada médica, volviendo a coronarse como campeón, y dejando sus peleas con el brasileño en un 2-1-1, favorable al mexicano. </p>
                    <h2 className={styles.peleador__article__title}>Brandon Moreno Después de sus peleas con Deiveson Figueiredo</h2>
                    <p className={styles.peleador__article__text}>Lamentablemente nuestro protagonista no sería capaz de retener el cinturón mucho tiempo, dado que para su primer defensa del título sería programado para enfrentar nuevamente, en un tercer combate, al brasileño <Link href='/peleadores/alexandre-pantoja'>Alexandre Pantoja</Link>, el día 8 de julio de 2023 en el UFC 290, donde terminaría cayendo derrotado por decisión dividida, aunque ganando nuevamente un bono a La Pelea de la Noche. </p>
                    <p className={styles.peleador__article__text}>Al año siguiente, el 24 de febrero de 2024, protagonizaría nuevamente una cartelera en su natal México, donde enfrentaría en una revancha a <b>Brandon Rovyal</b>, contra quien lamentablemente caería derrotado por decisión dividida. Sin embargo, para finales de ese 2024, el mexicano sería capaz de levantar cabeza, protagonizando nuevamente un Fight Night, en el que enfrentaría al iraquí <b>Amir Albazi</b>, un rival durísimo del top5 de la división, al que luego de 5 asaltos, sería capaz de vencer por decisión unánime en lo que fue victoria contundente por parte del mexicano. </p>
                    <EndArticle />
                </article>
                <AsideChamps />
            </section>
        </main>
    )
}