import PeleadoresHero from '@/app/peleadores/components/PeleadoresHero'
import fighter from '@/assets/peleadores__images/0-100/40-60/jack-della-maddalena/jack_della_maddalena.png'
import styles from '@/app/peleadores/components/peleador.module.css'
import Link from 'next/link'
import type { Metadata } from 'next'
import dynamic from 'next/dynamic'
import { YouTubeEmbed } from '@next/third-parties/google'

const AsideChamps = dynamic(() => import('@/app/components/asides/AsideChamps'))
const EndArticle = dynamic(() => import('@/app/components/EndArticle'))

export const metadata: Metadata = {
    title: 'Jack Della Maddalena',
    description: 'Jack Della Maddalena es un peleador australiano, que compite en la división de peso wélter de la UFC, desde que hiciera su debut el día 22 de enero de 2022, cuando derrotaría al luchador estadounidense Pete Rodriguez por la vía del nocaut en el primer asalto de la pelea.',
    openGraph: {
        title: 'Jack Della Maddalena',
        description: 'Jack Della Maddalena es un peleador australiano, que compite en la división de peso wélter de la UFC, desde que hiciera su debut el día 22 de enero de 2022, cuando derrotaría al luchador estadounidense Pete Rodriguez por la vía del nocaut en el primer asalto de la pelea.',
        url: 'https://fullmma.org/peleadores/jack-della-maddalena'
    }
}

export default function DellaMaddalena () {
    return(
        <main>
            <PeleadoresHero peleadoresImage={fighter} w={18} l={2} d={0} categoria='Peso Wélter' nombre='Jack Della Maddalena' apodo={null} time='2025-11-11' />
            <section className={styles.peleador__articles__container}>
                <article className={styles.peleador__article}>
                    <h2 className={styles.peleador__article__title}>Jack Della Maddalena MMA</h2>
                    <p className={styles.peleador__article__text}>Jack Della Maddalena es un peleador australiano, que compite en la división de peso wélter de la <Link href='/articulos/ufc'>UFC</Link>, desde que hiciera su debut el día 22 de enero de 2022, cuando derrotaría al luchador estadounidense <b>Pete Rodriguez</b> por la vía del nocaut en el primer asalto de la pelea. </p>
                    <p className={styles.peleador__article__text}>El australiano es un caso especial, dado que es de los pocos campeones de la UFC que perdió sus 2 primeros combates profesionales. A pesar de ello, siguió peleando, confiando en que tenía la habilidad de llegar lejos en el deporte, y eventualmente consiguiéndolo, ganando todos sus combates desde entonces, hasta enfrentar al campeón <Link href='/peleadores/belal-muhammad'>Belal Muhammad</Link>, en el <b>UFC 315</b>, donde lograría derrotarlo por decisión unánime y convertirse en campeón de peso wélter de la UFC, con un récord de 18-2. </p>
                    <h2 className={styles.peleador__article__title}>Jack Della Maddalena Récord</h2>
                    <p className={styles.peleador__article__text}>Jack Della Maddalena posee un récord profesional en MMA de 18-2. Tiene 18 victorias totales, de las cuales 12 vienen por la vía del nocaut, 2 por la vía de la decisión y 4 por decisión. Mientras que de sus 2 derrotas, 1 viene producto de un nocaut, y 1 por la vía de la sumisión. </p>
                    <h2 className={styles.peleador__article__title}>Jack Della Maddalena Historia</h2>
                    <p className={styles.peleador__article__text}>Giacomo &quot;Jack&quot; Della Maddalena nació el 10 de septiembre de 1996 en la ciudad de Perth, Australia. Desde pequeño comenzó a practicar deportes, iniciando con el rugby, que es uno de los deportes principales del país. Tendría bastantes peleas físicas con su hermano mayor durante gran parte de su infancia, ensayando técnicas de peleas que habían visto en la tele o en videos de manera autodidacta. De esta forma, influenciado por su hermano, comenzó a entrenar boxeo a los 14 años, con la idea de que eso lo ayudaría en su carrera de Rugby.</p>
                    <p className={styles.peleador__article__text}>Finalmente, se enamoraría del deporte y una vez finalizada su carrera en rugby y transicionaría a las MMA, a las que dedicaría todo su tiempo, haciendo su debut profesional en el deporte el día 12 de marzo de 2016, enfrentando al luchador británico <b>Aldin Bates</b> en la promotora <b>Eternal MMA</b>, donde pelearía durante gran parte de su carrera temprana. Lamentablemente para nuestro protagonista, caería derrotado por TKO en el tercer asalto de la pelea, lo que es una rareza para la mayoría de los peleadores que hoy compiten en la UFC. Para peor, en su siguiente pelea que tendría lugar 2 meses después, el 28 de mayo en la misma cartelera, volvería a caer derrotado, esta vez por sumisión en el primer asalto ante su compatriota <b>Darcy Vendy</b>. </p>
                    <p className={styles.peleador__article__text}>Lo de Jack Della Maddalena es un caso particular por esto mismo, al ser un peleador que perdió sus 2 primeros combates profesionales, ya que este primer intento fallido de ser un profesional exitoso hubiera desmotivado a la mayoría de personas, pero este no era el caso para nuestro protagonista, que creía que contaba con la habilidad para llegar lejos en el deporte, y terminaría por demostrarlo con el tiempo. Comenzando ya el 15 de octubre de ese mismo año, enfrentando a su compatriota <b>Brandt Cogill</b>, a quien lograría derrotar por KO en el primer asalto del combate con un codazo, consiguiendo de esta manera su primer combate victoria profesional, y sería la primera de muchas, dado que a partir de aquí comenzaría una racha de victorias impresionantes. </p>
                    <p className={styles.peleador__article__text}>Su siguiente victoria sería por nocat en el primer asalto ante <b>Glen Pettigrew</b>, pelea que tendría lugar el 8 de abril de 2017, y que además le serviría para ganar el Campeonato de Peso Wélter de Reign Fighting. </p>
                    <p className={styles.peleador__article__text}>Ese mismo año tendría 2 peleas más, con la primera siendo el 8 de julio ante su compatriota <b>Ty Duncan</b>, a quien noquearía en el segundo asalto. Y con su segunda pelea siendo para la promotora inglesa <b>Cage Warriors</b> el 28 de octubre, enfrentando al luchador británico <b>James Duckett</b>, a quien conseguiría conectarle la primer sumisión de su carrera en el segundo asalto del combate. </p>
                    <p className={styles.peleador__article__text}>En el año 2018 lograría convertirse en campeón de la promotora que lo vió debutar, <b>Eternal MMA</b>, cuando el día 10 de marzo se enfrentara a <b>Luke Howard</b>, consiguiendo dejarlo KO en el segundo asalto con una combinación de golpes. </p>
                    <p className={styles.peleador__article__text}>A partir de acá, defendería su cinturón en 4 oportunidades, noqueando en el primer asalto a su compatriota <b>Dean Abramo</b>; venciendo al francés <b>Kevin Jousset</b> por parada médica al finalizar el segundo asalto en octubre de 2019; consiguiendo un nuevo nocaut en el segundo asalto ante <b>Glen Pettigrew</b>; y finalmente obteniendo una victoria por KO en el primer asalto ante le británico <b>Aldin Bates</b>, en lo que sería su última defensa del cinturón, y su último combate para la promotora <b>Eternal MMA</b>. </p>
                    <h2 className={styles.peleador__article__title}>Jack Della Maddalena Dana Whites Contender Series</h2>
                    <p className={styles.peleador__article__text}>Habiendo acumulado 9 victorias consecutivas, y siendo un campeón regional con 4 defensas exitosas del cinturón, a Jack se le presentaría la oportunidad de su vida, cuando sería invitado a particiar del programa de la UFC <Link href='/eventos/dana-white-contender-series-que-es'>Dana Whites Contender Series</Link>, donde en caso de impreisonar al jefe <b>Dana White</b>, obtendría un contrato con la compañía de artes marciales mixtas más grande del mundo. Para aquel combate se enfrentaría al luchador suizo <b>Ange Loosa</b>, el día 14 de septiembre de 2021, logrando luego de 3 asaltos una victoria por decisión unánime, siendo este el primero de sus combate que se extiende hasta los 3 asaltos, pero que de igual manera le serviría para ganarse el tan ansiado contrato con la UFC. </p>
                    <YouTubeEmbed videoid='xPOQpI2SpdE' />
                    <h2 className={styles.peleador__article__title}>Jack Della Maddalena UFC</h2>
                    <p className={styles.peleador__article__text}>Jack Della Maddalena haría su debut en la UFC el día 22 de enero de 2022 en el <b>UFC 270</b> (que tenía a <Link href='/peleadores/francis-ngannou'>Francis Ngannou</Link> vs <Link href='/peleadores/ciryl-gane'>Ciryl Gane</Link> como evento estelar), enfrentando al estadounidense <b>Pete Rodríguez</b>, a quien conseguiría derrotar por TKO en el primer asalto de la pelea, logrando un debut exitoso en la compañía. </p>
                    <p className={styles.peleador__article__text}>El 19 de noviembre de ese mismo año tendría su segunda pelea, donde enfrentaría al luchador daguestaní (ver <Link href='/articulos/luchadores-de-daguestan-ufc'>Luchadores destacados de Daguestán</Link>) <b>Ramazan Emeev</b>, en lo que a priori parecía un combate complicadísimo para nuestro protagonista, sin embargo en sólo 2 minutos y medio del primer asalto fue capaz de derrotarlo por TKO, ganando de esta forma su primer bono a la Actuación de la Noche. Volvería a combatir el 12 de febrero de 2023, enfrentando al luchador inglés <b>Danny Roberts</b>, a quien sería capaz noquear nuevamente en el primer asalto, ganando su segundo bono por desempeño. </p>
                    <p className={styles.peleador__article__text}>Seguiría obteniendo victorias, venciendo en febrero de 2023 a <b>Randy Brown</b> por sumisión en el primer asalto, obteniendo un bono por desempeño nuevamente, y al derrotar a <b>Bassil Hafez</b> por decisión dividida, en la que sería elegida la pelea de la noche. A finales de ese mismo año, el 16 de septiembre, tendría su última pelea del año ante el siempre activo <b>Kevin Holland</b>, obteniendo una victoria por decisión dividida que lo asentaría en los rankings de la división. </p>
                    <p className={styles.peleador__article__text}>El 9 de marzo de 2024 en el <b>UFC 299</b>, pelearía ante el histórico peleador brasileño <b>Gilbert Burns</b>, en un combate que fue bastante cerrado, y que en caso de llegar a la decisión de los jueces, corría el riesgo de perderlo, finalmente logró conectar un rodillazo que luego de una combinación de golpes, le otorgaría la victoria por TKO en el tercer asalto, ganando nuevamente el bono a la Actuación de la Noche y estableciéndose como un serio peligro para toda la división. </p>
                    <YouTubeEmbed videoid='vGXSJCFE2h8' />
                    <p className={styles.peleador__article__text}>Se lo programaría para pelear contra el excampeón de la división <Link href='/peleadores/leon-edwards'>Leon Edwards</Link>, en un evento que estaba planeado para realizarse en Londres el 22 de marzo de 2025. Sin embargo este combate sería cancelado, luego de que el evento principal del <b>UFC 315</b> corriera peligro, en donde se enfrentarían el campeón de la división de peso wélter <Link href='/peleadores/belal-muhammad'>Belal Muhammad</Link> ante el kazajo <Link href='/peleadores/shavkat-rakhmonov'>Shavkat Rakhmonov</Link>, ya que este último se daría de baja por lesión. Fue en este contexto, donde se le ofreció a Jack Della Maddalena cancelar su pelea con Leon Edwards para pelear por el cinturón de la división.</p>
                    <p className={styles.peleador__article__text}>Por supuesto el australiano aceptaría, y de esta manera pelearía en el UFC 315, organizado el 10 de mayo de 2025 en Montreal, Canadá. Aquel combate se extendería hasta los 5 asaltos y sorprendería a medio mundo, con un Jack Della Maddalena que se mostró muy superior al campeón y lograría derrotarlo por decisión unánime, convirtiéndose en el nuevo campeón de peso wélter de la UFC. Teniendo un ascenso meteórico, peleando casi de que por azar del destino por el cinturón, pero demostrando que siempre estuvo listo para este momento, coronándose finalmente como campeón. </p>
                    <p className={styles.peleador__article__text}></p>
                    <EndArticle />
                </article>
                <AsideChamps />
            </section>
        </main>
    )
}