import PeleadoresHero from '@/app/peleadores/components/PeleadoresHero'
import usman from '@/assets/peleadores__images/10-20/kamaru-usman/usman.png'
import kamaru from '@/assets/peleadores__images/10-20/kamaru-usman/usman.jpg'
import card from '@/assets/peleadores__images/10-20/kamaru-usman/usman_card.jpg'
import styles from '@/app/peleadores/components/peleador.module.css'
import Link from 'next/link'
import Image from 'next/image'
import AsideChamps from '@/app/components/asides/AsideChamps'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Kamaru Usman',
    description: 'Kamaru Usman es un peleador de origen nigeriano que actualmente está rankeado en el puesto #1 de la división de Peso Welter, en donde llegó a ser campeón en marzo de 2019m cuando le arrebataría el título por decisión unánime al estadounidense Tyron Woodley. Tuvo 5 defensas por el título exitosas hasta que el 20 de agosto perdió el título por KO en el 5to asalto contra el jamaicano Leon Edwards, a quien tuvo la oportunidad de volver a enfrentar poco después sin mucho exito.',
    openGraph: {
        title: 'Kamaru Usman',
        description: 'Kamaru Usman es un peleador de origen nigeriano que actualmente está rankeado en el puesto #1 de la división de Peso Welter, en donde llegó a ser campeón en marzo de 2019m cuando le arrebataría el título por decisión unánime al estadounidense Tyron Woodley. Tuvo 5 defensas por el título exitosas hasta que el 20 de agosto perdió el título por KO en el 5to asalto contra el jamaicano Leon Edwards, a quien tuvo la oportunidad de volver a enfrentar poco después sin mucho exito.',
        url: 'https://fullmma.org/peleadores/kamaru-usman'
    }
}

export default function Usman () {
    return(
        <main>
            <PeleadoresHero peleadoresImage={usman} w={20} l={4} d={0} nombre='Kamaru Usman' apodo='NIGERIAN NIGHTMARE' categoria='Peso Welter' />
            <section className={styles.peleador__articles__container}>
                <article className={styles.peleador__article}>
                    <h2 className={styles.peleador__article__title}>Usman UFC</h2>
                    <p className={styles.peleador__article__text}>Kamaru Usman es un peleador de MMA nigeriano que compite en la división de peso wélter de la <Link href='/articulos/ufc'>UFC</Link> desde julio de 2015, cuando debutó enfrentando al estadounidense <b>Hayder Hassan</b>, en la final del torneo <b>The Ultimate Fighter</b>. Haría historia en la compañía al convertirse en campeón de la división al derrotar por decisión unánime al entonces campeón <b>Tyron Woodley</b> el 2 de marzo de 2019, convirtiéndose desde entonces en uno de los campeones más dominantes de la década. </p>
                    <p className={styles.peleador__article__text}>Es una auténtica leyenda de la división de las 170lbs, con victorias y actuaciones dominantes de todo tipo, siendo de los campeones con más defensas que ha habido en peso wélter, supo ser un campeón de época en su momento y es aún con su veteranía, un peligro para cualquier luchador que le quiera hacer frente. </p>
                    <p className={styles.peleador__article__text}>Haría historia en la compañía al convertirse en campeón de la división al derrotar por decisión unánime al entonces campeón <b>Tyron Woodley</b> el 2 de marzo de 2019, convirtiéndose desde entonces en uno de los campeones más dominantes de la década. </p>
                    <h2 className={styles.peleador__article__title}>Kamaru Usman Récord</h2>
                    <p className={styles.peleador__article__text}>Kamaru Usman tiene un record profesional de MMA de 20-4. Siendo 9 de sus 20 victorias por la vía del nocaut, 1 por sumisión y 10 por decisión. Mientras que de sus 4 derrotas, 1 fue por sumisión, 1 por la vía del nocaut y 2 por decisión. </p>
                    <h2 className={styles.peleador__article__title}>Kamaru Usman Historia</h2>
                    <p className={styles.peleador__article__text}>Kamaru Usman nació el 11 de mayo de 1987 en la ciudad de Benín, Nigeria. Tanto él como su familia se mudaron a los Estados Unidos cuando Usman tenía tan sólo 5 años. En su adolescencia, Kamaru comenzó a practicar Wrestling en la escuela secundaria a la que asistía, llegando a acumular un récord de 56-0, tanto en su escuela secundaria como posteriormente en su universidad, Usman se labraría una carrera exitosa en el wrestling. </p>
                    <p className={styles.peleador__article__text}>Esto en el futuro le terminaría abriendo las puertas a competir en MMA, donde haría su debut profesional el día 30 de noviembre de 2012, con 25 años, enfrentando al estadounidense <b>David Glover</b> a quien derrotaría por TKO en el segundo asalto. </p>
                    <p className={styles.peleador__article__video}>Kamaru perdería su siguiente combate, cuando enfrentando a <b>Jose Caceres</b> en mayo de 2013, caería derrotado por sumisión en el primer asalto. Sin embargo, esta sería su última derrota en mucho tiempo, dado que después de esta pelea, comenzaría el ascenso de unos de los peleadores más dominantes en la historia de las 170lbs en la UFC. Ganando su siguiente combate el 14 de diciembre de ese mismo año, al lograr noquear a <b>Rashid Abdullah</b>. </p>
                    <p className={styles.peleador__article__video}>Posteriormente firmaría con la promotora <b>Legacy FC</b>, en donde debutaría el 31 de enero de 2014, enfrentando a <b>Steven Rodíguez</b>, a quien conseguiría noquear en el primer asalto. El 4 de abril de ese mismo año volvería a pelear para enfrentar a <b>Lenny Lovoto</b>, a quien conseguiría noquear en el tercer asalto. Y finalmente tendría la última pelea del año, y última en la compañía, cuando enfrentando a <b>Marcu Hicks</b> lograría vencerlo por TKO en el segundo asalto del combate. </p>
                    <p className={styles.peleador__article__video}>Luego de esta racha de victorias, con récord profesional de 5-1, ganaría la oportunidad de participar en el reality de televisión de la UFC <b>The Ultimate Fighter</b>. En el cual destacaría al ganar todos sus combates hasta finalmente llegar a la final, en la que haría su debut oficial por la compañía al enfrentar al luchador americano <b>Hayder Hassan</b>, a quien sería capaz de someter en el segundo asalto, ganando el bono a la Actuación de la Noche por su desempeño. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/g6-ijAuuUMw?si=WFOnFl_dxVPXHmZn" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__video}>En su siguiente pelea con fecha para el 19 de diciembre de ese mismo 2015, se enfrentaría a un luchador que en el futuro sería importante para la historia de nuestro protagonista, al verse cara a cara con el jamaiquino <Link href='/peleadores/leon-edwards'>Leon Edwards</Link>, a quien al cabo de 3 asaltos sería capaz de derrotar por decisión unánime. </p>
                    <p className={styles.peleador__article__video}>El 23 de julio de 2016 volvería a subir al octágono para enfrentar al ruso <b>Alexander Yukovlev</b>, a quien acabaría derrotando por decisión unánime. En noviembre de ese mismo año se enfrentaría al brasileño <b>Warlley Alves</b>, en un evento organizado en Brasil, logrando conseguir nuevamente una victoria por decisión unánime. </p>
                    <p className={styles.peleador__article__video}>En el año 2017 tendría 2 combates, siendo el primero de estos el 8 de abril contra quien en el futuro se convertiría en campeón de medio <Link href='/peleadores/sean-strickland'>Sean Strickland</Link> en el UFC 210, consiguiendo dominar completamente al estadounidense durante los 3 asaltos de la pelea, llevándose la victoria por decisión unánime. Y la segunda pelea de aquel año la tendría ante el brasileño <b>Sérgio Moraes</b>, contra quien tendría la segunda finalización de su carrera, al lograr dejar KO a su rival antes de los 3 minutos del primer asalto. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/bhn5Qm5ZMlc?si=FdPkzlrjg53wkE7u" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__video}>En el 2018 sería aún más activo, peleando en 3 ocasiones diferentes. Siendo la primera de estas peleas el 14 de enero ante el noruego <b>Emil Weber Meek</b>, a quien conseguiría derrotar por decisión unánime. El 19 protagonizaría su primer cartelera de UFC, en un evento organizado en Santiago de Chile, donde en la pelea estelar enfrentaría al brasileño <b>Demian Maia</b>, a quien luego de 5 asaltos conseguiría derrotar por decisión unánime. </p>
                    <p className={styles.peleador__article__video}>La última pelea del año sería ante el histórico luchador de la compañía, excampeón de peso ligero, <b>Rafael Dos Anjos</b>, a quien enfrentaría el 30 de noviembre, en otro evento que lo tendría como protagonista de la cartelera. Aquella noche, el peleador nigeriano conseguiría hacerse con la victoria por decisión unánime, ganando además el tercer bono de su carrera a la Actuación de la Noche. </p>
                    <p className={styles.peleador__article__video}>De esta manera, con un récord profesional de 14-1, estando invicto en la UFC, y habiendo derrotado a varios de los rivales más duros de la división, el 2 de marzo de 2019 en el UFC 235, tendría la oportunidad de enfrentarse ante el campeón estadounidense <b>Tyroon Woodley</b> en una pelea por el título de las 170lbs. Nuestro protagonista aquella noche sería capaz de dominar completamente la pelea llevándose la victoria por decisión unánime luego de 5 asaltos, convirtiéndose de esta manera en el nuevo campeón de peso wélter de la UFC.</p>
                    <p className={styles.peleador__article__video}>Una vez coronado, haría su primer defensa del título el 14 de diciembre de ese mismo año ante el siempre controvertido <Link href='/peleadores/colby-covington'>Colby Covington</Link>, quien el año anterior había conseguido ser campeón interino, y quien venía de una racha de 7 victorias consecutivas. Aquella noche ambos luchadores darían lo mejor de sí en lo que fue todo un espectáculo, terminando el enfrentamiento en el quinto asalto, cuando nuestro protagonista conseguiría noquear a su rival, para concretar su primer defensa exitosa, y para al final de la noche terminar ganando el bono a La Pelea de la Noche. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/WaNhcOML4nA?si=qbk7B7yvtqDPeDhl" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__video}>Su segunda defensa estaba prevista que se realizara ante el brasileño <b>Gilbert Burns</b>, sin embargo este fue retirado del evento luego de enfermarse con ese virus que estaba muy de moda en 2020, siendo reemplazado en su lugar con el reciente ganador del <b>BMF</b>, <Link href='/articulos/jorge-masvidal-historia'>Jorge Masvidal</Link>, a quie enfrentaría el 11 de junio de 2020, en una pelea que se extendería hasta los 5 asaltos y que Kamaru Usman ganaría por decisión unánime. </p>
                    <p className={styles.peleador__article__video}>Para su tercer defensa programada como cabeza del evento UFC 258 el 13 de febrero de 2021, esta vez sí se enfrentaría a Burns, consiguiendo una espectacular victoria por nocat en el tercer asalto, ganando por esto el bono a la Actuación de la Noche. </p>
                    <p className={styles.peleador__article__video}>Aún más espectacular sería lo conseguido en su siguiente defensa, cuando se lo programaría para enfrentar en una revancha al peleador estadounidense de origen cubano y peruano <b>Jorge Masvidal</b>, a quien enfrentaría el 24 de abril de 2021 en el UFC 261. Aquella noche conseguiría conectar uno de los KO más vistosos jamás hechos en el segundo asalto. Logrando de esta forma concretar su cuarta defensa consecutiva del cinturón, y ganar nuevamente el bono a la Actuación de la Noche. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/08arcfS7v_c?si=00CqnffUA-ZMj3AV" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__video}>Ese mismo año volvería a pelear para enfrentarse en una nueva revancha al estadounidense <Link href='/peleadores/colby-covington'>Colby Covington</Link>, a quien enfrentaría el 6 de noviembre en el UFC 268, consiguiendo volver a derrotar a su rival por decisión unánime, completando su quinta defensa exitosa del título, y alcanzando las 20 victorias en toda su carrera profesional. </p>
                    <p className={styles.peleador__article__video}>Kamaru Usman repetería rival por tercera vez consecutiva, al programarse una revancha ante <Link href='/peleadores/leon-edwards'>Leon Edwards</Link> el 20 de agosto de 2022 en el UFC 278, en lo que sería su sexta defensa del cinturón de peso wélter. En esta ocasión, en un combate que estaba dominando completamente y que parecía que se iría a su favor al llegar a la decisión de los jueces, lamentablemente recibiría una patada en la cabeza en el quinto asalto, a un minuto de que acabe la pelea, que lo dejaría KO, perdiendo de esta menera su cinturón. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/egNhnzfX6VU?si=okvJLz6fYJXPE9AQ" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__video}>Debido a la larga trayectoria y a la excelente carrera que había conseguido hasta el momento es que se programaría una revancha inmediata, teniendo nuestro protagonista la oportunidad de recuperar su cinturón. Dicha combate se pactaría para el 18 de marzo de 2023 en el UFC 286, donde lamentablemente el nigeriano volvería a caer derrotado, esta vez por decisión mayoritaria. </p>
                    <p className={styles.peleador__article__video}>Tiempo después Usman aceptaría pelear con poco tiempo de anticipación para enfrentar al checheno <Link href='/peleadores/khamzat-chimaev'>Khamzat Chimaev</Link>, en reemplazo del brasileño <b>Paulo Costa</b> que se bajó por una lesión, el 21 de octubre de 2023 en el UFC 294. Este sería el debut en peso mediano de nuestro protagonista, en el que yendo de menos a más, terminaría por perder la pelea por decisión mayoritaria. </p>
                </article>
                <AsideChamps />
            </section>
        </main>
    )
}