import PeleadoresHero from '@/app/peleadores/components/PeleadoresHero'
import styles from '@/app/peleadores/components/peleador.module.css'
import Link from 'next/link'
import aspinall from '@/assets/peleadores__images/0-100/0-10/tom-aspinall/tom_aspinall.png'
import Image from 'next/image'
import AsideFighter from '@/app/components/asides/AsideFighter'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Tom Aspinall',
    description: 'Tom Aspinall es un peleador inglés de MMA que compite en la división de Peso Pesado de la UFC desde julio de 2020. Y ha destacado en la compañía al convertirse en campeón interino de la misma en noviembre de 2023, derrotando vía KO al ruso Sergei Pavlovich.',
    openGraph: {
        title: 'Tom Aspinall',
        description: 'Tom Aspinall es un peleador inglés de MMA que compite en la división de Peso Pesado de la UFC desde julio de 2020. Y ha destacado en la compañía al convertirse en campeón interino de la misma en noviembre de 2023, derrotando vía KO al ruso Sergei Pavlovich.',
        url: 'https://fullmma.org/peleadores/tom-aspinall'
    }
}

export default function Aspinall () {
    return(
        <main> 
            <PeleadoresHero peleadoresImage={aspinall} w={15} l={3} d={0} nombre='Tom Aspinall' categoria='Peso Pesado' apodo={null} />
            <section className={styles.peleador__articles__container}>
                <article className={styles.peleador__article}>
                    <h2 className={styles.peleador__article__title}>Tom Aspinall UFC</h2>
                    <p className={styles.peleador__article__text}>Tom Aspinall es un peleador inglés de MMA que compite en la división de Peso Pesado de la <Link href='/articulos/ufc'>UFC</Link> desde julio de 2020, cuando enfrentaría al estadounidense <b>Jake Collier</b> en el <b>UFC on ESPN: Whittaker vs. Till</b>. </p>
                    <p className={styles.peleador__article__text}>Es uno de los peleadores más entretenidos de ver que existe en la UFC actualmente, contando con una velocidad que no es normal para alguien de su peso, que sumado a su excelente nivel de lucha y al poder con el que cuenta en sus puños, lo hacen uno de los peleadores más peligrosos de la compañía. Es una maquina de finalizar, al punto tal que al menos hasta el 2024, en sus más de 15 peleas profesionales, jamás ha necesitado de ir a la tarjeta de los jueces, siendo uno de los peleadores con menos tiempo dentro del octágono que hay. </p>
                    <p className={styles.peleador__article__text}>Ha destacado al convertirse en campeón interino de la compañía en peso pesado, luego de que el día 11 de noviembre de 2023 en el UFC 295, fuera capaz de noquear en el primer asalto al ruso <b>sergei Pavlovich</b>. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/pV1ll_x0wcY?si=8EUdlf9bCkGoIPZU" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <h2 className={styles.peleador__article__title}>Tom Aspinall Récord</h2>
                    <p className={styles.peleador__article__text}>Tom Aspinall tiene un récord de 15-3. Siendo 12 de sus 15 victorias por la vía del nocaut y 3 por la vía de la sumisión, convirtiendolo en un peleador que hasta el momento ha finalizado en todas sus victorias. Mientras que de sus 3 derrotas, una fue por la vía del nocaut, 1 por sumisión, y una de sus peleas la perdió por descalificación, dado que dió un codazo ilegal hacia abajo en su combate contra el polaco <b>Łukasz Parobiec</b>.</p>
                    <h2 className={styles.peleador__article__title}>Tom Aspinall Historia</h2>
                    <p className={styles.peleador__article__text}>Thomas Aspinall nació el 11 de abril de 1993, en el condado de Gran Mánchester en Inglaterra. Es una persona nacida en el seno de una familia polaco-inglesa, por lo que es capaz de hablar ambos idiomas. A la edad de 7, siguiendo los pasos de su padre comenzó a entrenar artes marciales, comenzando con la lucha libre y el boxeo, terminaría trancisionando al jiu-jitsu brasileño en donde actualmente es cinturón negro.</p>
                    <p className={styles.peleador__article__text}>Transicionaría a las artes marciales mixtas, en donde de manera amateur lograría demostrar su desestreza, siendo campeón en 2 ocasiones, hasta finalmente hacer su debut profesional el 13 de diciembre de 2014, enfrentando al canadiense <b>Michał Piszczek</b>, a quien acabó ganando por nocaut ni bien empezar el combate en el primer asalto. En esta línea acumularía un récord de 5-2 hasta recibir su primer oferta para pelear en <Link href='/articulos/ufc'>UFC</Link>, oferta que rechazó ya que había afirmado no sentirse preparado, en su lugar se fue a pelear a <b>Cage Warriors</b>, donde entre otros, peleó <Link href='/peleadores/conor-mcgregor'>Conor Mcgregor</Link>.</p>
                    <p className={styles.peleador__article__text}>En esta promotora tendría 2 enfrentamientos a lo largo del año 2019, siendo el primero de ellos ante el francés <b>Sofiane Boukichou</b>, a quien enfrentaría el 16 de febrero en el <b>Cage Warriors 101</b>, consiguiendo una victoria por TKO en el primer asalto, luego de que su contrincante sufriera una lesión en la pierna que le impediría continuar. Su segunda pelea sería ante el también francés <b>Michael Ben Hamouda</b>, con quien se vería cara a cara el 29 de septiembre en el <b>Cage Warriors 107</b>, consiguiendo una importante victoria por nocaut antes de finalizado el primer minuto de la pelea. </p>
                    <p className={styles.peleador__article__text}>Finalmente ahora sí, haría su debut en la compañía más grande  de artes marciales mixtas en el mundo, el día 26 de julio de 2020 en el <b>UFC on ESPN: Whittaker vs. Till</b>, contra el estadounidense <b>Jake Collier</b> a quien vencería en el primer minuto del primer asalto de la pelea, ganando además en este combate el primer bono de su carrera a la Actuación de la Noche. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/dMfSsPCWwtE?si=J6s5AmLita3muH25" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>En octubre de ese mismo año volvería a pelear ante el luchador francés <b>Alan Baudot</b>, a quien conseguiría derrotar por TKO en el primer asalto de la pelea. Pelearía a los pocos meses ante el peleador de Bielorrusia <b>Andrei Arlovski</b>, a quien lograría derrotar por sumisión en el segundo asalto de la pelea, ganando nuevamente el bono a la Actuación de la Noche como premio a su desempeño. </p>
                    <p className={styles.peleador__article__text}>El 4 de septiembre de 2021 volvería a subirse al octágono para enfrentar al peleador de Maldovia <b>Sergey Spivak</b>, a quien derrotaría por TKO en el primer asalto de la pelea, luego de conectar un codazo y puñetazos que le darían la victoria, además, volvería a ganar el bono a la Actuación de la Noche. </p>
                    <p className={styles.peleador__article__text}>Volvería a pelear para encabezar el evento de UFC organizado en la capital de su país, Londrés. En el llamado <b>UFC Fight Night: Volkov vs. Aspinall</b> que se llevaría a cabo el 19 de marzo de 2022, enfrentando al ruso ya mencionado <b>Aleksandr Vólkov</b>, a quien derrotaría por sumisión en el primer asalto de la pelea. Ganando nuevamente el bono a la Actuación de la Noche por el desempeño realizado. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/aCS_rPXRFGY?si=9UGMD133zRkIQHrC" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>La última pelea del 2022 la tendría el día 22 de julio, nuevamente encabzadon un evento de UFC en Londrés. Para ello enfrentaría al estadounidense <b>Curtis Blaydes</b>, contra quien lamentablemente sufriría la primer derrota de su carrera en UFC de manera completamente fortuita, al recibir una lesión en la rodilla que le impidiría seguir peleando a tan sólo 15 segundo de empezado el combate, terminando el evento de manera totalmente anticlimática. </p>
                    <p className={styles.peleador__article__text}>Como necesitaría del tiempo necesario para recuparse de la lesión recibida, no volvería a pelear hasta dentro de 12 meses después, haciendo su regreso el 22 de julio de 2023, para protagonizar nuevamente un evento de la UFC en Londres, enfrentando para ello al polaco <b>Marcin Tybura</b>, a quien derrotaría vía TKO en el primer asalto de la pelea, regresando de la mejor manera de su lesión, ganando además el bono a la Actuación de la Noche por quinta vez en su carrera. </p>
                    <p className={styles.peleador__article__text}>Con un récord profesional de 13-3, nuestro protagonista aceptaría una pelea de último momento para reemplazar el combate entre <Link href='/peleadores/jon-jones'>Jon Jones</Link>, quien para aquel momento era el campeón indiscutido, y <b>Stipe Miocic</b>, en lo que era una pelea por el campeonato. Resulta que el campeón Jon Jones se lesionó, teniendo que cancelar el combate, llevando a la UFC a poner la pelea entre Tom Aspinall y el ruso <b>Sergei Pavlovich</b>, disputándose un cinturón interino de la división de los pesos pesados. </p>
                    <p className={styles.peleador__article__text}>La pelea se llevaría a cabo como evento coestelar del UFC 295, organizado el 11 de noviembre de 2023. Aquella noche, Aspinall conseguiría llevarse la victoria al derrotar por KO en el primer asalto a su rival, ganando de esta forma el Campeonato Interino de Peso Pesado de UFC, además del sexto bono de su carrera a la Actuación de la Noche. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/dx9z0t4ZOzY?si=WD7Y-zvBDY4rhbWu" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>De forma un tanto inédita, como contamos más a detalle en <Link href='/noticias/jones-esquiva-aspinall'>este artículo</Link>, no se pondría a Tom Aspinall a enfrentar Jon Jones, como es costumbre cuando hay un campeón indiscutido y un campeón interino, sino que debido a la inactividad del estadounidense, se pondría al luchador inglés a defender el cinturón interino, para mantener movida la división y que esta no quede estancada. Para ello, en el <Link href='/covertura-ufc/ufc304'>UFC 304</Link> que se organizó en la ciudad inglesa de Manchester, se lo pondría a enfrentar en una revancha ante el americano <b>Curtis Blaydes</b>, contra quien había caído derrotado de forma accidental, consiguiendo esta vez vengar su derrota al derrotar por TKO en el primer asalto de la pelea a su rival, defendiendo de esta maenra su cinturón de forma exitosa.</p>
                </article>
                <AsideFighter />
            </section>
        </main>
    )
}