import styles from '@/app/leyendas/components/leyenda.module.css'
import Link from 'next/link'
import AsideChamps from '@/app/components/asides/AsideChamps'
import AldoHero from './AldoHero'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'José Aldo',
    description: "José Aldo es un expeleador de MMA brasileño que destacó por ser el primer campeón de peso pluma de la UFC, donde es considerado por muchos como el mejor campeón que tuvo la división en la compañía. Contando con un total de 7 defensas exitosas, siendo de los peleadores más dominantes que tuvo la división.",
    openGraph: {
        title: 'José Aldo',
        description: "José Aldo es un expeleador de MMA brasileño que destacó por ser el primer campeón de peso pluma de la UFC, donde es considerado por muchos como el mejor campeón que tuvo la división en la compañía. Contando con un total de 7 defensas exitosas, siendo de los peleadores más dominantes que tuvo la división.",
        url: 'https://fullmma.org/leyendas/jose-aldo'
    }
}


export default function Aldo () {
    return(
        <main>
            <AldoHero />
            <section className={styles.leyenda__articles__container}>
                <article className={styles.leyenda__article}>
                    <h2 className={styles.leyenda__article__title}>Jose Aldo UFC</h2>
                    <p className={styles.leyenda__article__text}>José Aldo es un expeleador de MMA brasileño que destacó por ser el primer campeón de peso pluma de la <Link href='/articulos/ufc'>UFC</Link>, donde es considerado por muchos como el mejor campeón que tuvo la división en la compañía. Contando con un total de 7 defensas exitosas, siendo de los peleadores más dominantes que tuvo la división.</p>
                    <h2 className={styles.leyenda__article__title}>Jose Aldo Récord</h2>
                    <p className={styles.leyenda__article__text}>José Aldo cuenta con un récord en las MMA de 32-8. Siendo 16 de esas 32 victorias por nocaut, 2 por sumisión, y 15 por decisión. Mientras que de sus 8 derrotas, 4 fueron por nocaut, 1 por sumisión y 3 por decisión. </p>
                    <h2 className={styles.leyenda__article__title}>Jose Aldo Historia</h2>
                    <p className={styles.leyenda__article__text}>Chunguita José Aldo da Silva Oliveira, Jr. nació en el seno de una familia pobre un 9 de septiembre de 1986 en la ciudad de Manaos, que es la capital del Estado de Amazonas, perteneciente al norte de Brasil. Desde pequeño comenzó a practicar capoeira, donde se destacó, llamando la atención de un entrenador de Jiu-Jitsu brasileño que le recomendó entrenar con él, y así lo hizo, destacando al ganar campeonatos locales siendo un adolescente.</p>
                    <iframe width="560" height="315" src="https://www.youtube.com/embed/L8oht5ZNwFM?si=dpTMQfG8GVSHclkV" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.leyenda__article__text}>Aldo haría su debut profesional en las MMA el 10 de agosto de 2004 contra el brasileño <b>Mario Bigola</b>, a quien derrotaría por KO a los 18 segundos del primer asalto. Seguiría peleando logrando un récord de 7-0, siendo 5 por nocaut, hasta que llegaría su primera derrota contra <b>Luciano Azevedo</b> que lo sometió en el segundo asalto. Sin embargo se recuperaría en su siguiente pelea ganando por decisión unánime contra el brasileño <b>Thiago Meller</b>. Luego de 2 victorias más por decisión contra <b>Fábio Mello</b> y <b>Shoji Maruyama</b>, comenzaría a pelear en la promtora <b>WEC</b>, donde debutaría con una victoria por TKO contra <b>Alexandre Nogueira</b>.</p>
                    <p className={styles.leyenda__article__text}>Ganaría 5 victorias consecutivas en la compañía hasta tener su oportunidad de pelear por el título, siendo la última de estas en la eliminatoria por el campeonato contra el estadounidense <b>Cub Swanson</b>, a quien venció por nocaut a los 8 segundos de la pelea, ganando además el premio al KO de la noche. Su pelea por el campeonato la tendría contra <b>Mike Brown</b> en noviembre de 2009, a quien fue capaz de noquear en el segundo asalto, ganando nuevamente el premio al KO de la noche y el Campeonato de Peso Pluma de la WEC.</p>
                    <iframe className={styles.leyenda__article__video} width="560" height="315" src="https://www.youtube.com/embed/btCBlJhNPqw?si=5vVvHqytRCzoiXI_" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.leyenda__article__text}>Aldo tendría una defensa exitosa por el título, hasta que por aquellos años, la UFC compra la compañía en la que José estaba peleando, adquiriendo además a todos los peleadores de dicha compañía. Esto hizo, que su segunda defensa del título contra el armenio <b>Manvel Gamburyan</b>, a quien venció por KO en el segundo asalto, sea el último en la entonces WEC, para que su título sea ascendido al Campeonato de Peso Pluma de la UFC, comenzando desde entonces a defender en la compañía liderada por Dana White.</p>
                    <p className={styles.leyenda__article__text}>En UFC, haría un total 8 defensas del título, contando la que hizo contra Gamburyan, convirtiendolo en el peleador con más defensas éxitosas consecutivas en la hisotria de la divisón de peso pluma de la compañía. Finalizando 3 de estas defensas por nocuat, y, debido a lo dominante que siempre se mostró en sus combates, ganando el resto de los combates por decisión unánime. La úlima de estas defensas siendo contra el estadounidense <b>Chad Mendes</b> en UFC 179, a quien ya había derrotado por KO en el primer asalto en el pasado, ganando nuevamente en la revancha por decisión unánime, en lo que sería la pelea de la noche, y la pelea del año 2014.</p>
                    <iframe className={styles.leyenda__article__video} width="560" height="315" src="https://www.youtube.com/embed/K63PJBKuA4U?si=tthIK5jRUXKFzTj_" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.leyenda__article__text}>Lamentablemente, la racha de 18 victorias consecutivas que llevaba, incluidas las 7 defensas del título en UFC, se verían finalizadas cuando el 12 de diciembre se enfrentaría a un joven <Link href='/peleadores/conor-mcgregor'>Conor McGregor</Link> en UFC 194, que venía invicto en la UFC y acababa de derrotar también a <b>Chad Mendes</b> por nocaut en el segundo asalto, perfilandose como un claro contendiente al título. La previa del combate sería bastante intensa, cargada de un trash talk pesado por parte de Conor, que busco de todas las maneras posibles meterse en la cabeza del campeón, cosa que lograría, dado que le bastaron tan sólo 13 segundos para noquear al brasileño, convirtiendose este, en el nocaut más rápido en una pelea por el título. Lo que significaría una derrota durísima para el legendario campeón brasileño.</p>
                    <iframe className={styles.leyenda__article__video} width="560" height="315" src="https://www.youtube.com/embed/7qrVQwjieac?si=IlgBbDoZuJGa-Vup" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen></iframe>
                    <p className={styles.leyenda__article__text}>Pese a la dolorosa derrota sufrida, Aldo volvería a pelear en el UFC 200, esta vez por el campeonato interino de peso pluma de la UFC contra <b>Frankie Edgard</b>, a quien ya había enfrentado y derrotado por decisión unánime en una defensa del título. El combate terminaría de la misma forma, con un José Aldo que se impondría a lo largo de los 5 asaltos, consiguiendo una victoria por decisión unánime nuevamente. Su cinturón interino, debido a la inactividad de Conor, y a que luego este subiría de división para pelear por el título de Peso Ligero, sería ascendido a cinturón del campeón indiscutido.</p>
                    <p className={styles.leyenda__article__text}>Lamentablemente, la recuperación de su cinturón no duraría mucho, puesto que poco después pelearía contra <Link href='/peleadores/max-holloway'>Max Holloway</Link>, quien en el tercer asalto lo noquearía, arrebatandole así el cinturón de campeón. Pocos meses después se organizaría la revancha entre estos 2 por el cinturón, pero el resultado sería el mismo, con un Holloway finalizando por nocaut en el tercer asalto.</p>
                    <p className={styles.leyenda__article__text}>Aldo tendría 3 combates más en la división, ganando los 2 primeros por TKO contra <b>Jeremy Stephens</b> y contra <b>Renato Moicano</b>. Sin embargo perdería el siguiente contra quien tiempo después se convertiría en el campeón de la división, <Link href='/peleadores/alexander-volkanovski'>Alexander Volkanovski</Link>, quien luego de los 5 asaltos se llevaría la pelea por decisión unánime.</p>
                    <iframe className={styles.leyenda__article__video} width="560" height="315" src="https://www.youtube.com/embed/JUXuzqbxlkw?si=8BkzLk2BztpJIoj-" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.leyenda__article__text}>Luego de esto, José Aldo decidiría bajar de división para pelear por el campeonato de Peso Gallo. Allí se pelearía contra el brasileño <b>Marlon Moraes</b>, esperando que el ganador de ese combate sea el siguiente contendiente al título. Sin embargo en una pelea bastante cerrada, Moraes se llevó la victoría por decisión dividida. Pese a esta derrota, el 11 de julio de 2020, Aldo tendría la oportunidad de pelear por el cinturón de Peso Gallo contra el ruso <b>Petr Yan</b>, pero en el quinto asalto perdería por nocaut técnico. Luego de eso, tendría 3 combates más en la división que ganaría de forma consecutiva por decisión unánime, contra el ecuatoriano <Link href='/peleadores/marlon-vera'>Marlon Vera</Link>, contra <b>Pedro Munhoz</b> y contra <b>Rob Font</b>. </p>
                    <p className={styles.leyenda__article__text}>Su última pelea como profesional en la UFC sería contra el georgiano <b>Merab Dvalishvili</b> en UFC 278, quien luego de los 5 asaltos lo vencería por decisión unánime. José Aldo colgaría los guantes luego de la pelea, dejando atrás un récord de 31-8, con un glorioso legado, siendo seguramente <b>el mejor peso pluma de la historia de UFC</b>.</p>
                </article>
                <AsideChamps />
            </section>
        </main>
    )
}