import PeleadoresHero from '@/app/peleadores/components/PeleadoresHero'
import fighter from '@/assets/peleadores__images/0-100/40-60/carlos-prates/carlos_prates.png'
import styles from '@/app/peleadores/components/peleador.module.css'
import Link from 'next/link'
import type { Metadata } from 'next'
import dynamic from 'next/dynamic'

const AsideChamps = dynamic(() => import('@/app/components/asides/AsideChamps'))
const EndArticle = dynamic(() => import('@/app/components/EndArticle'))

export const metadata: Metadata = {
    title: 'Carlos Prates',
    description: 'Carlos Prates es un luchador brasileño de MMA que compite en la división de peso wélter UFC desde el 10 de febrero de 2024, cuando haría su debut oficial ante el peleador estadounidense Trevin Giles, a quien enfrentaría en el UFC Fight Night: Hermansson vs. Pyfer.',
    openGraph: {
        title: 'Carlos Prates',
        description: 'Carlos Prates es un luchador brasileño de MMA que compite en la división de peso wélter UFC desde el 10 de febrero de 2024, cuando haría su debut oficial ante el peleador estadounidense Trevin Giles, a quien enfrentaría en el UFC Fight Night: Hermansson vs. Pyfer.',
        url: 'https://fullmma.org/peleadores/carlos-prates'
    }
}

export default function CarlosPrates () {
    return(
        <main>
            <PeleadoresHero peleadoresImage={fighter} w={17} l={1} d={0} categoria='Peso Wélter' nombre='Carlos Prates' apodo={null} />
            <section className={styles.peleador__articles__container}>
                <article className={styles.peleador__article}>
                    <h2 className={styles.peleador__article__title}>Carlos Prates MMA</h2>
                    <p className={styles.peleador__article__text}>Carlos Prates es un luchador brasileño de MMA que compite en la división de peso wélter UFC desde el 10 de febrero de 2024, cuando haría su debut oficial ante el peleador estadounidense <b>Trevin Giles</b>, a quien enfrentaría en el <b>UFC Fight Night: Hermansson vs. Pyfer</b>. </p>
                    <p className={styles.peleador__article__text}>Es uno de los miembros más reconocidos de los <Link href='/articulos/fighting-nerds'>Fighting Nerds</Link>, quienes lo han llevado a ser de los peleadores más destacados de la división de peso wélter de la UFC, con constantes finalizaciones por KO que llevan a los fanáticos a poner los ojos en él. </p>
                    <h2 className={styles.peleador__article__title}>Carlos Prates Récord</h2>
                    <p className={styles.peleador__article__text}>Carlos Prates posee un récord profesional de MMA de 21-6. Siendo 16 de sus victorias por la vía del nocaut, con sólo 3 siendo por sumisión y sólo 2 por decisión. Mientras que de sus derrotas 2 fueron por nocaut, 3 por sumisión y sólo 1 por decisión. </p>
                    <h2 className={styles.peleador__article__title}>Carlos Prates Historia</h2>
                    <p className={styles.peleador__article__text}>Carlos Augusto Monteiro Prates nació el 17 de agosto de 1993 en la ciudad brasileña Taubaté, en Sao Paulo. Fue críado por una madre soltera, quien fue la mujer que lo inscribió a Carlos a sus 15 años a un gimnasio para que aprendiera la filosofía de las artes marciales, dado que para aquel entonces nuestro protagonista se estaba metiendo en problemas, según él mismo cuenta, tomando malas decisiones de vida, entre las que se encontraba el comenzar a fumar cigarrillos. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/e3W4EEXXH4M?si=BtKB4zE0MxTFLoQj" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>El primer arte marcial que practicaría sería el Muay Thai, donde no arrancaría del todo bien, dado que sufriría 4 derrotas en su carrera temprana, cosa que lo motivó a mudarse a Tailandia para practicar mejor este arte marcial.</p>
                    <p className={styles.peleador__article__text}>Durante un tiempo, Prates compaginaría su carrera como peleador en 3 deportes distintos, siendo estos las MMA, el kickboxing y el Muay Thai. Dedicándose exclusivamente a las MMA en el año 2021. </p>
                    <p className={styles.peleador__article__text}>Centrándonos en lo que hizo como luchador de MMA, haría su debut el 17 de marzo de 2012, en peso ligero, enfrentando a <b>Sergio Vieira</b> en una promotora brasileña, consiguiendo ganar aquel combate por la vía del nocaut en el segundo asalto de la pelea. Tan sólo una semana después tendría su siguiente pelea en la que lograría repetir el hito ante <b>Renato Da Silva Jr.</b>, venciendo por TKO en el tercer asalto. </p>
                    <p className={styles.peleador__article__text}>Comenzaría una racha irregular por su parte, dado que en mayo de ese mismo año se enfrentaría a <b>Rafael Nunes</b>, y caería derrotado por TKO. Un año más tarde, pelearía en peso pluma ante <b>Rodrigo Haro</b>, a quien vencería por decisión mayoritoria. Pero perdería su siguiente combate con fecha para septiembre del 2013, al ser sometido en el primer asalto por <b>Diogo Cavalcanti</b>. Ganaría la siguiente pelea de ese año por KO en el primer asalto ante <b>Cosme Santos</b>. Perdería la siguiente pelea de su carrera por sumisión ante <b>Claudiere Freitas</b>. Volvería a ganar, por sumisión en el tercer asalto ante <b>Bruno Pereira</b>. Pero acabaría perdiendo nuevamente su siguiente pelea ante <b>Ary Santos</b>, quien lo sometería en el primer asalto. </p>
                    <p className={styles.peleador__article__text}>En el 2016 subiría de categoría para pelear en peso wélter, y acá sería capaz de hilar 2 victorias consecutivas, siendo la primera por sumisión en el segundo asalto, en una pelea con fecha para el 10 de enero, ante <b>Yousef Wehbe</b>. Y ganaría por sumisión en el primer asalto ante <b>Sun Jiming</b>, a quien enfrentó el 6 de noviembre de ese año. </p>
                    <p className={styles.peleador__article__text}>Un par de meses después, en enero de 2017 se enfrentaría a <b>Mikhail ROmanchuck</b>, que le propinaría la quinta derrota de su carrera, al noquear a nuestro protagonista en el primer asalto. A pesar de esto, Prates volvería a hilar 2 victorias consecutivas, enfrentando primero a <b>Tao Jiang</b>, a quien sería capaz de vencer por TKO en el segundo asalto; y enfrentando luego a <b>Tuluosibake Kuerbanjiang</b>, a quien también vencería por TKO, esta vez a los 28 segundos del primer asalto. </p>
                    <p className={styles.peleador__article__text}>Habiendo acumulado una racha de 9-5, se le presentaría la oportunidad de pelear en una de las compañías de artes marciales mixtas más grandes del mundo, particularmente popular en el continente asiático, como lo es <b>ONE Championship</b>, donde debutaría el día 25 de abril de 2019, en la categoría de peso mediano, para enfrentar a <b>Gunther Kalunda Ngunza</b>, a quien dejaría KO en el segundo asalto luego de conectar una patada al cuerpo. </p>
                    <p className={styles.peleador__article__text}>Perdería su siguiente combate ante <b>Gadzhimurad Abdullaev</b>, aunque esta vez por decisión, y esta terminaría por ser su última derrota en un largo tiempo, dado que después de su pelea con Abdullaev, acumularía la racha de victorias más larga en su carrera. Comenzando con <b>Joseph Luciano</b>, a quien enfrentaría el 4 de diciembre, venciendo por decisión unánime en lo que sería su última pelea en la compañía asiática. </p>
                    <p className={styles.peleador__article__text}>Para el 2021 ya estaba decidido a dedicarse de lleno a las MMA, por lo que tuvo su siguiente pelea 2 años después, enfrentando en un combate en peso ligero en la promotora <b>Standout Fighting Tournament</b>, a <b>Alan Silva</b>, a quien sería capaz de vencer por TKO en el primer asalto. El 11 de junio de 2022 volvería a pelear para la compañía en peso wélter, enfrentando a <b>Taffarel Brasil</b>, a quien vencería por KO en el segundo asalto de la pelea. </p>
                    <p className={styles.peleador__article__text}>Estas 2 victorias consecutivas en la compañía, le darían la oportunidad de disputar el cinturón de esta, enfrentando para ello a su compatriota <b>Charles de Oliveira Santos</b>, el día 3 de septiembre de ese mismo año, obteniendo una victoria por KO en el primer asalto, y ganando el cinturón vacante de peso wélter de SFT. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/q_U6K8jQN28?si=HUeoXDgg0rT6SAbB" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Comenzaría a pelear en LFA, donde debutaría el 4 de noviembre de 2022, tan sólo un mes después de su última pelea, consiguiendo una victoria por KO en el primer asalto ante <b>Moacir Rocha</b>. Su última pelea en esta compañía sería el 10 de marzo del 2023, enfrentando a <b>Eduardo Ramon</b>, logrando la victoria por KO en el primer asalto. </p>
                    <h2 className={styles.peleador__article__title}>Carlos Prates UFC</h2>
                    <p className={styles.peleador__article__text}>La oportunidad de pelear en la UFC se le presentaría el 18 de noviembre de ese mismo año, teniendo que pasar primero por la prueba que es el reality de de TV, <b>Dana White&apos;s Contender Series</b>, que lo enfrentaría a <b>Mitch Ramirez</b>, a quien conseguiría derrotar por TKO en el segundo asalto, garantizando un contrato con la compañía de artes marciales mixtas más grande del mundo. </p>
                    <p className={styles.peleador__article__text}>A partir de este momento es donde vendría de los más loco visto en un peleador de la UFC, especialmente si tenemos en cuenta la velocidad en que se hizo todo. En el 2024, en su primer año como luchador de la compañía, tendría nada menos que 4 combates a lo largo del año. </p>
                    <p className={styles.peleador__article__text}>El primero sería enfrentando a <b>Trevis Giles</b>, a quien vería cara a cara el 10 de febrero en el <b>UFC Fight Night: Hermansson vs. Pyfer</b>, aquella pelea terminaría en una victoria para nuestro protagonista por KO en el segundo asalto, ganando además, en su primer combate, el primer bono de su carrera a la Actuación de la Noche. </p>
                    <p className={styles.peleador__article__text}>Volvería a subirse al octágono el día 8 de junio en el <Link href='/covertura-ufc/fight-night-cannonier-imanov'>UFC on ESPN: Cannonier vs. Imavov</Link>, enfrentando a <b>Charles Redtke</b>, a quien conseguiría vencer por KO con un rodillazo al cuerpo en el primer asalto. Debido a esta actuación ganaría otro bono a la Actuación de la Noche. </p>
                    <p className={styles.peleador__article__text}>Un par de meses después, el 17 de agosto en el <Link href='/covertura-ufc/ufc305'>UFC 305</Link>, se enfrentaría al peleador chino <b>Li Jingliang</b>, a quien conseguiría derrotar por KO en el segundo asalto de la pelea, ganando por este desempeño otro bono a la Actuación de la Noche. </p>
                    <iframe className={styles.peleador__article__video} loading='lazy' width="560" height="315" src="https://www.youtube.com/embed/1EH02xXy-gM?si=I-Zb_BgRH_Wv5dz5" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen></iframe>
                    <p className={styles.peleador__article__text}>Por último, para finalizar el año, a Carlos Prates se le presentaría la oportunidad de protagonizar su primer cartelera de la UFC, ya en su cuarta pelea en la compañía, enfrentando al veterano luchador estadounidense <b>Neil Magny</b>, a quien en caso de ganar, lo llevaría a entrar a los rankings de la división de peso wélter, ya en su primer año. Se enfrentarían el 9 de noviembre, y Prates sería capaz de finalizar a su rival nuevamente por la vía del KO en el primer asalto, ganando otra vez el bono a la Actuación de la Noche. Cerrando el 2024 con 4 peleas, 4 victorias por KO y 4 bonos por desempeño. </p>
                    <EndArticle />
                </article>
                <AsideChamps />
            </section>
        </main>
    )
}